# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "pcar"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_pcar_faceSideWiWheels_Fa0_Ctr0():
	P000 = App.Vector(-900.0000, 100.0000, 0)
	P001 = App.Vector(-346.4102, 100.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-0.0000, 700.0000, 0)
	P003 = App.Vector(346.4102, 100.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(2653.5898, 100.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(3000.0000, 700.0000, 0)
	P006 = App.Vector(3346.4102, 100.0000, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(3900.0000, 100.0000, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(3970.7107, 129.2893, 0)
	P009 = App.Vector(4000.0000, 200.0000, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(4000.0000, 623.1880, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(3894.7394, 930.0769, 0)
	P012 = App.Vector(3623.2768, 1107.7525, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(3028.1444, 1230.5109, 0)
	P014 = App.Vector(2424.2910, 1298.4317, 0)
	S008 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(2400.9380, 1302.8113, 0)
	P016 = App.Vector(2379.2774, 1312.5767, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(1808.9929, 1600.4040, 0)
	P018 = App.Vector(1202.0104, 1799.5049, 0)
	S010 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(1200.0136, 1800.0190, 0)
	P020 = App.Vector(1198.0279, 1800.5743, 0)
	S011 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(505.4437, 1899.9941, 0)
	P022 = App.Vector(-187.5670, 1803.5914, 0)
	S012 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-199.6676, 1799.2714, 0)
	P024 = App.Vector(-211.1144, 1793.4355, 0)
	S013 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(-624.4206, 1495.0407, 0)
	P026 = App.Vector(-977.9568, 1127.7892, 0)
	S014 = Part.Arc(P024, P025, P026)
	P027 = App.Vector(-994.3284, 1098.3563, 0)
	P028 = App.Vector(-1000.0000, 1065.1575, 0)
	S015 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-1000.0000, 200.0000, 0)
	S016 = Part.LineSegment(P028, P029)
	P030 = App.Vector(-970.7107, 129.2893, 0)
	P031 = App.Vector(-900.0000, 100.0000, 0)
	S017 = Part.Arc(P029, P030, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_pcar_faceSideWiWheels_Fa0():
	FC000 = ctr_face_pcar_faceSideWiWheels_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def pcar_faceSideWiWheels():
	FA000 = face_pcar_faceSideWiWheels_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_pcar_faceSideWoWheels_Fa0_Ctr0():
	P000 = App.Vector(-900.0000, 100.0000, 0)
	P001 = App.Vector(3900.0000, 100.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(3970.7107, 129.2893, 0)
	P003 = App.Vector(4000.0000, 200.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(4000.0000, 623.1880, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(3894.7394, 930.0769, 0)
	P006 = App.Vector(3623.2768, 1107.7525, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(3028.1444, 1230.5109, 0)
	P008 = App.Vector(2424.2910, 1298.4317, 0)
	S004 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(2400.9380, 1302.8113, 0)
	P010 = App.Vector(2379.2774, 1312.5767, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(1808.9929, 1600.4040, 0)
	P012 = App.Vector(1202.0104, 1799.5049, 0)
	S006 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(1200.0136, 1800.0190, 0)
	P014 = App.Vector(1198.0279, 1800.5743, 0)
	S007 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(505.4437, 1899.9941, 0)
	P016 = App.Vector(-187.5670, 1803.5914, 0)
	S008 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(-199.6676, 1799.2714, 0)
	P018 = App.Vector(-211.1144, 1793.4355, 0)
	S009 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(-624.4206, 1495.0407, 0)
	P020 = App.Vector(-977.9568, 1127.7892, 0)
	S010 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(-994.3284, 1098.3563, 0)
	P022 = App.Vector(-1000.0000, 1065.1575, 0)
	S011 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-1000.0000, 200.0000, 0)
	S012 = Part.LineSegment(P022, P023)
	P024 = App.Vector(-970.7107, 129.2893, 0)
	P025 = App.Vector(-900.0000, 100.0000, 0)
	S013 = Part.Arc(P023, P024, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_pcar_faceSideWoWheels_Fa0():
	FC000 = ctr_face_pcar_faceSideWoWheels_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def pcar_faceSideWoWheels():
	FA000 = face_pcar_faceSideWoWheels_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_pcar_faceTop_Fa0_Ctr0():
	P000 = App.Vector(-863.1403, 46.5162, 0)
	P001 = App.Vector(1366.1245, 0.1492, 0)
	P002 = App.Vector(3595.5739, 36.5759, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(3860.1396, 149.2363, 0)
	P004 = App.Vector(3980.7649, 410.2667, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(4000.0000, 1000.0000, 0)
	P006 = App.Vector(3980.7649, 1589.7333, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(3860.1396, 1850.7637, 0)
	P008 = App.Vector(3595.5739, 1963.4241, 0)
	S003 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(1366.1245, 1999.8508, 0)
	P010 = App.Vector(-863.1403, 1953.4838, 0)
	S004 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(-927.9028, 1926.2291, 0)
	P012 = App.Vector(-958.7492, 1863.0983, 0)
	S005 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(-1000.0000, 1000.0000, 0)
	P014 = App.Vector(-958.7492, 136.9017, 0)
	S006 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(-927.9028, 73.7709, 0)
	P016 = App.Vector(-863.1403, 46.5162, 0)
	S007 = Part.Arc(P014, P015, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_pcar_faceTop_Fa0():
	FC000 = ctr_face_pcar_faceTop_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def pcar_faceTop():
	FA000 = face_pcar_faceTop_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_pcar_faceFront_Fa0_Ctr0():
	P000 = App.Vector(129.7993, 100.0000, 0)
	P001 = App.Vector(1870.2007, 100.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1933.5757, 122.6462, 0)
	P003 = App.Vector(1968.2466, 180.3279, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(1999.5603, 537.7996, 0)
	P005 = App.Vector(1951.6545, 893.4282, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(1950.2335, 900.0774, 0)
	P007 = App.Vector(1949.2677, 906.8077, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(1854.2384, 1368.9622, 0)
	P009 = App.Vector(1674.2749, 1805.1163, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(1643.4019, 1840.2108, 0)
	P011 = App.Vector(1599.9520, 1857.4407, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(1000.0000, 1900.0000, 0)
	P013 = App.Vector(400.0480, 1857.4407, 0)
	S006 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(356.5981, 1840.2108, 0)
	P015 = App.Vector(325.7251, 1805.1163, 0)
	S007 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(145.7616, 1368.9622, 0)
	P017 = App.Vector(50.7323, 906.8077, 0)
	S008 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(49.7665, 900.0774, 0)
	P019 = App.Vector(48.3455, 893.4282, 0)
	S009 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(0.4397, 537.7996, 0)
	P021 = App.Vector(31.7534, 180.3279, 0)
	S010 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(66.4243, 122.6462, 0)
	P023 = App.Vector(129.7993, 100.0000, 0)
	S011 = Part.Arc(P021, P022, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_pcar_faceFront_Fa0():
	FC000 = ctr_face_pcar_faceFront_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def pcar_faceFront():
	FA000 = face_pcar_faceFront_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_pcar_faceWheel_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(50.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(50.0000, 300.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(250.0000, 300.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(285.3553, 314.6447, 0)
	P005 = App.Vector(300.0000, 350.0000, 0)
	S003 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(300.0000, 450.0000, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(285.3553, 485.3553, 0)
	P008 = App.Vector(250.0000, 500.0000, 0)
	S005 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(0.0000, 500.0000, 0)
	S006 = Part.LineSegment(P008, P009)
	P010 = App.Vector(0.0000, 0.0000, 0)
	S007 = Part.LineSegment(P009, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_pcar_faceWheel_Fa0():
	FC000 = ctr_face_pcar_faceWheel_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def pcar_faceWheel():
	FA000 = face_pcar_faceWheel_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_pcar_sideWiW1():
	FIG = pcar_faceSideWiWheels()
	VEX = FIG.extrude(App.Vector(0, 0, 600))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 600.0000, 0.0000))
	return VFP
subpax_pcar_sideWiW1 = fex_subpax_pcar_sideWiW1()

def fex_subpax_pcar_sideWiW2():
	FIG = pcar_faceSideWiWheels()
	VEX = FIG.extrude(App.Vector(0, 0, 600))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 2000.0000, 0.0000))
	return VFP
subpax_pcar_sideWiW2 = fex_subpax_pcar_sideWiW2()

def fex_subpax_pcar_sideWoW():
	FIG = pcar_faceSideWoWheels()
	VEX = FIG.extrude(App.Vector(0, 0, 800))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 1400.0000, 0.0000))
	return VFP
subpax_pcar_sideWoW = fex_subpax_pcar_sideWoW()

def fex_subpax_pcar_front():
	FIG = pcar_faceFront()
	VEX = FIG.extrude(App.Vector(0, 0, 5000))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 90.0000)
	VFP = VR3.translate(App.Vector(-1000.0000, 0.0000, 0.0000))
	return VFP
subpax_pcar_front = fex_subpax_pcar_front()

def fex_subpax_pcar_top():
	FIG = pcar_faceTop()
	VEX = FIG.extrude(App.Vector(0, 0, 1900))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_pcar_top = fex_subpax_pcar_top()

def fex_subpax_pcar_wheel11():
	FIG = pcar_faceWheel()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 600.0000, 300.0000))
	return VFP
subpax_pcar_wheel11 = fex_subpax_pcar_wheel11()

def fex_subpax_pcar_wheel12():
	FIG = pcar_faceWheel()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 1400.0000, 300.0000))
	return VFP
subpax_pcar_wheel12 = fex_subpax_pcar_wheel12()

def fex_subpax_pcar_wheel21():
	FIG = pcar_faceWheel()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(3000.0000, 600.0000, 300.0000))
	return VFP
subpax_pcar_wheel21 = fex_subpax_pcar_wheel21()

def fex_subpax_pcar_wheel22():
	FIG = pcar_faceWheel()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(3000.0000, 1400.0000, 300.0000))
	return VFP
subpax_pcar_wheel22 = fex_subpax_pcar_wheel22()

def fvol_ipax_pcar_side():
	V000 = subpax_pcar_sideWiW1
	V001 = V000.fuse(subpax_pcar_sideWiW2)
	V002 = V001.fuse(subpax_pcar_sideWoW)
	VFC = V002.removeSplitter()
	return VFC
ipax_pcar_side = fvol_ipax_pcar_side()

def fvol_ipax_pcar_body():
	V000 = ipax_pcar_side
	V001 = V000.common(subpax_pcar_front)
	V002 = V001.common(subpax_pcar_top)
	VFC = V002.removeSplitter()
	return VFC
ipax_pcar_body = fvol_ipax_pcar_body()

def fvol_pax_pcar():
	V000 = ipax_pcar_body
	V001 = V000.fuse(subpax_pcar_wheel11)
	V002 = V001.fuse(subpax_pcar_wheel12)
	V003 = V002.fuse(subpax_pcar_wheel21)
	V004 = V003.fuse(subpax_pcar_wheel22)
	VFC = V004.removeSplitter()
	return VFC
pax_pcar = fvol_pax_pcar()


pax_pcar.check()
#pax_pcar.exportBrep(f"{outFileName}.brep")
#pax_pcar.exportIges(f"{outFileName}.igs")
#pax_pcar.exportStep(f"{outFileName}.stp")
pax_pcar.exportStl(f"{outFileName}.stl")

