# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "springTorqueB"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(42.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr1():
	P000 = App.Vector(8.8273, -0.0000, 0)
	P001 = App.Vector(10.9717, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(11.7472, 0.3686, 0)
	P003 = App.Vector(11.9509, 1.2028, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(11.4457, 3.6424, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(10.9274, 4.3270, 0)
	P006 = App.Vector(10.0693, 4.3574, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(8.1013, 3.5057, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(7.4251, 3.4632, 0)
	P009 = App.Vector(6.8770, 3.8614, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(6.1219, 4.9726, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(5.9534, 5.6288, 0)
	P012 = App.Vector(6.2418, 6.2418, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(7.7582, 7.7582, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(8.0458, 8.5672, 0)
	P015 = App.Vector(7.6001, 9.3011, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(5.5177, 10.6689, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(4.6672, 10.7866, 0)
	P018 = App.Vector(4.0389, 10.2012, 0)
	S011 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(3.2495, 8.2074, 0)
	S012 = Part.LineSegment(P018, P019)
	P020 = App.Vector(2.8015, 7.6992, 0)
	P021 = App.Vector(2.1324, 7.5932, 0)
	S013 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(0.8126, 7.8450, 0)
	S014 = Part.LineSegment(P021, P022)
	P023 = App.Vector(0.2295, 8.1898, 0)
	P024 = App.Vector(0.0000, 8.8273, 0)
	S015 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(0.0000, 10.9717, 0)
	S016 = Part.LineSegment(P024, P025)
	P026 = App.Vector(-0.3686, 11.7472, 0)
	P027 = App.Vector(-1.2028, 11.9509, 0)
	S017 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(-3.6424, 11.4457, 0)
	S018 = Part.LineSegment(P027, P028)
	P029 = App.Vector(-4.3270, 10.9274, 0)
	P030 = App.Vector(-4.3574, 10.0693, 0)
	S019 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(-3.5057, 8.1013, 0)
	S020 = Part.LineSegment(P030, P031)
	P032 = App.Vector(-3.4632, 7.4251, 0)
	P033 = App.Vector(-3.8614, 6.8770, 0)
	S021 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(-4.9726, 6.1219, 0)
	S022 = Part.LineSegment(P033, P034)
	P035 = App.Vector(-5.6288, 5.9534, 0)
	P036 = App.Vector(-6.2418, 6.2418, 0)
	S023 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-7.7582, 7.7582, 0)
	S024 = Part.LineSegment(P036, P037)
	P038 = App.Vector(-8.5672, 8.0458, 0)
	P039 = App.Vector(-9.3011, 7.6001, 0)
	S025 = Part.Arc(P037, P038, P039)
	P040 = App.Vector(-10.6689, 5.5177, 0)
	S026 = Part.LineSegment(P039, P040)
	P041 = App.Vector(-10.7866, 4.6672, 0)
	P042 = App.Vector(-10.2012, 4.0389, 0)
	S027 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(-8.2074, 3.2495, 0)
	S028 = Part.LineSegment(P042, P043)
	P044 = App.Vector(-7.6992, 2.8015, 0)
	P045 = App.Vector(-7.5932, 2.1324, 0)
	S029 = Part.Arc(P043, P044, P045)
	P046 = App.Vector(-7.8450, 0.8126, 0)
	S030 = Part.LineSegment(P045, P046)
	P047 = App.Vector(-8.1898, 0.2295, 0)
	P048 = App.Vector(-8.8273, 0.0000, 0)
	S031 = Part.Arc(P046, P047, P048)
	P049 = App.Vector(-10.9717, 0.0000, 0)
	S032 = Part.LineSegment(P048, P049)
	P050 = App.Vector(-11.7472, -0.3686, 0)
	P051 = App.Vector(-11.9509, -1.2028, 0)
	S033 = Part.Arc(P049, P050, P051)
	P052 = App.Vector(-11.4457, -3.6424, 0)
	S034 = Part.LineSegment(P051, P052)
	P053 = App.Vector(-10.9274, -4.3270, 0)
	P054 = App.Vector(-10.0693, -4.3574, 0)
	S035 = Part.Arc(P052, P053, P054)
	P055 = App.Vector(-8.1013, -3.5057, 0)
	S036 = Part.LineSegment(P054, P055)
	P056 = App.Vector(-7.4251, -3.4632, 0)
	P057 = App.Vector(-6.8770, -3.8614, 0)
	S037 = Part.Arc(P055, P056, P057)
	P058 = App.Vector(-6.1219, -4.9726, 0)
	S038 = Part.LineSegment(P057, P058)
	P059 = App.Vector(-5.9534, -5.6288, 0)
	P060 = App.Vector(-6.2418, -6.2418, 0)
	S039 = Part.Arc(P058, P059, P060)
	P061 = App.Vector(-7.7582, -7.7582, 0)
	S040 = Part.LineSegment(P060, P061)
	P062 = App.Vector(-8.0458, -8.5672, 0)
	P063 = App.Vector(-7.6001, -9.3011, 0)
	S041 = Part.Arc(P061, P062, P063)
	P064 = App.Vector(-5.5177, -10.6689, 0)
	S042 = Part.LineSegment(P063, P064)
	P065 = App.Vector(-4.6672, -10.7866, 0)
	P066 = App.Vector(-4.0389, -10.2012, 0)
	S043 = Part.Arc(P064, P065, P066)
	P067 = App.Vector(-3.2495, -8.2074, 0)
	S044 = Part.LineSegment(P066, P067)
	P068 = App.Vector(-2.8015, -7.6992, 0)
	P069 = App.Vector(-2.1324, -7.5932, 0)
	S045 = Part.Arc(P067, P068, P069)
	P070 = App.Vector(-0.8126, -7.8450, 0)
	S046 = Part.LineSegment(P069, P070)
	P071 = App.Vector(-0.2295, -8.1898, 0)
	P072 = App.Vector(-0.0000, -8.8273, 0)
	S047 = Part.Arc(P070, P071, P072)
	P073 = App.Vector(-0.0000, -10.9717, 0)
	S048 = Part.LineSegment(P072, P073)
	P074 = App.Vector(0.3686, -11.7472, 0)
	P075 = App.Vector(1.2028, -11.9509, 0)
	S049 = Part.Arc(P073, P074, P075)
	P076 = App.Vector(3.6424, -11.4457, 0)
	S050 = Part.LineSegment(P075, P076)
	P077 = App.Vector(4.3270, -10.9274, 0)
	P078 = App.Vector(4.3574, -10.0693, 0)
	S051 = Part.Arc(P076, P077, P078)
	P079 = App.Vector(3.5057, -8.1013, 0)
	S052 = Part.LineSegment(P078, P079)
	P080 = App.Vector(3.4632, -7.4251, 0)
	P081 = App.Vector(3.8614, -6.8770, 0)
	S053 = Part.Arc(P079, P080, P081)
	P082 = App.Vector(4.9726, -6.1219, 0)
	S054 = Part.LineSegment(P081, P082)
	P083 = App.Vector(5.6288, -5.9534, 0)
	P084 = App.Vector(6.2418, -6.2418, 0)
	S055 = Part.Arc(P082, P083, P084)
	P085 = App.Vector(7.7582, -7.7582, 0)
	S056 = Part.LineSegment(P084, P085)
	P086 = App.Vector(8.5672, -8.0458, 0)
	P087 = App.Vector(9.3011, -7.6001, 0)
	S057 = Part.Arc(P085, P086, P087)
	P088 = App.Vector(10.6689, -5.5177, 0)
	S058 = Part.LineSegment(P087, P088)
	P089 = App.Vector(10.7866, -4.6672, 0)
	P090 = App.Vector(10.2012, -4.0389, 0)
	S059 = Part.Arc(P088, P089, P090)
	P091 = App.Vector(8.2074, -3.2495, 0)
	S060 = Part.LineSegment(P090, P091)
	P092 = App.Vector(7.6992, -2.8015, 0)
	P093 = App.Vector(7.5932, -2.1324, 0)
	S061 = Part.Arc(P091, P092, P093)
	P094 = App.Vector(7.8450, -0.8126, 0)
	S062 = Part.LineSegment(P093, P094)
	P095 = App.Vector(8.1898, -0.2295, 0)
	P096 = App.Vector(8.8273, -0.0000, 0)
	S063 = Part.Arc(P094, P095, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047, S048, S049, S050, S051, S052, S053, S054, S055, S056, S057, S058, S059, S060, S061, S062, S063])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(15.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(10.6066, 10.6066, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(0.0000, 15.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-10.6066, 10.6066, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-15.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-10.6066, -10.6066, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-0.0000, -15.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr9():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(10.6066, -10.6066, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr10():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(40.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr11():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(36.9552, 15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr12():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(28.2843, 28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr13():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(15.3073, 36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr14():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(0.0000, 40.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr15():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-15.3073, 36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr16():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-28.2843, 28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr17():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-36.9552, 15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr18():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-40.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr19():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-36.9552, -15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr20():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-28.2843, -28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr21():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-15.3073, -36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr22():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-0.0000, -40.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr23():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(15.3073, -36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr24():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(28.2843, -28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr25():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(36.9552, -15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr26():
	P000 = App.Vector(17.9374, 0.5000, 0)
	P001 = App.Vector(27.3523, 0.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(27.5980, 0.6625, 0)
	P003 = App.Vector(27.5445, 0.9522, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(27.0921, 1.4215, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(26.8128, 2.7319, 0)
	P006 = App.Vector(27.8660, 3.5602, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(36.6946, 4.5288, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(37.3780, 4.9130, 0)
	P009 = App.Vector(37.5743, 5.6721, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(36.8572, 9.2490, 0)
	P011 = App.Vector(35.8005, 12.7407, 0)
	S006 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(35.2691, 13.3172, 0)
	P013 = App.Vector(34.4852, 13.3331, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(26.2453, 10.0186, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(26.0787, 9.7907, 0)
	P016 = App.Vector(26.2099, 9.5407, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(26.7721, 9.2108, 0)
	S010 = Part.LineSegment(P016, P017)
	P018 = App.Vector(27.3876, 7.9555, 0)
	P019 = App.Vector(26.4729, 6.8981, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(17.4071, 4.3580, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(16.8265, 3.9211, 0)
	P022 = App.Vector(16.6949, 3.2065, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(16.8417, 2.3148, 0)
	P024 = App.Vector(16.9409, 1.4167, 0)
	S014 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(17.2604, 0.7640, 0)
	P026 = App.Vector(17.9374, 0.5000, 0)
	S015 = Part.Arc(P024, P025, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr27():
	P000 = App.Vector(17.1373, 5.3209, 0)
	P001 = App.Vector(26.2031, 7.8610, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(26.3958, 8.0838, 0)
	P003 = App.Vector(26.2662, 8.3483, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(25.7039, 8.6781, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(25.0815, 9.8646, 0)
	P006 = App.Vector(25.8721, 10.9463, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(34.1120, 14.2609, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(34.6665, 14.8152, 0)
	P009 = App.Vector(34.6506, 15.5991, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(32.9951, 18.8500, 0)
	P011 = App.Vector(31.0355, 21.9271, 0)
	S006 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(30.3683, 22.3388, 0)
	P013 = App.Vector(29.6091, 22.1427, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(22.5691, 16.7279, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(22.4702, 16.4636, 0)
	P016 = App.Vector(22.6639, 16.2582, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(23.2943, 16.0923, 0)
	S010 = Part.LineSegment(P016, P017)
	P018 = App.Vector(24.2256, 15.0496, 0)
	P019 = App.Vector(23.6301, 13.7846, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(15.5858, 8.8928, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(15.1446, 8.3154, 0)
	P022 = App.Vector(15.2107, 7.5918, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(15.5926, 6.7728, 0)
	P024 = App.Vector(15.9304, 5.9347, 0)
	S014 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(16.4142, 5.3925, 0)
	P026 = App.Vector(17.1373, 5.3209, 0)
	S015 = Part.Arc(P024, P025, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr28():
	P000 = App.Vector(15.0663, 9.7472, 0)
	P001 = App.Vector(23.1106, 14.6390, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(23.2360, 14.9055, 0)
	P003 = App.Vector(23.0398, 15.1253, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(22.4094, 15.2911, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(21.4900, 16.2657, 0)
	P006 = App.Vector(21.9594, 17.5206, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(28.9995, 22.9354, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(29.3838, 23.6187, 0)
	P009 = App.Vector(29.1571, 24.3693, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(26.6859, 27.0529, 0)
	P011 = App.Vector(23.9688, 29.4872, 0)
	S006 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(23.2152, 29.7037, 0)
	P013 = App.Vector(22.5371, 29.3100, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(17.2190, 22.1967, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(17.1951, 21.9154, 0)
	P016 = App.Vector(17.4371, 21.7700, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(18.0888, 21.7803, 0)
	S010 = Part.LineSegment(P016, P017)
	P018 = App.Vector(19.2669, 21.0275, 0)
	P019 = App.Vector(19.0348, 19.6488, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(12.6086, 12.7680, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(12.3395, 12.0930, 0)
	P022 = App.Vector(12.5984, 11.4140, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(13.1871, 10.7285, 0)
	P024 = App.Vector(13.7385, 10.0126, 0)
	S014 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(14.3506, 9.6210, 0)
	P026 = App.Vector(15.0663, 9.7472, 0)
	S015 = Part.Arc(P024, P025, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr29():
	P000 = App.Vector(11.8778, 13.4506, 0)
	P001 = App.Vector(18.3040, 20.3313, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(18.3529, 20.6218, 0)
	P003 = App.Vector(18.1047, 20.7804, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(17.4529, 20.7701, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(16.3046, 21.4605, 0)
	P006 = App.Vector(16.4181, 22.7955, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(21.7362, 29.9088, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(21.9219, 30.6706, 0)
	P009 = App.Vector(21.5011, 31.3321, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(18.3975, 33.2495, 0)
	P011 = App.Vector(15.1244, 34.8605, 0)
	S006 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(14.3404, 34.8656, 0)
	P013 = App.Vector(13.7936, 34.3036, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(10.5919, 26.0192, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(10.6448, 25.7419, 0)
	P016 = App.Vector(10.9170, 25.6671, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(11.5418, 25.8529, 0)
	S010 = Part.LineSegment(P016, P017)
	P018 = App.Vector(12.8793, 25.4459, 0)
	P019 = App.Vector(13.0278, 24.0557, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(8.6963, 15.6963, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(8.6193, 14.9737, 0)
	P022 = App.Vector(9.0517, 14.3898, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(9.8036, 13.8885, 0)
	P024 = App.Vector(10.5277, 13.3479, 0)
	S014 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(11.2228, 13.1360, 0)
	P026 = App.Vector(11.8778, 13.4506, 0)
	S015 = Part.Arc(P024, P025, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr30():
	P000 = App.Vector(7.8084, 16.1564, 0)
	P001 = App.Vector(12.1399, 24.5158, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(12.1086, 24.8087, 0)
	P003 = App.Vector(11.8268, 24.8944, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(11.2020, 24.7086, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(9.9100, 25.0636, 0)
	P006 = App.Vector(9.6591, 26.3797, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(12.8609, 34.6641, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(12.8342, 35.4477, 0)
	P009 = App.Vector(12.2505, 35.9712, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(8.7447, 36.9801, 0)
	P011 = App.Vector(5.1583, 37.6483, 0)
	S006 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(4.4020, 37.4416, 0)
	P013 = App.Vector(4.0271, 36.7530, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(3.1792, 27.9120, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(3.3049, 27.6593, 0)
	P016 = App.Vector(3.5872, 27.6607, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(4.1387, 28.0082, 0)
	S010 = Part.LineSegment(P016, P017)
	P018 = App.Vector(5.5365, 27.9771, 0)
	P019 = App.Vector(6.0545, 26.6785, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(4.1390, 17.4605, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(4.2598, 16.7439, 0)
	P022 = App.Vector(4.8338, 16.2983, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(5.6930, 16.0184, 0)
	P024 = App.Vector(6.5361, 15.6933, 0)
	S014 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(7.2625, 15.6767, 0)
	P026 = App.Vector(7.8084, 16.1564, 0)
	S015 = Part.Arc(P024, P025, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr31():
	P000 = App.Vector(3.1599, 17.6639, 0)
	P001 = App.Vector(5.0755, 26.8819, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(4.9663, 27.1555, 0)
	P003 = App.Vector(4.6718, 27.1621, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(4.1203, 26.8146, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(2.7805, 26.8078, 0)
	P006 = App.Vector(2.1838, 28.0075, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(3.0317, 36.8485, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(2.7946, 37.5958, 0)
	P009 = App.Vector(2.0913, 37.9424, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-1.5567, 37.9681, 0)
	P011 = App.Vector(-5.1904, 37.6439, 0)
	S006 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(-5.8629, 37.2408, 0)
	P013 = App.Vector(-6.0380, 36.4766, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(-4.4692, 27.7347, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(-4.2800, 27.5253, 0)
	P016 = App.Vector(-4.0086, 27.6028, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(-3.5712, 28.0862, 0)
	S010 = Part.LineSegment(P016, P017)
	P018 = App.Vector(-2.2169, 28.4333, 0)
	P019 = App.Vector(-1.3678, 27.3227, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(-0.7253, 17.9297, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-0.4157, 17.2723, 0)
	P022 = App.Vector(0.2573, 16.9981, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(1.1601, 16.9604, 0)
	P024 = App.Vector(2.0597, 16.8748, 0)
	S014 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(2.7637, 17.0548, 0)
	P026 = App.Vector(3.1599, 17.6639, 0)
	S015 = Part.Arc(P024, P025, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr32():
	P000 = App.Vector(-1.7229, 17.8615, 0)
	P001 = App.Vector(-2.3654, 27.2544, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-2.5443, 27.4884, 0)
	P003 = App.Vector(-2.8297, 27.4153, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-3.2670, 26.9319, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-4.5553, 26.5639, 0)
	P006 = App.Vector(-5.4535, 27.5581, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-7.0223, 36.3000, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-7.4523, 36.9556, 0)
	P009 = App.Vector(-8.2230, 37.0996, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-11.7426, 36.1401, 0)
	P011 = App.Vector(-15.1541, 34.8476, 0)
	S006 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(-15.6930, 34.2781, 0)
	P013 = App.Vector(-15.6554, 33.4949, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(-11.7862, 25.5005, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(-11.5475, 25.3498, 0)
	P016 = App.Vector(-11.3071, 25.4977, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(-11.0164, 26.0812, 0)
	S010 = Part.LineSegment(P016, P017)
	P018 = App.Vector(-9.8059, 26.7808, 0)
	P019 = App.Vector(-8.6886, 25.9405, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(-5.5357, 17.0691, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-5.0602, 16.5196, 0)
	P022 = App.Vector(-4.3383, 16.4371, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-3.4588, 16.6444, 0)
	P024 = App.Vector(-2.5694, 16.8047, 0)
	S014 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(-1.9401, 17.1680, 0)
	P026 = App.Vector(-1.7229, 17.8615, 0)
	S015 = Part.Arc(P024, P025, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr33():
	P000 = App.Vector(-6.4780, 16.7343, 0)
	P001 = App.Vector(-9.6309, 25.6056, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-9.8663, 25.7826, 0)
	P003 = App.Vector(-10.1213, 25.6352, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-10.4120, 25.0518, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-11.5532, 24.3498, 0)
	P006 = App.Vector(-12.6864, 25.0648, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-16.5555, 33.0593, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-17.1464, 33.5746, 0)
	P009 = App.Vector(-17.9274, 33.5053, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-21.0577, 31.6318, 0)
	P011 = App.Vector(-23.9939, 29.4668, 0)
	S006 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(-24.3591, 28.7730, 0)
	P013 = App.Vector(-24.1117, 28.0290, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(-18.2291, 21.3749, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(-17.9586, 21.2943, 0)
	P016 = App.Vector(-17.7670, 21.5016, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(-17.6445, 22.1418, 0)
	S010 = Part.LineSegment(P016, P017)
	P018 = App.Vector(-16.6677, 23.1421, 0)
	P019 = App.Vector(-15.3651, 22.6344, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(-9.9357, 14.9426, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-9.3295, 14.5418, 0)
	P022 = App.Vector(-8.6121, 14.6571, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-7.8211, 15.0940, 0)
	P024 = App.Vector(-7.0080, 15.4883, 0)
	S014 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(-6.5001, 16.0079, 0)
	P026 = App.Vector(-6.4780, 16.7343, 0)
	S015 = Part.Arc(P024, P025, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr34():
	P000 = App.Vector(-10.7526, 14.3660, 0)
	P001 = App.Vector(-16.1820, 22.0577, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-16.4565, 22.1647, 0)
	P003 = App.Vector(-16.6623, 21.9539, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-16.7848, 21.3137, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-17.6943, 20.3298, 0)
	P006 = App.Vector(-18.9783, 20.7126, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-24.8609, 27.3667, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-25.5689, 27.7035, 0)
	P009 = App.Vector(-26.3023, 27.4261, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-28.8110, 24.7776, 0)
	P011 = App.Vector(-31.0542, 21.9006, 0)
	S006 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(-31.2187, 21.1340, 0)
	P013 = App.Vector(-30.7797, 20.4844, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(-23.3200, 15.6641, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(-23.0378, 15.6595, 0)
	P016 = App.Vector(-22.9092, 15.9108, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(-22.9640, 16.5603, 0)
	S010 = Part.LineSegment(P016, P017)
	P018 = App.Vector(-22.2933, 17.7870, 0)
	P019 = App.Vector(-20.9020, 17.6496, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(-13.5987, 11.7079, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-12.9069, 11.4855, 0)
	P022 = App.Vector(-12.2472, 11.7901, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-11.6034, 12.4242, 0)
	P024 = App.Vector(-10.9268, 13.0232, 0)
	S014 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(-10.5779, 13.6606, 0)
	P026 = App.Vector(-10.7526, 14.3660, 0)
	S015 = Part.Arc(P024, P025, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr35():
	P000 = App.Vector(-14.2298, 10.9322, 0)
	P001 = App.Vector(-21.5330, 16.8739, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-21.8262, 16.9028, 0)
	P003 = App.Vector(-21.9675, 16.6444, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-21.9127, 15.9948, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-22.5231, 14.8021, 0)
	P006 = App.Vector(-23.8628, 14.8242, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-31.3224, 19.6445, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-32.0951, 19.7778, 0)
	P009 = App.Vector(-32.7264, 19.3128, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-34.4275, 16.0856, 0)
	P011 = App.Vector(-35.8113, 12.7102, 0)
	S006 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(-35.7629, 11.9276, 0)
	P013 = App.Vector(-35.1649, 11.4205, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(-26.6814, 8.7916, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(-26.4083, 8.8633, 0)
	P016 = App.Vector(-26.3523, 9.1399, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(-26.5803, 9.7506, 0)
	S010 = Part.LineSegment(P016, P017)
	P018 = App.Vector(-26.2655, 11.1128, 0)
	P019 = App.Vector(-24.8887, 11.3558, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(-16.2532, 7.6049, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-15.5270, 7.5773, 0)
	P022 = App.Vector(-14.9740, 8.0486, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-14.5251, 8.8329, 0)
	P024 = App.Vector(-14.0353, 9.5923, 0)
	S014 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(-13.8712, 10.3002, 0)
	P026 = App.Vector(-14.2298, 10.9322, 0)
	S015 = Part.Arc(P024, P025, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr36():
	P000 = App.Vector(-16.6516, 6.6877, 0)
	P001 = App.Vector(-25.2871, 10.4386, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-25.5771, 10.3874, 0)
	P003 = App.Vector(-25.6435, 10.1004, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-25.4155, 9.4897, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-25.6814, 8.1765, 0)
	P006 = App.Vector(-26.9774, 7.8364, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-35.4609, 10.4653, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-36.2409, 10.3852, 0)
	P009 = App.Vector(-36.7233, 9.7672, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-37.4907, 6.2007, 0)
	P011 = App.Vector(-37.9125, 2.5771, 0)
	S006 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(-37.6548, 1.8366, 0)
	P013 = App.Vector(-36.9421, 1.5096, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(-28.0639, 1.2670, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(-27.8203, 1.4097, 0)
	P016 = App.Vector(-27.8410, 1.6912, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(-28.2253, 2.2178, 0)
	S010 = Part.LineSegment(P016, P017)
	P018 = App.Vector(-28.2897, 3.6144, 0)
	P019 = App.Vector(-27.0295, 4.2198, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(-17.7022, 2.9378, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-16.9956, 3.1072, 0)
	P022 = App.Vector(-16.5902, 3.7103, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-16.3696, 4.5865, 0)
	P024 = App.Vector(-16.1028, 5.4499, 0)
	S014 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(-16.1358, 6.1758, 0)
	P026 = App.Vector(-16.6516, 6.6877, 0)
	S015 = Part.Arc(P024, P025, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr37():
	P000 = App.Vector(-17.8384, 1.9471, 0)
	P001 = App.Vector(-27.1656, 3.2291, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-27.4312, 3.1016, 0)
	P003 = App.Vector(-27.4176, 2.8073, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-27.0333, 2.2808, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-26.9351, 0.9446, 0)
	P006 = App.Vector(-28.0912, 0.2674, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-36.9694, 0.5100, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-37.6989, 0.2224, 0)
	P009 = App.Vector(-37.9967, -0.5029, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-37.7734, -4.1441, 0)
	P011 = App.Vector(-37.2019, -7.7472, 0)
	S006 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(-36.7539, -8.3906, 0)
	P013 = App.Vector(-35.9795, -8.5132, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(-27.3651, -6.3515, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(-27.1690, -6.1484, 0)
	P016 = App.Vector(-27.2649, -5.8829, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(-27.7770, -5.4796, 0)
	S010 = Part.LineSegment(P016, P017)
	P018 = App.Vector(-28.2157, -4.1521, 0)
	P019 = App.Vector(-27.1656, -3.2291, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(-17.8384, -1.9471, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-17.2037, -1.5934, 0)
	P022 = App.Vector(-16.9760, -0.9033, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-17.0000, -0.0000, 0)
	P024 = App.Vector(-16.9760, 0.9033, 0)
	S014 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(-17.2037, 1.5934, 0)
	P026 = App.Vector(-17.8384, 1.9471, 0)
	S015 = Part.Arc(P024, P025, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr38():
	P000 = App.Vector(-17.7022, -2.9378, 0)
	P001 = App.Vector(-27.0295, -4.2198, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-27.2507, -4.4143, 0)
	P003 = App.Vector(-27.1583, -4.6940, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-26.6462, -5.0973, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-26.1911, -6.3575, 0)
	P006 = App.Vector(-27.1217, -7.3214, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-35.7361, -9.4831, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-36.3609, -9.9568, 0)
	P009 = App.Vector(-36.4520, -10.7356, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-35.2546, -14.1816, 0)
	P011 = App.Vector(-33.7322, -17.4968, 0)
	S006 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(-33.1272, -17.9956, 0)
	P013 = App.Vector(-32.3485, -17.9047, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(-24.6367, -13.4990, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(-24.5027, -13.2505, 0)
	P016 = App.Vector(-24.6666, -13.0207, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(-25.2686, -12.7705, 0)
	S010 = Part.LineSegment(P016, P017)
	P018 = App.Vector(-26.0492, -11.6107, 0)
	P019 = App.Vector(-25.2871, -10.4386, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(-16.6516, -6.6877, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-16.1358, -6.1758, 0)
	P022 = App.Vector(-16.1028, -5.4499, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-16.3696, -4.5865, 0)
	P024 = App.Vector(-16.5902, -3.7103, 0)
	S014 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(-16.9956, -3.1072, 0)
	P026 = App.Vector(-17.7022, -2.9378, 0)
	S015 = Part.Arc(P024, P025, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr39():
	P000 = App.Vector(-16.2532, -7.6049, 0)
	P001 = App.Vector(-24.8887, -11.3558, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-25.0492, -11.6027, 0)
	P003 = App.Vector(-24.8848, -11.8471, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-24.2828, -12.0973, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-23.5046, -13.1880, 0)
	P006 = App.Vector(-24.1406, -14.3673, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-31.8524, -18.7730, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-32.3262, -19.3977, 0)
	P009 = App.Vector(-32.2038, -20.1721, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-30.1211, -23.1672, 0)
	P011 = App.Vector(-27.7607, -25.9488, 0)
	S006 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(-27.0436, -26.2659, 0)
	P013 = App.Vector(-26.3183, -25.9682, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(-20.0811, -19.6453, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(-20.0191, -19.3699, 0)
	P016 = App.Vector(-20.2390, -19.1929, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(-20.8861, -19.1143, 0)
	S010 = Part.LineSegment(P016, P017)
	P018 = App.Vector(-21.9507, -18.2081, 0)
	P019 = App.Vector(-21.5330, -16.8739, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(-14.2298, -10.9322, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-13.8712, -10.3002, 0)
	P022 = App.Vector(-14.0353, -9.5923, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-14.5251, -8.8329, 0)
	P024 = App.Vector(-14.9740, -8.0486, 0)
	S014 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(-15.5270, -7.5773, 0)
	P026 = App.Vector(-16.2532, -7.6049, 0)
	S015 = Part.Arc(P024, P025, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr40():
	P000 = App.Vector(-13.5987, -11.7079, 0)
	P001 = App.Vector(-20.9020, -17.6496, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-20.9900, -17.9307, 0)
	P003 = App.Vector(-20.7657, -18.1216, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-20.1185, -18.2001, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-19.0749, -19.0404, 0)
	P006 = App.Vector(-19.3692, -20.3476, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-25.6063, -26.6705, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-25.8941, -27.3999, 0)
	P009 = App.Vector(-25.5672, -28.1126, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-22.7537, -30.4347, 0)
	P011 = App.Vector(-19.7304, -32.4763, 0)
	S006 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(-18.9543, -32.5882, 0)
	P013 = App.Vector(-18.3362, -32.1058, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(-14.0362, -24.3346, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(-14.0508, -24.0527, 0)
	P016 = App.Vector(-14.3103, -23.9415, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(-14.9546, -24.0405, 0)
	S010 = Part.LineSegment(P016, P017)
	P018 = App.Vector(-16.2242, -23.4551, 0)
	P019 = App.Vector(-16.1820, -22.0577, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(-10.7526, -14.3660, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-10.5779, -13.6606, 0)
	P022 = App.Vector(-10.9268, -13.0232, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-11.6034, -12.4242, 0)
	P024 = App.Vector(-12.2472, -11.7901, 0)
	S014 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(-12.9069, -11.4855, 0)
	P026 = App.Vector(-13.5987, -11.7079, 0)
	S015 = Part.Arc(P024, P025, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr41():
	P000 = App.Vector(-9.9357, -14.9426, 0)
	P001 = App.Vector(-15.3651, -22.6344, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-15.3739, -22.9288, 0)
	P003 = App.Vector(-15.1064, -23.0521, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-14.4622, -22.9531, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-13.2306, -23.4807, 0)
	P006 = App.Vector(-13.1612, -24.8188, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-17.4612, -32.5900, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-17.5414, -33.3699, 0)
	P009 = App.Vector(-17.0345, -33.9680, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-13.6987, -35.4450, 0)
	P011 = App.Vector(-10.2367, -36.5952, 0)
	S006 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(-9.4593, -36.4935, 0)
	P013 = App.Vector(-8.9942, -35.8623, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(-6.9503, -27.2192, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(-7.0404, -26.9516, 0)
	P016 = App.Vector(-7.3203, -26.9146, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(-7.9140, -27.1837, 0)
	S010 = Part.LineSegment(P016, P017)
	P018 = App.Vector(-9.2945, -26.9626, 0)
	P019 = App.Vector(-9.6309, -25.6056, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(-6.4780, -16.7343, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-6.5001, -16.0079, 0)
	P022 = App.Vector(-7.0080, -15.4883, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-7.8211, -15.0940, 0)
	P024 = App.Vector(-8.6121, -14.6571, 0)
	S014 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(-9.3295, -14.5418, 0)
	P026 = App.Vector(-9.9357, -14.9426, 0)
	S015 = Part.Arc(P024, P025, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr42():
	P000 = App.Vector(-5.5357, -17.0691, 0)
	P001 = App.Vector(-8.6886, -25.9405, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-8.6177, -26.2264, 0)
	P003 = App.Vector(-8.3269, -26.2730, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-7.7332, -26.0038, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-6.4049, -26.1795, 0)
	P006 = App.Vector(-5.9771, -27.4493, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-8.0210, -36.0924, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-7.8879, -36.8651, 0)
	P009 = App.Vector(-7.2383, -37.3042, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-3.6278, -37.8264, 0)
	P011 = App.Vector(0.0162, -38.0000, 0)
	S006 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(0.7373, -37.6923, 0)
	P013 = App.Vector(1.0149, -36.9590, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(0.6511, -28.0850, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(0.4921, -27.8517, 0)
	P016 = App.Vector(0.2126, -27.8915, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(-0.2864, -28.3109, 0)
	S010 = Part.LineSegment(P016, P017)
	P018 = App.Vector(-1.6754, -28.4704, 0)
	P019 = App.Vector(-2.3654, -27.2544, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(-1.7229, -17.8615, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-1.9401, -17.1680, 0)
	P022 = App.Vector(-2.5694, -16.8047, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-3.4588, -16.6444, 0)
	P024 = App.Vector(-4.3383, -16.4371, 0)
	S014 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(-5.0602, -16.5196, 0)
	P026 = App.Vector(-5.5357, -17.0691, 0)
	S015 = Part.Arc(P024, P025, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr43():
	P000 = App.Vector(-0.7253, -17.9297, 0)
	P001 = App.Vector(-1.3678, -27.3227, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-1.2224, -27.5789, 0)
	P003 = App.Vector(-0.9297, -27.5453, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-0.4307, -27.1259, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(0.8958, -26.9368, 0)
	P006 = App.Vector(1.6502, -28.0440, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(2.0141, -36.9181, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(2.3507, -37.6262, 0)
	P009 = App.Vector(3.0947, -37.8738, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(6.7122, -37.4025, 0)
	P011 = App.Vector(10.2679, -36.5865, 0)
	S006 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(10.8793, -36.0956, 0)
	P013 = App.Vector(10.9487, -35.3147, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(8.2042, -26.8678, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(7.9882, -26.6861, 0)
	P016 = App.Vector(7.7298, -26.7999, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(7.3624, -27.3383, 0)
	S010 = Part.LineSegment(P016, P017)
	P018 = App.Vector(6.0680, -27.8666, 0)
	P019 = App.Vector(5.0755, -26.8819, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(3.1599, -17.6639, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(2.7637, -17.0548, 0)
	P022 = App.Vector(2.0597, -16.8748, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(1.1601, -16.9604, 0)
	P024 = App.Vector(0.2573, -16.9981, 0)
	S014 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(-0.4157, -17.2723, 0)
	P026 = App.Vector(-0.7253, -17.9297, 0)
	S015 = Part.Arc(P024, P025, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr44():
	P000 = App.Vector(4.1390, -17.4605, 0)
	P001 = App.Vector(6.0545, -26.6785, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(6.2636, -26.8860, 0)
	P003 = App.Vector(6.5364, -26.7746, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(6.9038, -26.2362, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(8.1300, -25.6962, 0)
	P006 = App.Vector(9.1552, -26.5588, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(11.8998, -35.0057, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(12.4150, -35.5967, 0)
	P009 = App.Vector(13.1981, -35.6344, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(16.5544, -34.2046, 0)
	P011 = App.Vector(19.7580, -32.4595, 0)
	S006 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(20.2143, -31.8219, 0)
	P013 = App.Vector(20.0705, -31.0512, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(15.1488, -23.6580, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(14.8918, -23.5413, 0)
	P016 = App.Vector(14.6737, -23.7206, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(14.4651, -24.3382, 0)
	S010 = Part.LineSegment(P016, P017)
	P018 = App.Vector(13.3613, -25.1961, 0)
	P019 = App.Vector(12.1399, -24.5158, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(7.8084, -16.1564, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(7.2625, -15.6767, 0)
	P022 = App.Vector(6.5361, -15.6933, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(5.6930, -16.0184, 0)
	P024 = App.Vector(4.8338, -16.2983, 0)
	S014 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(4.2598, -16.7439, 0)
	P026 = App.Vector(4.1390, -17.4605, 0)
	S015 = Part.Arc(P024, P025, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr45():
	P000 = App.Vector(8.6963, -15.6963, 0)
	P001 = App.Vector(13.0278, -24.0557, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(13.2851, -24.1990, 0)
	P003 = App.Vector(13.5177, -24.0183, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(13.7262, -23.4007, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(14.7613, -22.5499, 0)
	P006 = App.Vector(15.9812, -23.1039, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(20.9029, -30.4970, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(21.5585, -30.9271, 0)
	P009 = App.Vector(22.3228, -30.7522, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(25.1688, -28.4699, 0)
	P011 = App.Vector(27.7828, -25.9252, 0)
	S006 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(28.0502, -25.1881, 0)
	P013 = App.Vector(27.7037, -24.4848, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(20.9699, -18.6937, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(20.6909, -18.6506, 0)
	P016 = App.Vector(20.5293, -18.8820, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(20.4951, -19.5330, 0)
	S010 = Part.LineSegment(P016, P017)
	P018 = App.Vector(19.6636, -20.6570, 0)
	P019 = App.Vector(18.3040, -20.3313, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(11.8778, -13.4506, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(11.2228, -13.1360, 0)
	P022 = App.Vector(10.5277, -13.3479, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(9.8036, -13.8885, 0)
	P024 = App.Vector(9.0517, -14.3898, 0)
	S014 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(8.6193, -14.9737, 0)
	P026 = App.Vector(8.6963, -15.6963, 0)
	S015 = Part.Arc(P024, P025, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr46():
	P000 = App.Vector(12.6086, -12.7680, 0)
	P001 = App.Vector(19.0348, -19.6488, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(19.3213, -19.7174, 0)
	P003 = App.Vector(19.4965, -19.4806, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(19.5306, -18.8296, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(20.2978, -17.7311, 0)
	P006 = App.Vector(21.6219, -17.9355, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(28.3558, -23.7266, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(29.1031, -23.9639, 0)
	P009 = App.Vector(29.7918, -23.5892, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(31.9165, -20.6237, 0)
	P011 = App.Vector(33.7471, -17.4681, 0)
	S006 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(33.8057, -16.6862, 0)
	P013 = App.Vector(33.2823, -16.1024, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(25.2358, -12.3428, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(24.9555, -12.3766, 0)
	P016 = App.Vector(24.8623, -12.6431, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(25.0050, -13.2791, 0)
	S010 = Part.LineSegment(P016, P017)
	P018 = App.Vector(24.5076, -14.5858, 0)
	P019 = App.Vector(23.1106, -14.6390, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(15.0663, -9.7472, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(14.3506, -9.6210, 0)
	P022 = App.Vector(13.7385, -10.0126, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(13.1871, -10.7285, 0)
	P024 = App.Vector(12.5984, -11.4140, 0)
	S014 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(12.3395, -12.0930, 0)
	P026 = App.Vector(12.6086, -12.7680, 0)
	S015 = Part.Arc(P024, P025, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr47():
	P000 = App.Vector(15.5858, -8.8928, 0)
	P001 = App.Vector(23.6301, -13.7846, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(23.9245, -13.7734, 0)
	P003 = App.Vector(24.0293, -13.4981, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(23.8866, -12.8621, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(24.3289, -11.5973, 0)
	P006 = App.Vector(25.6591, -11.4368, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(33.7056, -15.1964, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(34.4892, -15.2233, 0)
	P009 = App.Vector(35.0513, -14.6767, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(36.2972, -11.2479, 0)
	P011 = App.Vector(37.2085, -7.7155, 0)
	S006 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(37.0540, -6.9468, 0)
	P013 = App.Vector(36.3925, -6.5259, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(27.6300, -5.0766, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(27.3693, -5.1848, 0)
	P016 = App.Vector(27.3514, -5.4665, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(27.6604, -6.0404, 0)
	S010 = Part.LineSegment(P016, P017)
	P018 = App.Vector(27.5340, -7.4328, 0)
	P019 = App.Vector(26.2031, -7.8610, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(17.1373, -5.3209, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(16.4142, -5.3925, 0)
	P022 = App.Vector(15.9304, -5.9347, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(15.5926, -6.7728, 0)
	P024 = App.Vector(15.2107, -7.5918, 0)
	S014 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(15.1446, -8.3154, 0)
	P026 = App.Vector(15.5858, -8.8928, 0)
	S015 = Part.Arc(P024, P025, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr48():
	P000 = App.Vector(17.4071, -4.3580, 0)
	P001 = App.Vector(26.4729, -6.8981, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(26.7533, -6.8079, 0)
	P003 = App.Vector(26.7800, -6.5145, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(26.4709, -5.9406, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(26.5556, -4.6034, 0)
	P006 = App.Vector(27.7932, -4.0900, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(36.5557, -5.5393, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(37.3175, -5.3537, 0)
	P009 = App.Vector(37.7112, -4.6757, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(37.9858, -1.0380, 0)
	P011 = App.Vector(37.9103, 2.6093, 0)
	S006 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(37.5541, 3.3078, 0)
	P013 = App.Vector(36.8036, 3.5347, 0)
	S007 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(27.9751, 2.5661, 0)
	S008 = Part.LineSegment(P013, P014)
	P015 = App.Vector(27.7532, 2.3916, 0)
	P016 = App.Vector(27.8120, 2.1155, 0)
	S009 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(28.2644, 1.6462, 0)
	S010 = Part.LineSegment(P016, P017)
	P018 = App.Vector(28.5183, 0.2714, 0)
	P019 = App.Vector(27.3523, -0.5000, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(17.9374, -0.5000, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(17.2604, -0.7640, 0)
	P022 = App.Vector(16.9409, -1.4167, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(16.8417, -2.3148, 0)
	P024 = App.Vector(16.6949, -3.2065, 0)
	S014 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(16.8265, -3.9211, 0)
	P026 = App.Vector(17.4071, -4.3580, 0)
	S015 = Part.Arc(P024, P025, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_springTorqueB_faceProfile_Fa0():
	FC000 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr0()
	FC001 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr1()
	FC002 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr2()
	FC003 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr3()
	FC004 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr4()
	FC005 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr5()
	FC006 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr6()
	FC007 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr7()
	FC008 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr8()
	FC009 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr9()
	FC010 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr10()
	FC011 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr11()
	FC012 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr12()
	FC013 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr13()
	FC014 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr14()
	FC015 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr15()
	FC016 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr16()
	FC017 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr17()
	FC018 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr18()
	FC019 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr19()
	FC020 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr20()
	FC021 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr21()
	FC022 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr22()
	FC023 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr23()
	FC024 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr24()
	FC025 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr25()
	FC026 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr26()
	FC027 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr27()
	FC028 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr28()
	FC029 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr29()
	FC030 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr30()
	FC031 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr31()
	FC032 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr32()
	FC033 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr33()
	FC034 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr34()
	FC035 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr35()
	FC036 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr36()
	FC037 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr37()
	FC038 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr38()
	FC039 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr39()
	FC040 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr40()
	FC041 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr41()
	FC042 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr42()
	FC043 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr43()
	FC044 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr44()
	FC045 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr45()
	FC046 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr46()
	FC047 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr47()
	FC048 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr48()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008, FC009, FC010, FC011, FC012, FC013, FC014, FC015, FC016, FC017, FC018, FC019, FC020, FC021, FC022, FC023, FC024, FC025, FC026, FC027, FC028, FC029, FC030, FC031, FC032, FC033, FC034, FC035, FC036, FC037, FC038, FC039, FC040, FC041, FC042, FC043, FC044, FC045, FC046, FC047, FC048])
	rOneFace.check()
	return rOneFace

def springTorqueB_faceProfile():
	FA000 = face_springTorqueB_faceProfile_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_springTorqueB_profile():
	FIG = springTorqueB_faceProfile()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_springTorqueB_profile = fex_subpax_springTorqueB_profile()

pax_springTorqueB = subpax_springTorqueB_profile

pax_springTorqueB.check()
#pax_springTorqueB.exportBrep(f"{outFileName}.brep")
#pax_springTorqueB.exportIges(f"{outFileName}.igs")
#pax_springTorqueB.exportStep(f"{outFileName}.stp")
pax_springTorqueB.exportStl(f"{outFileName}.stl")

