# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "springTorqueB"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(42.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr1():
	P000 = App.Vector(8.8273, -0.0000, 0)
	P001 = App.Vector(10.9717, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(11.7472, 0.3686, 0)
	P003 = App.Vector(11.9509, 1.2028, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(11.4457, 3.6424, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(10.9274, 4.3270, 0)
	P006 = App.Vector(10.0693, 4.3574, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(8.1013, 3.5057, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(7.4251, 3.4632, 0)
	P009 = App.Vector(6.8770, 3.8614, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(6.1219, 4.9726, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(5.9534, 5.6288, 0)
	P012 = App.Vector(6.2418, 6.2418, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(7.7582, 7.7582, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(8.0458, 8.5672, 0)
	P015 = App.Vector(7.6001, 9.3011, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(5.5177, 10.6689, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(4.6672, 10.7866, 0)
	P018 = App.Vector(4.0389, 10.2012, 0)
	S011 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(3.2495, 8.2074, 0)
	S012 = Part.LineSegment(P018, P019)
	P020 = App.Vector(2.8015, 7.6992, 0)
	P021 = App.Vector(2.1324, 7.5932, 0)
	S013 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(0.8126, 7.8450, 0)
	S014 = Part.LineSegment(P021, P022)
	P023 = App.Vector(0.2295, 8.1898, 0)
	P024 = App.Vector(0.0000, 8.8273, 0)
	S015 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(0.0000, 10.9717, 0)
	S016 = Part.LineSegment(P024, P025)
	P026 = App.Vector(-0.3686, 11.7472, 0)
	P027 = App.Vector(-1.2028, 11.9509, 0)
	S017 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(-3.6424, 11.4457, 0)
	S018 = Part.LineSegment(P027, P028)
	P029 = App.Vector(-4.3270, 10.9274, 0)
	P030 = App.Vector(-4.3574, 10.0693, 0)
	S019 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(-3.5057, 8.1013, 0)
	S020 = Part.LineSegment(P030, P031)
	P032 = App.Vector(-3.4632, 7.4251, 0)
	P033 = App.Vector(-3.8614, 6.8770, 0)
	S021 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(-4.9726, 6.1219, 0)
	S022 = Part.LineSegment(P033, P034)
	P035 = App.Vector(-5.6288, 5.9534, 0)
	P036 = App.Vector(-6.2418, 6.2418, 0)
	S023 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-7.7582, 7.7582, 0)
	S024 = Part.LineSegment(P036, P037)
	P038 = App.Vector(-8.5672, 8.0458, 0)
	P039 = App.Vector(-9.3011, 7.6001, 0)
	S025 = Part.Arc(P037, P038, P039)
	P040 = App.Vector(-10.6689, 5.5177, 0)
	S026 = Part.LineSegment(P039, P040)
	P041 = App.Vector(-10.7866, 4.6672, 0)
	P042 = App.Vector(-10.2012, 4.0389, 0)
	S027 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(-8.2074, 3.2495, 0)
	S028 = Part.LineSegment(P042, P043)
	P044 = App.Vector(-7.6992, 2.8015, 0)
	P045 = App.Vector(-7.5932, 2.1324, 0)
	S029 = Part.Arc(P043, P044, P045)
	P046 = App.Vector(-7.8450, 0.8126, 0)
	S030 = Part.LineSegment(P045, P046)
	P047 = App.Vector(-8.1898, 0.2295, 0)
	P048 = App.Vector(-8.8273, 0.0000, 0)
	S031 = Part.Arc(P046, P047, P048)
	P049 = App.Vector(-10.9717, 0.0000, 0)
	S032 = Part.LineSegment(P048, P049)
	P050 = App.Vector(-11.7472, -0.3686, 0)
	P051 = App.Vector(-11.9509, -1.2028, 0)
	S033 = Part.Arc(P049, P050, P051)
	P052 = App.Vector(-11.4457, -3.6424, 0)
	S034 = Part.LineSegment(P051, P052)
	P053 = App.Vector(-10.9274, -4.3270, 0)
	P054 = App.Vector(-10.0693, -4.3574, 0)
	S035 = Part.Arc(P052, P053, P054)
	P055 = App.Vector(-8.1013, -3.5057, 0)
	S036 = Part.LineSegment(P054, P055)
	P056 = App.Vector(-7.4251, -3.4632, 0)
	P057 = App.Vector(-6.8770, -3.8614, 0)
	S037 = Part.Arc(P055, P056, P057)
	P058 = App.Vector(-6.1219, -4.9726, 0)
	S038 = Part.LineSegment(P057, P058)
	P059 = App.Vector(-5.9534, -5.6288, 0)
	P060 = App.Vector(-6.2418, -6.2418, 0)
	S039 = Part.Arc(P058, P059, P060)
	P061 = App.Vector(-7.7582, -7.7582, 0)
	S040 = Part.LineSegment(P060, P061)
	P062 = App.Vector(-8.0458, -8.5672, 0)
	P063 = App.Vector(-7.6001, -9.3011, 0)
	S041 = Part.Arc(P061, P062, P063)
	P064 = App.Vector(-5.5177, -10.6689, 0)
	S042 = Part.LineSegment(P063, P064)
	P065 = App.Vector(-4.6672, -10.7866, 0)
	P066 = App.Vector(-4.0389, -10.2012, 0)
	S043 = Part.Arc(P064, P065, P066)
	P067 = App.Vector(-3.2495, -8.2074, 0)
	S044 = Part.LineSegment(P066, P067)
	P068 = App.Vector(-2.8015, -7.6992, 0)
	P069 = App.Vector(-2.1324, -7.5932, 0)
	S045 = Part.Arc(P067, P068, P069)
	P070 = App.Vector(-0.8126, -7.8450, 0)
	S046 = Part.LineSegment(P069, P070)
	P071 = App.Vector(-0.2295, -8.1898, 0)
	P072 = App.Vector(-0.0000, -8.8273, 0)
	S047 = Part.Arc(P070, P071, P072)
	P073 = App.Vector(-0.0000, -10.9717, 0)
	S048 = Part.LineSegment(P072, P073)
	P074 = App.Vector(0.3686, -11.7472, 0)
	P075 = App.Vector(1.2028, -11.9509, 0)
	S049 = Part.Arc(P073, P074, P075)
	P076 = App.Vector(3.6424, -11.4457, 0)
	S050 = Part.LineSegment(P075, P076)
	P077 = App.Vector(4.3270, -10.9274, 0)
	P078 = App.Vector(4.3574, -10.0693, 0)
	S051 = Part.Arc(P076, P077, P078)
	P079 = App.Vector(3.5057, -8.1013, 0)
	S052 = Part.LineSegment(P078, P079)
	P080 = App.Vector(3.4632, -7.4251, 0)
	P081 = App.Vector(3.8614, -6.8770, 0)
	S053 = Part.Arc(P079, P080, P081)
	P082 = App.Vector(4.9726, -6.1219, 0)
	S054 = Part.LineSegment(P081, P082)
	P083 = App.Vector(5.6288, -5.9534, 0)
	P084 = App.Vector(6.2418, -6.2418, 0)
	S055 = Part.Arc(P082, P083, P084)
	P085 = App.Vector(7.7582, -7.7582, 0)
	S056 = Part.LineSegment(P084, P085)
	P086 = App.Vector(8.5672, -8.0458, 0)
	P087 = App.Vector(9.3011, -7.6001, 0)
	S057 = Part.Arc(P085, P086, P087)
	P088 = App.Vector(10.6689, -5.5177, 0)
	S058 = Part.LineSegment(P087, P088)
	P089 = App.Vector(10.7866, -4.6672, 0)
	P090 = App.Vector(10.2012, -4.0389, 0)
	S059 = Part.Arc(P088, P089, P090)
	P091 = App.Vector(8.2074, -3.2495, 0)
	S060 = Part.LineSegment(P090, P091)
	P092 = App.Vector(7.6992, -2.8015, 0)
	P093 = App.Vector(7.5932, -2.1324, 0)
	S061 = Part.Arc(P091, P092, P093)
	P094 = App.Vector(7.8450, -0.8126, 0)
	S062 = Part.LineSegment(P093, P094)
	P095 = App.Vector(8.1898, -0.2295, 0)
	P096 = App.Vector(8.8273, -0.0000, 0)
	S063 = Part.Arc(P094, P095, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047, S048, S049, S050, S051, S052, S053, S054, S055, S056, S057, S058, S059, S060, S061, S062, S063])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(15.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(10.6066, 10.6066, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(0.0000, 15.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-10.6066, 10.6066, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-15.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-10.6066, -10.6066, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-0.0000, -15.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr9():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(10.6066, -10.6066, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr10():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(40.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr11():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(36.9552, 15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr12():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(28.2843, 28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr13():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(15.3073, 36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr14():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(0.0000, 40.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr15():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-15.3073, 36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr16():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-28.2843, 28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr17():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-36.9552, 15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr18():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-40.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr19():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-36.9552, -15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr20():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-28.2843, -28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr21():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-15.3073, -36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr22():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-0.0000, -40.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr23():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(15.3073, -36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr24():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(28.2843, -28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr25():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(36.9552, -15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr26():
	P000 = App.Vector(17.9374, 0.5000, 0)
	P001 = App.Vector(33.3921, 0.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(35.3124, 2.4203, 0)
	P003 = App.Vector(33.3921, 4.3406, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(20.2584, 4.3406, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(17.3381, 7.2609, 0)
	P006 = App.Vector(20.2584, 10.1812, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(31.2161, 10.1812, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(33.1364, 12.1015, 0)
	P009 = App.Vector(31.2161, 14.0219, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(15.3009, 14.0219, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(12.3806, 16.9422, 0)
	P012 = App.Vector(15.3009, 19.8625, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(25.4244, 19.8625, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(27.3447, 21.7828, 0)
	P015 = App.Vector(25.4244, 23.7031, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(22.3347, 23.7031, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(19.7327, 25.2976, 0)
	P018 = App.Vector(19.9721, 28.3399, 0)
	S011 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(21.3257, 30.2029, 0)
	S012 = Part.LineSegment(P018, P019)
	P020 = App.Vector(21.5010, 30.9671, 0)
	P021 = App.Vector(21.0712, 31.6229, 0)
	S013 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(3.9721, 37.7918, 0)
	P023 = App.Vector(-14.0359, 35.3128, 0)
	S014 = Part.Arc(P021, P022, P023)
	P024 = App.Vector(-14.5927, 34.7607, 0)
	P025 = App.Vector(-14.5801, 33.9768, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(-13.6435, 31.8731, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(-11.9897, 30.7364, 0)
	P028 = App.Vector(-10.2262, 31.6940, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-8.6813, 34.3697, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(-4.6921, 35.4386, 0)
	P031 = App.Vector(-3.6232, 31.4494, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(-8.6849, 22.6822, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(-7.9821, 20.0590, 0)
	P034 = App.Vector(-5.3589, 20.7619, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(2.5987, 34.5448, 0)
	S022 = Part.LineSegment(P034, P035)
	P036 = App.Vector(6.5879, 35.6137, 0)
	P037 = App.Vector(7.6568, 31.6245, 0)
	S023 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(2.1780, 22.1349, 0)
	S024 = Part.LineSegment(P037, P038)
	P039 = App.Vector(2.8809, 19.5117, 0)
	P040 = App.Vector(5.5041, 20.2146, 0)
	S025 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(12.0709, 31.5887, 0)
	S026 = Part.LineSegment(P040, P041)
	P042 = App.Vector(16.0602, 32.6576, 0)
	P043 = App.Vector(17.1291, 28.6684, 0)
	S027 = Part.Arc(P041, P042, P043)
	P044 = App.Vector(9.4017, 15.2842, 0)
	S028 = Part.LineSegment(P043, P044)
	P045 = App.Vector(9.2919, 14.5659, 0)
	P046 = App.Vector(9.6973, 13.9629, 0)
	S029 = Part.Arc(P044, P045, P046)
	P047 = App.Vector(14.7224, 8.5000, 0)
	P048 = App.Vector(16.9409, 1.4167, 0)
	S030 = Part.Arc(P046, P047, P048)
	P049 = App.Vector(17.2604, 0.7640, 0)
	P050 = App.Vector(17.9374, 0.5000, 0)
	S031 = Part.Arc(P048, P049, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr27():
	P000 = App.Vector(8.5357, 15.7842, 0)
	P001 = App.Vector(16.2630, 29.1684, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(15.5602, 31.7916, 0)
	P003 = App.Vector(12.9370, 31.0887, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(6.3701, 19.7146, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(2.3809, 18.6457, 0)
	P006 = App.Vector(1.3120, 22.6349, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(6.7908, 32.1245, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(6.0879, 34.7477, 0)
	P009 = App.Vector(3.4647, 34.0448, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-4.4928, 20.2619, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-8.4821, 19.1930, 0)
	P012 = App.Vector(-9.5510, 23.1822, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(-4.4892, 31.9494, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(-5.1921, 34.5726, 0)
	P015 = App.Vector(-7.8153, 33.8697, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(-9.3601, 31.1940, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(-12.0420, 29.7378, 0)
	P018 = App.Vector(-14.5570, 31.4663, 0)
	S011 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(-15.4937, 33.5700, 0)
	S012 = Part.LineSegment(P018, P019)
	P020 = App.Vector(-16.0678, 34.1039, 0)
	P021 = App.Vector(-16.8506, 34.0596, 0)
	S013 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(-30.7426, 22.3358, 0)
	P023 = App.Vector(-37.5997, 5.5009, 0)
	S014 = Part.Arc(P021, P022, P023)
	P024 = App.Vector(-37.4000, 4.7427, 0)
	P025 = App.Vector(-36.7148, 4.3616, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(-34.4246, 4.1209, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(-32.6134, 4.9848, 0)
	P028 = App.Vector(-32.5609, 6.9909, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-34.1057, 9.6666, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(-33.0368, 13.6558, 0)
	P031 = App.Vector(-29.0476, 12.5869, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(-23.9858, 3.8197, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(-21.3626, 3.1168, 0)
	P034 = App.Vector(-20.6597, 5.7400, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(-28.6173, 19.5230, 0)
	S022 = Part.LineSegment(P034, P035)
	P036 = App.Vector(-27.5484, 23.5122, 0)
	P037 = App.Vector(-23.5592, 22.4433, 0)
	S023 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(-18.0804, 12.9537, 0)
	S024 = Part.LineSegment(P037, P038)
	P039 = App.Vector(-15.4572, 12.2508, 0)
	P040 = App.Vector(-14.7543, 14.8740, 0)
	S025 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(-21.3212, 26.2481, 0)
	S026 = Part.LineSegment(P040, P041)
	P042 = App.Vector(-20.2522, 30.2373, 0)
	P043 = App.Vector(-16.2630, 29.1684, 0)
	S027 = Part.Arc(P041, P042, P043)
	P044 = App.Vector(-8.5357, 15.7842, 0)
	S028 = Part.LineSegment(P043, P044)
	P045 = App.Vector(-7.9685, 15.3299, 0)
	P046 = App.Vector(-7.2436, 15.3796, 0)
	S029 = Part.Arc(P044, P045, P046)
	P047 = App.Vector(-0.0000, 17.0000, 0)
	P048 = App.Vector(7.2436, 15.3796, 0)
	S030 = Part.Arc(P046, P047, P048)
	P049 = App.Vector(7.9685, 15.3299, 0)
	P050 = App.Vector(8.5357, 15.7842, 0)
	S031 = Part.Arc(P048, P049, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr28():
	P000 = App.Vector(-9.4017, 15.2842, 0)
	P001 = App.Vector(-17.1291, 28.6684, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-19.7522, 29.3713, 0)
	P003 = App.Vector(-20.4551, 26.7481, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-13.8883, 15.3740, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-14.9572, 11.3848, 0)
	P006 = App.Vector(-18.9464, 12.4537, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-24.4252, 21.9433, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-27.0484, 22.6462, 0)
	P009 = App.Vector(-27.7513, 20.0230, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-19.7937, 6.2400, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-20.8626, 2.2508, 0)
	P012 = App.Vector(-24.8518, 3.3197, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(-29.9136, 12.0869, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(-32.5368, 12.7898, 0)
	P015 = App.Vector(-33.2397, 10.1666, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(-31.6948, 7.4909, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(-31.7747, 4.4402, 0)
	P018 = App.Vector(-34.5291, 3.1264, 0)
	S011 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(-36.8193, 3.3671, 0)
	S012 = Part.LineSegment(P018, P019)
	P020 = App.Vector(-37.5688, 3.1368, 0)
	P021 = App.Vector(-37.9218, 2.4367, 0)
	S013 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(-34.7147, -15.4560, 0)
	P023 = App.Vector(-23.5638, -29.8119, 0)
	S014 = Part.Arc(P021, P022, P023)
	P024 = App.Vector(-22.8073, -30.0180, 0)
	P025 = App.Vector(-22.1347, -29.6151, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(-20.7811, -27.7521, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(-20.6237, -25.7516, 0)
	P028 = App.Vector(-22.3347, -24.7031, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-25.4244, -24.7031, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(-28.3447, -21.7828, 0)
	P031 = App.Vector(-25.4244, -18.8625, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(-15.3009, -18.8625, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(-13.3806, -16.9422, 0)
	P034 = App.Vector(-15.3009, -15.0219, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(-31.2161, -15.0219, 0)
	S022 = Part.LineSegment(P034, P035)
	P036 = App.Vector(-34.1364, -12.1015, 0)
	P037 = App.Vector(-31.2161, -9.1812, 0)
	S023 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(-20.2584, -9.1812, 0)
	S024 = Part.LineSegment(P037, P038)
	P039 = App.Vector(-18.3381, -7.2609, 0)
	P040 = App.Vector(-20.2584, -5.3406, 0)
	S025 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(-33.3921, -5.3406, 0)
	S026 = Part.LineSegment(P040, P041)
	P042 = App.Vector(-36.3124, -2.4203, 0)
	P043 = App.Vector(-33.3921, 0.5000, 0)
	S027 = Part.Arc(P041, P042, P043)
	P044 = App.Vector(-17.9374, 0.5000, 0)
	S028 = Part.LineSegment(P043, P044)
	P045 = App.Vector(-17.2604, 0.7640, 0)
	P046 = App.Vector(-16.9409, 1.4167, 0)
	S029 = Part.Arc(P044, P045, P046)
	P047 = App.Vector(-14.7224, 8.5000, 0)
	P048 = App.Vector(-9.6973, 13.9629, 0)
	S030 = Part.Arc(P046, P047, P048)
	P049 = App.Vector(-9.2919, 14.5659, 0)
	P050 = App.Vector(-9.4017, 15.2842, 0)
	S031 = Part.Arc(P048, P049, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr29():
	P000 = App.Vector(-17.9374, -0.5000, 0)
	P001 = App.Vector(-33.3921, -0.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-35.3124, -2.4203, 0)
	P003 = App.Vector(-33.3921, -4.3406, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-20.2584, -4.3406, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-17.3381, -7.2609, 0)
	P006 = App.Vector(-20.2584, -10.1812, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-31.2161, -10.1812, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-33.1364, -12.1015, 0)
	P009 = App.Vector(-31.2161, -14.0219, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-15.3009, -14.0219, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-12.3806, -16.9422, 0)
	P012 = App.Vector(-15.3009, -19.8625, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(-25.4244, -19.8625, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(-27.3447, -21.7828, 0)
	P015 = App.Vector(-25.4244, -23.7031, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(-22.3347, -23.7031, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(-19.7327, -25.2976, 0)
	P018 = App.Vector(-19.9721, -28.3399, 0)
	S011 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(-21.3257, -30.2029, 0)
	S012 = Part.LineSegment(P018, P019)
	P020 = App.Vector(-21.5010, -30.9671, 0)
	P021 = App.Vector(-21.0712, -31.6229, 0)
	S013 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(-3.9721, -37.7918, 0)
	P023 = App.Vector(14.0359, -35.3128, 0)
	S014 = Part.Arc(P021, P022, P023)
	P024 = App.Vector(14.5927, -34.7607, 0)
	P025 = App.Vector(14.5801, -33.9768, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(13.6435, -31.8731, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(11.9897, -30.7364, 0)
	P028 = App.Vector(10.2262, -31.6940, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(8.6813, -34.3697, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(4.6921, -35.4386, 0)
	P031 = App.Vector(3.6232, -31.4494, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(8.6849, -22.6822, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(7.9821, -20.0590, 0)
	P034 = App.Vector(5.3589, -20.7619, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(-2.5987, -34.5448, 0)
	S022 = Part.LineSegment(P034, P035)
	P036 = App.Vector(-6.5879, -35.6137, 0)
	P037 = App.Vector(-7.6568, -31.6245, 0)
	S023 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(-2.1780, -22.1349, 0)
	S024 = Part.LineSegment(P037, P038)
	P039 = App.Vector(-2.8809, -19.5117, 0)
	P040 = App.Vector(-5.5041, -20.2146, 0)
	S025 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(-12.0709, -31.5887, 0)
	S026 = Part.LineSegment(P040, P041)
	P042 = App.Vector(-16.0602, -32.6576, 0)
	P043 = App.Vector(-17.1291, -28.6684, 0)
	S027 = Part.Arc(P041, P042, P043)
	P044 = App.Vector(-9.4017, -15.2842, 0)
	S028 = Part.LineSegment(P043, P044)
	P045 = App.Vector(-9.2919, -14.5659, 0)
	P046 = App.Vector(-9.6973, -13.9629, 0)
	S029 = Part.Arc(P044, P045, P046)
	P047 = App.Vector(-14.7224, -8.5000, 0)
	P048 = App.Vector(-16.9409, -1.4167, 0)
	S030 = Part.Arc(P046, P047, P048)
	P049 = App.Vector(-17.2604, -0.7640, 0)
	P050 = App.Vector(-17.9374, -0.5000, 0)
	S031 = Part.Arc(P048, P049, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr30():
	P000 = App.Vector(-8.5357, -15.7842, 0)
	P001 = App.Vector(-16.2630, -29.1684, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-15.5602, -31.7916, 0)
	P003 = App.Vector(-12.9370, -31.0887, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-6.3701, -19.7146, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-2.3809, -18.6457, 0)
	P006 = App.Vector(-1.3120, -22.6349, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-6.7908, -32.1245, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-6.0879, -34.7477, 0)
	P009 = App.Vector(-3.4647, -34.0448, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(4.4928, -20.2619, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(8.4821, -19.1930, 0)
	P012 = App.Vector(9.5510, -23.1822, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(4.4892, -31.9494, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(5.1921, -34.5726, 0)
	P015 = App.Vector(7.8153, -33.8697, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(9.3601, -31.1940, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(12.0420, -29.7378, 0)
	P018 = App.Vector(14.5570, -31.4663, 0)
	S011 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(15.4937, -33.5700, 0)
	S012 = Part.LineSegment(P018, P019)
	P020 = App.Vector(16.0678, -34.1039, 0)
	P021 = App.Vector(16.8506, -34.0596, 0)
	S013 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(30.7426, -22.3358, 0)
	P023 = App.Vector(37.5997, -5.5009, 0)
	S014 = Part.Arc(P021, P022, P023)
	P024 = App.Vector(37.4000, -4.7427, 0)
	P025 = App.Vector(36.7148, -4.3616, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(34.4246, -4.1209, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(32.6134, -4.9848, 0)
	P028 = App.Vector(32.5609, -6.9909, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(34.1057, -9.6666, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(33.0368, -13.6558, 0)
	P031 = App.Vector(29.0476, -12.5869, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(23.9858, -3.8197, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(21.3626, -3.1168, 0)
	P034 = App.Vector(20.6597, -5.7400, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(28.6173, -19.5230, 0)
	S022 = Part.LineSegment(P034, P035)
	P036 = App.Vector(27.5484, -23.5122, 0)
	P037 = App.Vector(23.5592, -22.4433, 0)
	S023 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(18.0804, -12.9537, 0)
	S024 = Part.LineSegment(P037, P038)
	P039 = App.Vector(15.4572, -12.2508, 0)
	P040 = App.Vector(14.7543, -14.8740, 0)
	S025 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(21.3212, -26.2481, 0)
	S026 = Part.LineSegment(P040, P041)
	P042 = App.Vector(20.2522, -30.2373, 0)
	P043 = App.Vector(16.2630, -29.1684, 0)
	S027 = Part.Arc(P041, P042, P043)
	P044 = App.Vector(8.5357, -15.7842, 0)
	S028 = Part.LineSegment(P043, P044)
	P045 = App.Vector(7.9685, -15.3299, 0)
	P046 = App.Vector(7.2436, -15.3796, 0)
	S029 = Part.Arc(P044, P045, P046)
	P047 = App.Vector(-0.0000, -17.0000, 0)
	P048 = App.Vector(-7.2436, -15.3796, 0)
	S030 = Part.Arc(P046, P047, P048)
	P049 = App.Vector(-7.9685, -15.3299, 0)
	P050 = App.Vector(-8.5357, -15.7842, 0)
	S031 = Part.Arc(P048, P049, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr31():
	P000 = App.Vector(9.4017, -15.2842, 0)
	P001 = App.Vector(17.1291, -28.6684, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(19.7522, -29.3713, 0)
	P003 = App.Vector(20.4551, -26.7481, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(13.8883, -15.3740, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(14.9572, -11.3848, 0)
	P006 = App.Vector(18.9464, -12.4537, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(24.4252, -21.9433, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(27.0484, -22.6462, 0)
	P009 = App.Vector(27.7513, -20.0230, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(19.7937, -6.2400, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(20.8626, -2.2508, 0)
	P012 = App.Vector(24.8518, -3.3197, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(29.9136, -12.0869, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(32.5368, -12.7898, 0)
	P015 = App.Vector(33.2397, -10.1666, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(31.6948, -7.4909, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(31.7747, -4.4402, 0)
	P018 = App.Vector(34.5291, -3.1264, 0)
	S011 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(36.8193, -3.3671, 0)
	S012 = Part.LineSegment(P018, P019)
	P020 = App.Vector(37.5688, -3.1368, 0)
	P021 = App.Vector(37.9218, -2.4367, 0)
	S013 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(34.7147, 15.4560, 0)
	P023 = App.Vector(23.5638, 29.8119, 0)
	S014 = Part.Arc(P021, P022, P023)
	P024 = App.Vector(22.8073, 30.0180, 0)
	P025 = App.Vector(22.1347, 29.6151, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(20.7811, 27.7521, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(20.6237, 25.7516, 0)
	P028 = App.Vector(22.3347, 24.7031, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(25.4244, 24.7031, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(28.3447, 21.7828, 0)
	P031 = App.Vector(25.4244, 18.8625, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(15.3009, 18.8625, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(13.3806, 16.9422, 0)
	P034 = App.Vector(15.3009, 15.0219, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(31.2161, 15.0219, 0)
	S022 = Part.LineSegment(P034, P035)
	P036 = App.Vector(34.1364, 12.1015, 0)
	P037 = App.Vector(31.2161, 9.1812, 0)
	S023 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(20.2584, 9.1812, 0)
	S024 = Part.LineSegment(P037, P038)
	P039 = App.Vector(18.3381, 7.2609, 0)
	P040 = App.Vector(20.2584, 5.3406, 0)
	S025 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(33.3921, 5.3406, 0)
	S026 = Part.LineSegment(P040, P041)
	P042 = App.Vector(36.3124, 2.4203, 0)
	P043 = App.Vector(33.3921, -0.5000, 0)
	S027 = Part.Arc(P041, P042, P043)
	P044 = App.Vector(17.9374, -0.5000, 0)
	S028 = Part.LineSegment(P043, P044)
	P045 = App.Vector(17.2604, -0.7640, 0)
	P046 = App.Vector(16.9409, -1.4167, 0)
	S029 = Part.Arc(P044, P045, P046)
	P047 = App.Vector(14.7224, -8.5000, 0)
	P048 = App.Vector(9.6973, -13.9629, 0)
	S030 = Part.Arc(P046, P047, P048)
	P049 = App.Vector(9.2919, -14.5659, 0)
	P050 = App.Vector(9.4017, -15.2842, 0)
	S031 = Part.Arc(P048, P049, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_springTorqueB_faceProfile_Fa0():
	FC000 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr0()
	FC001 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr1()
	FC002 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr2()
	FC003 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr3()
	FC004 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr4()
	FC005 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr5()
	FC006 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr6()
	FC007 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr7()
	FC008 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr8()
	FC009 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr9()
	FC010 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr10()
	FC011 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr11()
	FC012 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr12()
	FC013 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr13()
	FC014 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr14()
	FC015 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr15()
	FC016 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr16()
	FC017 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr17()
	FC018 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr18()
	FC019 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr19()
	FC020 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr20()
	FC021 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr21()
	FC022 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr22()
	FC023 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr23()
	FC024 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr24()
	FC025 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr25()
	FC026 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr26()
	FC027 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr27()
	FC028 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr28()
	FC029 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr29()
	FC030 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr30()
	FC031 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr31()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008, FC009, FC010, FC011, FC012, FC013, FC014, FC015, FC016, FC017, FC018, FC019, FC020, FC021, FC022, FC023, FC024, FC025, FC026, FC027, FC028, FC029, FC030, FC031])
	rOneFace.check()
	return rOneFace

def springTorqueB_faceProfile():
	FA000 = face_springTorqueB_faceProfile_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_springTorqueB_profile():
	FIG = springTorqueB_faceProfile()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_springTorqueB_profile = fex_subpax_springTorqueB_profile()

pax_springTorqueB = subpax_springTorqueB_profile

pax_springTorqueB.check()
#pax_springTorqueB.exportBrep(f"{outFileName}.brep")
#pax_springTorqueB.exportIges(f"{outFileName}.igs")
#pax_springTorqueB.exportStep(f"{outFileName}.stp")
pax_springTorqueB.exportStl(f"{outFileName}.stl")

