# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "springTorqueB"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(42.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr1():
	P000 = App.Vector(8.8273, -0.0000, 0)
	P001 = App.Vector(10.9717, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(11.7472, 0.3686, 0)
	P003 = App.Vector(11.9509, 1.2028, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(11.4457, 3.6424, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(10.9274, 4.3270, 0)
	P006 = App.Vector(10.0693, 4.3574, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(8.1013, 3.5057, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(7.4251, 3.4632, 0)
	P009 = App.Vector(6.8770, 3.8614, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(6.1219, 4.9726, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(5.9534, 5.6288, 0)
	P012 = App.Vector(6.2418, 6.2418, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(7.7582, 7.7582, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(8.0458, 8.5672, 0)
	P015 = App.Vector(7.6001, 9.3011, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(5.5177, 10.6689, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(4.6672, 10.7866, 0)
	P018 = App.Vector(4.0389, 10.2012, 0)
	S011 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(3.2495, 8.2074, 0)
	S012 = Part.LineSegment(P018, P019)
	P020 = App.Vector(2.8015, 7.6992, 0)
	P021 = App.Vector(2.1324, 7.5932, 0)
	S013 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(0.8126, 7.8450, 0)
	S014 = Part.LineSegment(P021, P022)
	P023 = App.Vector(0.2295, 8.1898, 0)
	P024 = App.Vector(0.0000, 8.8273, 0)
	S015 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(0.0000, 10.9717, 0)
	S016 = Part.LineSegment(P024, P025)
	P026 = App.Vector(-0.3686, 11.7472, 0)
	P027 = App.Vector(-1.2028, 11.9509, 0)
	S017 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(-3.6424, 11.4457, 0)
	S018 = Part.LineSegment(P027, P028)
	P029 = App.Vector(-4.3270, 10.9274, 0)
	P030 = App.Vector(-4.3574, 10.0693, 0)
	S019 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(-3.5057, 8.1013, 0)
	S020 = Part.LineSegment(P030, P031)
	P032 = App.Vector(-3.4632, 7.4251, 0)
	P033 = App.Vector(-3.8614, 6.8770, 0)
	S021 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(-4.9726, 6.1219, 0)
	S022 = Part.LineSegment(P033, P034)
	P035 = App.Vector(-5.6288, 5.9534, 0)
	P036 = App.Vector(-6.2418, 6.2418, 0)
	S023 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-7.7582, 7.7582, 0)
	S024 = Part.LineSegment(P036, P037)
	P038 = App.Vector(-8.5672, 8.0458, 0)
	P039 = App.Vector(-9.3011, 7.6001, 0)
	S025 = Part.Arc(P037, P038, P039)
	P040 = App.Vector(-10.6689, 5.5177, 0)
	S026 = Part.LineSegment(P039, P040)
	P041 = App.Vector(-10.7866, 4.6672, 0)
	P042 = App.Vector(-10.2012, 4.0389, 0)
	S027 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(-8.2074, 3.2495, 0)
	S028 = Part.LineSegment(P042, P043)
	P044 = App.Vector(-7.6992, 2.8015, 0)
	P045 = App.Vector(-7.5932, 2.1324, 0)
	S029 = Part.Arc(P043, P044, P045)
	P046 = App.Vector(-7.8450, 0.8126, 0)
	S030 = Part.LineSegment(P045, P046)
	P047 = App.Vector(-8.1898, 0.2295, 0)
	P048 = App.Vector(-8.8273, 0.0000, 0)
	S031 = Part.Arc(P046, P047, P048)
	P049 = App.Vector(-10.9717, 0.0000, 0)
	S032 = Part.LineSegment(P048, P049)
	P050 = App.Vector(-11.7472, -0.3686, 0)
	P051 = App.Vector(-11.9509, -1.2028, 0)
	S033 = Part.Arc(P049, P050, P051)
	P052 = App.Vector(-11.4457, -3.6424, 0)
	S034 = Part.LineSegment(P051, P052)
	P053 = App.Vector(-10.9274, -4.3270, 0)
	P054 = App.Vector(-10.0693, -4.3574, 0)
	S035 = Part.Arc(P052, P053, P054)
	P055 = App.Vector(-8.1013, -3.5057, 0)
	S036 = Part.LineSegment(P054, P055)
	P056 = App.Vector(-7.4251, -3.4632, 0)
	P057 = App.Vector(-6.8770, -3.8614, 0)
	S037 = Part.Arc(P055, P056, P057)
	P058 = App.Vector(-6.1219, -4.9726, 0)
	S038 = Part.LineSegment(P057, P058)
	P059 = App.Vector(-5.9534, -5.6288, 0)
	P060 = App.Vector(-6.2418, -6.2418, 0)
	S039 = Part.Arc(P058, P059, P060)
	P061 = App.Vector(-7.7582, -7.7582, 0)
	S040 = Part.LineSegment(P060, P061)
	P062 = App.Vector(-8.0458, -8.5672, 0)
	P063 = App.Vector(-7.6001, -9.3011, 0)
	S041 = Part.Arc(P061, P062, P063)
	P064 = App.Vector(-5.5177, -10.6689, 0)
	S042 = Part.LineSegment(P063, P064)
	P065 = App.Vector(-4.6672, -10.7866, 0)
	P066 = App.Vector(-4.0389, -10.2012, 0)
	S043 = Part.Arc(P064, P065, P066)
	P067 = App.Vector(-3.2495, -8.2074, 0)
	S044 = Part.LineSegment(P066, P067)
	P068 = App.Vector(-2.8015, -7.6992, 0)
	P069 = App.Vector(-2.1324, -7.5932, 0)
	S045 = Part.Arc(P067, P068, P069)
	P070 = App.Vector(-0.8126, -7.8450, 0)
	S046 = Part.LineSegment(P069, P070)
	P071 = App.Vector(-0.2295, -8.1898, 0)
	P072 = App.Vector(-0.0000, -8.8273, 0)
	S047 = Part.Arc(P070, P071, P072)
	P073 = App.Vector(-0.0000, -10.9717, 0)
	S048 = Part.LineSegment(P072, P073)
	P074 = App.Vector(0.3686, -11.7472, 0)
	P075 = App.Vector(1.2028, -11.9509, 0)
	S049 = Part.Arc(P073, P074, P075)
	P076 = App.Vector(3.6424, -11.4457, 0)
	S050 = Part.LineSegment(P075, P076)
	P077 = App.Vector(4.3270, -10.9274, 0)
	P078 = App.Vector(4.3574, -10.0693, 0)
	S051 = Part.Arc(P076, P077, P078)
	P079 = App.Vector(3.5057, -8.1013, 0)
	S052 = Part.LineSegment(P078, P079)
	P080 = App.Vector(3.4632, -7.4251, 0)
	P081 = App.Vector(3.8614, -6.8770, 0)
	S053 = Part.Arc(P079, P080, P081)
	P082 = App.Vector(4.9726, -6.1219, 0)
	S054 = Part.LineSegment(P081, P082)
	P083 = App.Vector(5.6288, -5.9534, 0)
	P084 = App.Vector(6.2418, -6.2418, 0)
	S055 = Part.Arc(P082, P083, P084)
	P085 = App.Vector(7.7582, -7.7582, 0)
	S056 = Part.LineSegment(P084, P085)
	P086 = App.Vector(8.5672, -8.0458, 0)
	P087 = App.Vector(9.3011, -7.6001, 0)
	S057 = Part.Arc(P085, P086, P087)
	P088 = App.Vector(10.6689, -5.5177, 0)
	S058 = Part.LineSegment(P087, P088)
	P089 = App.Vector(10.7866, -4.6672, 0)
	P090 = App.Vector(10.2012, -4.0389, 0)
	S059 = Part.Arc(P088, P089, P090)
	P091 = App.Vector(8.2074, -3.2495, 0)
	S060 = Part.LineSegment(P090, P091)
	P092 = App.Vector(7.6992, -2.8015, 0)
	P093 = App.Vector(7.5932, -2.1324, 0)
	S061 = Part.Arc(P091, P092, P093)
	P094 = App.Vector(7.8450, -0.8126, 0)
	S062 = Part.LineSegment(P093, P094)
	P095 = App.Vector(8.1898, -0.2295, 0)
	P096 = App.Vector(8.8273, -0.0000, 0)
	S063 = Part.Arc(P094, P095, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047, S048, S049, S050, S051, S052, S053, S054, S055, S056, S057, S058, S059, S060, S061, S062, S063])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(15.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(10.6066, 10.6066, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(0.0000, 15.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-10.6066, 10.6066, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-15.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-10.6066, -10.6066, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-0.0000, -15.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr9():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(10.6066, -10.6066, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr10():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(40.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr11():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(36.9552, 15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr12():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(28.2843, 28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr13():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(15.3073, 36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr14():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(0.0000, 40.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr15():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-15.3073, 36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr16():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-28.2843, 28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr17():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-36.9552, 15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr18():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-40.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr19():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-36.9552, -15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr20():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-28.2843, -28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr21():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-15.3073, -36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr22():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-0.0000, -40.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr23():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(15.3073, -36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr24():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(28.2843, -28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr25():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(36.9552, -15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr26():
	P000 = App.Vector(17.9374, 0.5000, 0)
	P001 = App.Vector(34.9358, 0.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(35.3871, 0.9512, 0)
	P003 = App.Vector(34.9358, 1.4024, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(19.8471, 1.4024, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(18.3959, 2.8536, 0)
	P006 = App.Vector(19.8471, 4.3048, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(34.6237, 4.3048, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(35.0749, 4.7560, 0)
	P009 = App.Vector(34.6237, 5.2072, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(18.9134, 5.2072, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(17.4622, 6.6584, 0)
	P012 = App.Vector(18.9134, 8.1096, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(33.8841, 8.1096, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(34.3353, 8.5608, 0)
	P015 = App.Vector(33.8841, 9.0121, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(18.5397, 9.0121, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(17.0885, 10.4633, 0)
	P018 = App.Vector(18.5397, 11.9145, 0)
	S011 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(32.6880, 11.9145, 0)
	S012 = Part.LineSegment(P018, P019)
	P020 = App.Vector(33.1393, 12.3657, 0)
	P021 = App.Vector(32.6880, 12.8169, 0)
	S013 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(24.6287, 12.8169, 0)
	S014 = Part.LineSegment(P021, P022)
	P023 = App.Vector(23.1775, 14.2681, 0)
	P024 = App.Vector(24.6287, 15.7193, 0)
	S015 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(30.9828, 15.7193, 0)
	S016 = Part.LineSegment(P024, P025)
	P026 = App.Vector(31.4340, 16.1705, 0)
	P027 = App.Vector(30.9828, 16.6217, 0)
	S017 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(30.7177, 16.6217, 0)
	S018 = Part.LineSegment(P027, P028)
	P029 = App.Vector(29.3227, 17.6729, 0)
	P030 = App.Vector(29.9487, 19.3036, 0)
	S019 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(31.0870, 20.0149, 0)
	S020 = Part.LineSegment(P030, P031)
	P032 = App.Vector(31.5358, 20.6578, 0)
	P033 = App.Vector(31.3830, 21.4268, 0)
	S021 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(23.3951, 29.9444, 0)
	P035 = App.Vector(13.1981, 35.6344, 0)
	S022 = Part.Arc(P033, P034, P035)
	P036 = App.Vector(12.4150, 35.5967, 0)
	P037 = App.Vector(11.8998, 35.0057, 0)
	S023 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(11.4850, 33.7290, 0)
	S024 = Part.LineSegment(P037, P038)
	P039 = App.Vector(11.6618, 33.2155, 0)
	P040 = App.Vector(12.2041, 33.2439, 0)
	S025 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(12.4072, 33.4144, 0)
	S026 = Part.LineSegment(P040, P041)
	P042 = App.Vector(14.4517, 33.2355, 0)
	P043 = App.Vector(14.2728, 31.1910, 0)
	S027 = Part.Arc(P041, P042, P043)
	P044 = App.Vector(9.4053, 27.1066, 0)
	S028 = Part.LineSegment(P043, P044)
	P045 = App.Vector(9.3497, 26.4710, 0)
	P046 = App.Vector(9.9854, 26.4154, 0)
	S029 = Part.Arc(P044, P045, P046)
	P047 = App.Vector(16.1592, 31.5958, 0)
	S030 = Part.LineSegment(P046, P047)
	P048 = App.Vector(18.2037, 31.4169, 0)
	P049 = App.Vector(18.0248, 29.3724, 0)
	S031 = Part.Arc(P047, P048, P049)
	P050 = App.Vector(7.1866, 20.2781, 0)
	S032 = Part.LineSegment(P049, P050)
	P051 = App.Vector(7.1309, 19.6424, 0)
	P052 = App.Vector(7.7666, 19.5868, 0)
	S033 = Part.Arc(P050, P051, P052)
	P053 = App.Vector(19.5211, 29.4499, 0)
	S034 = Part.LineSegment(P052, P053)
	P054 = App.Vector(21.5656, 29.2711, 0)
	P055 = App.Vector(21.3867, 27.2266, 0)
	S035 = Part.Arc(P053, P054, P055)
	P056 = App.Vector(9.9185, 17.6036, 0)
	S036 = Part.LineSegment(P055, P056)
	P057 = App.Vector(9.8629, 16.9679, 0)
	P058 = App.Vector(10.4986, 16.9123, 0)
	S037 = Part.Arc(P056, P057, P058)
	P059 = App.Vector(22.5333, 27.0107, 0)
	S038 = Part.LineSegment(P058, P059)
	P060 = App.Vector(24.5778, 26.8318, 0)
	P061 = App.Vector(24.3990, 24.7873, 0)
	S039 = Part.Arc(P059, P060, P061)
	P062 = App.Vector(13.0795, 15.2891, 0)
	S040 = Part.LineSegment(P061, P062)
	P063 = App.Vector(13.0239, 14.6534, 0)
	P064 = App.Vector(13.6595, 14.5978, 0)
	S041 = Part.Arc(P062, P063, P064)
	P065 = App.Vector(25.2182, 24.2967, 0)
	S042 = Part.LineSegment(P064, P065)
	P066 = App.Vector(27.2627, 24.1178, 0)
	P067 = App.Vector(27.0838, 22.0733, 0)
	S043 = Part.Arc(P065, P066, P067)
	P068 = App.Vector(14.0622, 11.1469, 0)
	S044 = Part.LineSegment(P067, P068)
	P069 = App.Vector(13.7133, 10.5095, 0)
	P070 = App.Vector(13.8881, 9.8042, 0)
	S045 = Part.Arc(P068, P069, P070)
	P071 = App.Vector(15.9748, 5.8143, 0)
	P072 = App.Vector(16.9409, 1.4167, 0)
	S046 = Part.Arc(P070, P071, P072)
	P073 = App.Vector(17.2604, 0.7640, 0)
	P074 = App.Vector(17.9374, 0.5000, 0)
	S047 = Part.Arc(P072, P073, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr27():
	P000 = App.Vector(13.4194, 11.9130, 0)
	P001 = App.Vector(26.4410, 22.8394, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(26.4966, 23.4750, 0)
	P003 = App.Vector(25.8610, 23.5306, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(14.3023, 13.8318, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(12.2578, 14.0107, 0)
	P006 = App.Vector(12.4367, 16.0552, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(23.7562, 25.5533, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(23.8118, 26.1890, 0)
	P009 = App.Vector(23.1761, 26.2446, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(11.1413, 16.1463, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(9.0968, 16.3251, 0)
	P012 = App.Vector(9.2757, 18.3696, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(20.7439, 27.9926, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(20.7995, 28.6283, 0)
	P015 = App.Vector(20.1639, 28.6839, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(8.4094, 18.8207, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(6.3649, 18.9996, 0)
	P018 = App.Vector(6.5438, 21.0441, 0)
	S011 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(17.3820, 30.1385, 0)
	S012 = Part.LineSegment(P018, P019)
	P020 = App.Vector(17.4376, 30.7742, 0)
	P021 = App.Vector(16.8020, 30.8298, 0)
	S013 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(10.6281, 25.6493, 0)
	S014 = Part.LineSegment(P021, P022)
	P023 = App.Vector(8.5836, 25.8282, 0)
	P024 = App.Vector(8.7625, 27.8727, 0)
	S015 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(13.6300, 31.9570, 0)
	S016 = Part.LineSegment(P024, P025)
	P026 = App.Vector(13.6857, 32.5927, 0)
	P027 = App.Vector(13.0500, 32.6483, 0)
	S017 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(12.8469, 32.4779, 0)
	S018 = Part.LineSegment(P027, P028)
	P029 = App.Vector(11.1026, 32.3865, 0)
	P030 = App.Vector(10.5339, 34.0380, 0)
	S019 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(10.9487, 35.3147, 0)
	S020 = Part.LineSegment(P030, P031)
	P032 = App.Vector(10.8793, 36.0956, 0)
	P033 = App.Vector(10.2679, 36.5865, 0)
	S021 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(-1.3262, 37.9769, 0)
	P035 = App.Vector(-12.7950, 35.7811, 0)
	S022 = Part.Arc(P033, P034, P035)
	P036 = App.Vector(-13.3707, 35.2488, 0)
	P037 = App.Vector(-13.3855, 34.4649, 0)
	S023 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(-12.8826, 33.2203, 0)
	S024 = Part.LineSegment(P037, P038)
	P039 = App.Vector(-12.4171, 32.9406, 0)
	P040 = App.Vector(-12.0199, 33.3110, 0)
	S025 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(-11.9739, 33.5721, 0)
	S026 = Part.LineSegment(P040, P041)
	P042 = App.Vector(-10.2927, 34.7492, 0)
	P043 = App.Vector(-9.1156, 33.0681, 0)
	S027 = Part.Arc(P041, P042, P043)
	P044 = App.Vector(-10.2189, 26.8105, 0)
	S028 = Part.LineSegment(P043, P044)
	P045 = App.Vector(-9.8529, 26.2878, 0)
	P046 = App.Vector(-9.3302, 26.6538, 0)
	S029 = Part.Arc(P044, P045, P046)
	P047 = App.Vector(-7.9307, 34.5907, 0)
	S030 = Part.LineSegment(P046, P047)
	P048 = App.Vector(-6.2496, 35.7679, 0)
	P049 = App.Vector(-5.0724, 34.0867, 0)
	S031 = Part.Arc(P047, P048, P049)
	P050 = App.Vector(-7.5293, 20.1533, 0)
	S032 = Part.LineSegment(P049, P050)
	P051 = App.Vector(-7.1633, 19.6306, 0)
	P052 = App.Vector(-6.6406, 19.9966, 0)
	S033 = Part.Arc(P050, P051, P052)
	P053 = App.Vector(-3.9760, 35.1079, 0)
	S034 = Part.LineSegment(P052, P053)
	P054 = App.Vector(-2.2949, 36.2850, 0)
	P055 = App.Vector(-1.1177, 34.6039, 0)
	S035 = Part.Arc(P053, P054, P055)
	P056 = App.Vector(-3.7174, 19.8606, 0)
	S036 = Part.LineSegment(P055, P056)
	P057 = App.Vector(-3.3514, 19.3379, 0)
	P058 = App.Vector(-2.8287, 19.7039, 0)
	S037 = Part.Arc(P056, P057, P058)
	P059 = App.Vector(-0.1006, 35.1755, 0)
	S038 = Part.LineSegment(P058, P059)
	P060 = App.Vector(1.5806, 36.3527, 0)
	P061 = App.Vector(2.7577, 34.6715, 0)
	S039 = Part.Arc(P059, P060, P061)
	P062 = App.Vector(0.1918, 20.1195, 0)
	S040 = Part.LineSegment(P061, P062)
	P063 = App.Vector(0.5578, 19.5968, 0)
	P064 = App.Vector(1.0805, 19.9628, 0)
	S041 = Part.Arc(P062, P063, P064)
	P065 = App.Vector(3.7006, 34.8223, 0)
	S042 = Part.LineSegment(P064, P065)
	P066 = App.Vector(5.3818, 35.9994, 0)
	P067 = App.Vector(6.5590, 34.3183, 0)
	S043 = Part.Arc(P065, P066, P067)
	P068 = App.Vector(3.6072, 17.5781, 0)
	S044 = Part.LineSegment(P067, P068)
	P069 = App.Vector(3.7496, 16.8655, 0)
	P070 = App.Vector(4.3369, 16.4375, 0)
	S045 = Part.Arc(P068, P069, P070)
	P071 = App.Vector(8.5000, 14.7224, 0)
	P072 = App.Vector(12.0668, 11.9746, 0)
	S046 = Part.Arc(P070, P071, P072)
	P073 = App.Vector(12.7311, 11.6800, 0)
	P074 = App.Vector(13.4194, 11.9130, 0)
	S047 = Part.Arc(P072, P073, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr28():
	P000 = App.Vector(2.6224, 17.7517, 0)
	P001 = App.Vector(5.5741, 34.4919, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(5.2081, 35.0146, 0)
	P003 = App.Vector(4.6854, 34.6486, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(2.0653, 19.7891, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(0.3842, 18.6120, 0)
	P006 = App.Vector(-0.7930, 20.2931, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(1.7729, 34.8452, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(1.4069, 35.3679, 0)
	P009 = App.Vector(0.8842, 35.0019, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-1.8438, 19.5303, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-3.5250, 18.3531, 0)
	P012 = App.Vector(-4.7022, 20.0343, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(-2.1025, 34.7775, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(-2.4685, 35.3002, 0)
	P015 = App.Vector(-2.9912, 34.9342, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(-5.6558, 19.8230, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(-7.3369, 18.6458, 0)
	P018 = App.Vector(-8.5141, 20.3270, 0)
	S011 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(-6.0572, 34.2604, 0)
	S012 = Part.LineSegment(P018, P019)
	P020 = App.Vector(-6.4232, 34.7831, 0)
	P021 = App.Vector(-6.9459, 34.4171, 0)
	S013 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(-8.3454, 26.4802, 0)
	S014 = Part.LineSegment(P021, P022)
	P023 = App.Vector(-10.0266, 25.3030, 0)
	P024 = App.Vector(-11.2037, 26.9842, 0)
	S015 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(-10.1004, 33.2417, 0)
	S016 = Part.LineSegment(P024, P025)
	P026 = App.Vector(-10.4664, 33.7644, 0)
	P027 = App.Vector(-10.9891, 33.3984, 0)
	S017 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(-11.0351, 33.1373, 0)
	S018 = Part.LineSegment(P027, P028)
	P029 = App.Vector(-12.3126, 31.9461, 0)
	P030 = App.Vector(-13.8098, 32.8457, 0)
	S019 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(-14.3126, 34.0903, 0)
	S020 = Part.LineSegment(P030, P031)
	P032 = App.Vector(-14.8678, 34.6439, 0)
	P033 = App.Vector(-15.6517, 34.6269, 0)
	S021 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(-25.4270, 28.2395, 0)
	P035 = App.Vector(-32.8012, 19.1855, 0)
	S022 = Part.Arc(P033, P034, P035)
	P036 = App.Vector(-32.9000, 18.4077, 0)
	P037 = App.Vector(-32.4075, 17.7976, 0)
	S023 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(-31.2223, 17.1675, 0)
	S024 = Part.LineSegment(P037, P038)
	P039 = App.Vector(-30.6859, 17.2524, 0)
	P040 = App.Vector(-30.6197, 17.7914, 0)
	S025 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(-30.7522, 18.0210, 0)
	S026 = Part.LineSegment(P040, P041)
	P042 = App.Vector(-30.2211, 20.0034, 0)
	P043 = App.Vector(-28.2387, 19.4722, 0)
	S027 = Part.Arc(P041, P042, P043)
	P044 = App.Vector(-25.0616, 13.9694, 0)
	S028 = Part.LineSegment(P043, P044)
	P045 = App.Vector(-24.4453, 13.8043, 0)
	P046 = App.Vector(-24.2801, 14.4206, 0)
	S029 = Part.Arc(P044, P045, P046)
	P047 = App.Vector(-28.3098, 21.4002, 0)
	S030 = Part.LineSegment(P046, P047)
	P048 = App.Vector(-27.7786, 23.3826, 0)
	P049 = App.Vector(-25.7962, 22.8515, 0)
	S031 = Part.Arc(P047, P048, P049)
	P050 = App.Vector(-18.7221, 10.5986, 0)
	S032 = Part.LineSegment(P049, P050)
	P051 = App.Vector(-18.1057, 10.4335, 0)
	P052 = App.Vector(-17.9405, 11.0498, 0)
	S033 = Part.Arc(P050, P051, P052)
	P053 = App.Vector(-25.6127, 24.3384, 0)
	S034 = Part.LineSegment(P052, P053)
	P054 = App.Vector(-25.0815, 26.3208, 0)
	P055 = App.Vector(-23.0992, 25.7896, 0)
	S035 = Part.Arc(P053, P054, P055)
	P056 = App.Vector(-15.6138, 12.8246, 0)
	S036 = Part.LineSegment(P055, P056)
	P057 = App.Vector(-14.9975, 12.6595, 0)
	P058 = App.Vector(-14.8323, 13.2759, 0)
	S037 = Part.Arc(P056, P057, P058)
	P059 = App.Vector(-22.6875, 26.8814, 0)
	S038 = Part.LineSegment(P058, P059)
	P060 = App.Vector(-22.1563, 28.8637, 0)
	P061 = App.Vector(-20.1739, 28.3326, 0)
	S039 = Part.Arc(P059, P060, P061)
	P062 = App.Vector(-12.7856, 15.5357, 0)
	S040 = Part.LineSegment(P061, P062)
	P063 = App.Vector(-12.1693, 15.3705, 0)
	P064 = App.Vector(-12.0041, 15.9869, 0)
	S041 = Part.Arc(P062, P063, P064)
	P065 = App.Vector(-19.5485, 29.0541, 0)
	S042 = Part.LineSegment(P064, P065)
	P066 = App.Vector(-19.0173, 31.0365, 0)
	P067 = App.Vector(-17.0349, 30.5053, 0)
	S043 = Part.Arc(P065, P066, P067)
	P068 = App.Vector(-8.5357, 15.7842, 0)
	S044 = Part.LineSegment(P067, P068)
	P069 = App.Vector(-7.9685, 15.3299, 0)
	P070 = App.Vector(-7.2436, 15.3796, 0)
	S045 = Part.Arc(P068, P069, P070)
	P071 = App.Vector(-2.9520, 16.7417, 0)
	P072 = App.Vector(1.5466, 16.9295, 0)
	S046 = Part.Arc(P070, P071, P072)
	P073 = App.Vector(2.2448, 17.1308, 0)
	P074 = App.Vector(2.6224, 17.7517, 0)
	S047 = Part.Arc(P072, P073, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr29():
	P000 = App.Vector(-9.4017, 15.2842, 0)
	P001 = App.Vector(-17.9009, 30.0053, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-18.5173, 30.1705, 0)
	P003 = App.Vector(-18.6824, 29.5541, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-11.1381, 16.4869, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-11.6693, 14.5045, 0)
	P006 = App.Vector(-13.6516, 15.0357, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-21.0399, 27.8326, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-21.6563, 27.9977, 0)
	P009 = App.Vector(-21.8214, 27.3814, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-13.9663, 13.7759, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-14.4975, 11.7935, 0)
	P012 = App.Vector(-16.4798, 12.3246, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(-23.9652, 25.2896, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(-24.5815, 25.4548, 0)
	P015 = App.Vector(-24.7467, 24.8384, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(-17.0745, 11.5498, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(-17.6057, 9.5675, 0)
	P018 = App.Vector(-19.5881, 10.0986, 0)
	S011 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(-26.6623, 22.3515, 0)
	S012 = Part.LineSegment(P018, P019)
	P020 = App.Vector(-27.2786, 22.5166, 0)
	P021 = App.Vector(-27.4438, 21.9002, 0)
	S013 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(-23.4141, 14.9206, 0)
	S014 = Part.LineSegment(P021, P022)
	P023 = App.Vector(-23.9453, 12.9383, 0)
	P024 = App.Vector(-25.9276, 13.4694, 0)
	S015 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(-29.1047, 18.9722, 0)
	S016 = Part.LineSegment(P024, P025)
	P026 = App.Vector(-29.7211, 19.1374, 0)
	P027 = App.Vector(-29.8862, 18.5210, 0)
	S017 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(-29.7536, 18.2914, 0)
	S018 = Part.LineSegment(P027, P028)
	P029 = App.Vector(-29.9665, 16.5578, 0)
	P030 = App.Vector(-31.6917, 16.2845, 0)
	S019 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(-32.8769, 16.9147, 0)
	S020 = Part.LineSegment(P030, P031)
	P032 = App.Vector(-33.6581, 16.9819, 0)
	P033 = App.Vector(-34.2477, 16.4650, 0)
	S021 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(-37.6302, 5.2886, 0)
	P035 = App.Vector(-37.4593, -6.3873, 0)
	S022 = Part.Arc(P033, P034, P035)
	P036 = App.Vector(-37.0351, -7.0466, 0)
	P037 = App.Vector(-36.2657, -7.1973, 0)
	S023 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(-34.9527, -6.9182, 0)
	S024 = Part.LineSegment(P037, P038)
	P039 = App.Vector(-34.5964, -6.5084, 0)
	P040 = App.Vector(-34.8922, -6.0529, 0)
	S025 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(-35.1413, -5.9622, 0)
	S026 = Part.LineSegment(P040, P041)
	P042 = App.Vector(-36.0086, -4.1022, 0)
	P043 = App.Vector(-34.1486, -3.2349, 0)
	S027 = Part.Arc(P041, P042, P043)
	P044 = App.Vector(-28.1777, -5.4081, 0)
	S028 = Part.LineSegment(P043, P044)
	P045 = App.Vector(-27.5994, -5.1384, 0)
	P046 = App.Vector(-27.8691, -4.5601, 0)
	S029 = Part.Arc(P044, P045, P046)
	P047 = App.Vector(-35.4424, -1.8036, 0)
	S030 = Part.LineSegment(P046, P047)
	P048 = App.Vector(-36.3097, 0.0564, 0)
	P049 = App.Vector(-34.4497, 0.9237, 0)
	S031 = Part.Arc(P047, P048, P049)
	P050 = App.Vector(-21.1546, -3.9153, 0)
	S032 = Part.LineSegment(P049, P050)
	P051 = App.Vector(-20.5763, -3.6456, 0)
	P052 = App.Vector(-20.8460, -3.0673, 0)
	S033 = Part.Arc(P050, P051, P052)
	P053 = App.Vector(-35.2649, 2.1808, 0)
	S034 = Part.LineSegment(P052, P053)
	P054 = App.Vector(-36.1323, 4.0408, 0)
	P055 = App.Vector(-34.2723, 4.9082, 0)
	S035 = Part.Arc(P053, P054, P055)
	P056 = App.Vector(-20.2044, -0.2121, 0)
	S036 = Part.LineSegment(P055, P056)
	P057 = App.Vector(-19.6261, 0.0576, 0)
	P058 = App.Vector(-19.8958, 0.6359, 0)
	S037 = Part.Arc(P056, P057, P058)
	P059 = App.Vector(-34.6586, 6.0091, 0)
	S038 = Part.LineSegment(P058, P059)
	P060 = App.Vector(-35.5259, 7.8691, 0)
	P061 = App.Vector(-33.6659, 8.7365, 0)
	S039 = Part.Arc(P059, P060, P061)
	P062 = App.Vector(-19.7805, 3.6826, 0)
	S040 = Part.LineSegment(P061, P062)
	P063 = App.Vector(-19.2022, 3.9523, 0)
	P064 = App.Vector(-19.4719, 4.5306, 0)
	S041 = Part.Arc(P062, P063, P064)
	P065 = App.Vector(-33.6506, 9.6912, 0)
	S042 = Part.LineSegment(P064, P065)
	P066 = App.Vector(-34.5180, 11.5513, 0)
	P067 = App.Vector(-32.6579, 12.4186, 0)
	S043 = Part.Arc(P065, P066, P067)
	P068 = App.Vector(-16.6846, 6.6048, 0)
	S044 = Part.LineSegment(P067, P068)
	P069 = App.Vector(-15.9581, 6.6213, 0)
	P070 = App.Vector(-15.4347, 7.1253, 0)
	S045 = Part.Arc(P068, P069, P070)
	P071 = App.Vector(-13.0228, 10.9274, 0)
	P072 = App.Vector(-9.6973, 13.9629, 0)
	S046 = Part.Arc(P070, P071, P072)
	P073 = App.Vector(-9.2919, 14.5659, 0)
	P074 = App.Vector(-9.4017, 15.2842, 0)
	S047 = Part.Arc(P072, P073, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr30():
	P000 = App.Vector(-17.0266, 5.6651, 0)
	P001 = App.Vector(-33.0000, 11.4789, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-33.5783, 11.2092, 0)
	P003 = App.Vector(-33.3086, 10.6309, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-19.1298, 5.4703, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-18.2625, 3.6102, 0)
	P006 = App.Vector(-20.1225, 2.7429, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-34.0079, 7.7968, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-34.5863, 7.5271, 0)
	P009 = App.Vector(-34.3166, 6.9488, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-19.5537, 1.5756, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-18.6864, -0.2845, 0)
	P012 = App.Vector(-20.5464, -1.1518, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(-34.6143, 3.9685, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(-35.1926, 3.6988, 0)
	P015 = App.Vector(-34.9229, 3.1205, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(-20.5039, -2.1276, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(-19.6366, -3.9876, 0)
	P018 = App.Vector(-21.4966, -4.8550, 0)
	S011 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(-34.7917, -0.0160, 0)
	S012 = Part.LineSegment(P018, P019)
	P020 = App.Vector(-35.3700, -0.2856, 0)
	P021 = App.Vector(-35.1003, -0.8639, 0)
	S013 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(-27.5270, -3.6204, 0)
	S014 = Part.LineSegment(P021, P022)
	P023 = App.Vector(-26.6597, -5.4804, 0)
	P024 = App.Vector(-28.5197, -6.3478, 0)
	S015 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(-34.4906, -4.1746, 0)
	S016 = Part.LineSegment(P024, P025)
	P026 = App.Vector(-35.0689, -4.4442, 0)
	P027 = App.Vector(-34.7993, -5.0225, 0)
	S017 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(-34.5501, -5.1132, 0)
	S018 = Part.LineSegment(P027, P028)
	P029 = App.Vector(-33.5988, -6.5781, 0)
	P030 = App.Vector(-34.7447, -7.8964, 0)
	S019 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(-36.0578, -8.1755, 0)
	S020 = Part.LineSegment(P030, P031)
	P032 = App.Vector(-36.6994, -8.6261, 0)
	P033 = App.Vector(-36.8188, -9.4010, 0)
	S021 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(-32.2258, -20.1369, 0)
	P035 = App.Vector(-24.5899, -28.9713, 0)
	S022 = Part.Arc(P033, P034, P035)
	P036 = App.Vector(-23.8410, -29.2037, 0)
	P037 = App.Vector(-23.1548, -28.8246, 0)
	S023 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(-22.3283, -27.7668, 0)
	S024 = Part.LineSegment(P037, P038)
	P039 = App.Vector(-22.3189, -27.2238, 0)
	P040 = App.Vector(-22.8382, -27.0650, 0)
	S025 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(-23.0873, -27.1557, 0)
	S026 = Part.LineSegment(P040, P041)
	P042 = App.Vector(-24.9474, -26.2884, 0)
	P043 = App.Vector(-24.0800, -24.4283, 0)
	S027 = Part.Arc(P041, P042, P043)
	P044 = App.Vector(-18.1091, -22.2551, 0)
	S028 = Part.LineSegment(P043, P044)
	P045 = App.Vector(-17.8394, -21.6768, 0)
	P046 = App.Vector(-18.4178, -21.4071, 0)
	S029 = Part.Arc(P044, P045, P046)
	P047 = App.Vector(-25.9911, -24.1636, 0)
	S030 = Part.LineSegment(P046, P047)
	P048 = App.Vector(-27.8511, -23.2962, 0)
	P049 = App.Vector(-26.9838, -21.4362, 0)
	S031 = Part.Arc(P047, P048, P049)
	P050 = App.Vector(-13.6887, -16.5972, 0)
	S032 = Part.LineSegment(P049, P050)
	P051 = App.Vector(-13.4190, -16.0189, 0)
	P052 = App.Vector(-13.9973, -15.7492, 0)
	S033 = Part.Arc(P050, P051, P052)
	P053 = App.Vector(-28.4163, -20.9973, 0)
	S034 = Part.LineSegment(P052, P053)
	P054 = App.Vector(-30.2763, -20.1299, 0)
	P055 = App.Vector(-29.4090, -18.2699, 0)
	S035 = Part.Arc(P053, P054, P055)
	P056 = App.Vector(-15.3411, -13.1496, 0)
	S036 = Part.LineSegment(P055, P056)
	P057 = App.Vector(-15.0715, -12.5713, 0)
	P058 = App.Vector(-15.6498, -12.3016, 0)
	S037 = Part.Arc(P056, P057, P058)
	P059 = App.Vector(-30.4126, -17.6749, 0)
	S038 = Part.LineSegment(P058, P059)
	P060 = App.Vector(-32.2726, -16.8075, 0)
	P061 = App.Vector(-31.4053, -14.9475, 0)
	S039 = Part.Arc(P059, P060, P061)
	P062 = App.Vector(-17.5199, -9.8936, 0)
	S040 = Part.LineSegment(P061, P062)
	P063 = App.Vector(-17.2502, -9.3153, 0)
	P064 = App.Vector(-17.8285, -9.0456, 0)
	S041 = Part.Arc(P062, P063, P064)
	P065 = App.Vector(-32.0073, -14.2063, 0)
	S042 = Part.LineSegment(P064, P065)
	P066 = App.Vector(-33.8673, -13.3389, 0)
	P067 = App.Vector(-33.0000, -11.4789, 0)
	S043 = Part.Arc(P065, P066, P067)
	P068 = App.Vector(-17.0266, -5.6651, 0)
	S044 = Part.LineSegment(P067, P068)
	P069 = App.Vector(-16.4808, -5.1855, 0)
	P070 = App.Vector(-16.4037, -4.4629, 0)
	S045 = Part.Arc(P068, P069, P070)
	P071 = App.Vector(-17.0000, 0.0000, 0)
	P072 = App.Vector(-16.4037, 4.4629, 0)
	S046 = Part.Arc(P070, P071, P072)
	P073 = App.Vector(-16.4808, 5.1855, 0)
	P074 = App.Vector(-17.0266, 5.6651, 0)
	S047 = Part.Arc(P072, P073, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr31():
	P000 = App.Vector(-16.6846, -6.6048, 0)
	P001 = App.Vector(-32.6579, -12.4186, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-32.9276, -12.9969, 0)
	P003 = App.Vector(-32.3493, -13.2666, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-18.1705, -8.1059, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-16.3105, -8.9733, 0)
	P006 = App.Vector(-17.1778, -10.8333, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-31.0633, -15.8872, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-31.3329, -16.4655, 0)
	P009 = App.Vector(-30.7546, -16.7352, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-15.9918, -11.3620, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-14.1318, -12.2293, 0)
	P012 = App.Vector(-14.9991, -14.0893, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(-29.0669, -19.2096, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(-29.3366, -19.7879, 0)
	P015 = App.Vector(-28.7583, -20.0576, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(-14.3393, -14.8095, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(-12.4793, -15.6769, 0)
	P018 = App.Vector(-13.3466, -17.5369, 0)
	S011 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(-26.6417, -22.3759, 0)
	S012 = Part.LineSegment(P018, P019)
	P020 = App.Vector(-26.9114, -22.9542, 0)
	P021 = App.Vector(-26.3331, -23.2239, 0)
	S013 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(-18.7598, -20.4674, 0)
	S014 = Part.LineSegment(P021, P022)
	P023 = App.Vector(-16.8997, -21.3348, 0)
	P024 = App.Vector(-17.7671, -23.1948, 0)
	S015 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(-23.7380, -25.3680, 0)
	S016 = Part.LineSegment(P024, P025)
	P026 = App.Vector(-24.0077, -25.9463, 0)
	P027 = App.Vector(-23.4294, -26.2160, 0)
	S017 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(-23.1802, -26.1253, 0)
	S018 = Part.LineSegment(P027, P028)
	P029 = App.Vector(-21.5098, -26.6360, 0)
	P030 = App.Vector(-21.5403, -28.3825, 0)
	S019 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(-22.3667, -29.4403, 0)
	S020 = Part.LineSegment(P030, P031)
	P032 = App.Vector(-22.5686, -30.1979, 0)
	P033 = App.Vector(-22.1619, -30.8682, 0)
	S021 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(-11.7426, -36.1401, 0)
	P035 = App.Vector(-0.2145, -37.9994, 0)
	S022 = Part.Arc(P033, P034, P035)
	P036 = App.Vector(0.5085, -37.6961, 0)
	P037 = App.Vector(0.7905, -36.9645, 0)
	S023 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(0.7437, -35.6230, 0)
	S024 = Part.LineSegment(P037, P038)
	P039 = App.Vector(0.4019, -35.2009, 0)
	P040 = App.Vector(-0.0980, -35.4131, 0)
	S025 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(-0.2306, -35.6427, 0)
	S026 = Part.LineSegment(P040, P041)
	P042 = App.Vector(-2.2129, -36.1739, 0)
	P043 = App.Vector(-2.7441, -34.1915, 0)
	S027 = Part.Arc(P041, P042, P043)
	P044 = App.Vector(0.4329, -28.6887, 0)
	S028 = Part.LineSegment(P043, P044)
	P045 = App.Vector(0.2678, -28.0724, 0)
	P046 = App.Vector(-0.3486, -28.2375, 0)
	S029 = Part.Arc(P044, P045, P046)
	P047 = App.Vector(-4.3783, -35.2171, 0)
	S030 = Part.LineSegment(P046, P047)
	P048 = App.Vector(-6.3606, -35.7483, 0)
	P049 = App.Vector(-6.8918, -33.7659, 0)
	S031 = Part.Arc(P047, P048, P049)
	P050 = App.Vector(0.1823, -21.5131, 0)
	S032 = Part.LineSegment(P049, P050)
	P051 = App.Vector(0.0172, -20.8967, 0)
	P052 = App.Vector(-0.5992, -21.0619, 0)
	S033 = Part.Arc(P050, P051, P052)
	P053 = App.Vector(-8.2713, -34.3505, 0)
	S034 = Part.LineSegment(P052, P053)
	P054 = App.Vector(-10.2537, -34.8817, 0)
	P055 = App.Vector(-10.7849, -32.8993, 0)
	S035 = Part.Arc(P053, P054, P055)
	P056 = App.Vector(-3.2996, -19.9343, 0)
	S036 = Part.LineSegment(P055, P056)
	P057 = App.Vector(-3.4647, -19.3179, 0)
	P058 = App.Vector(-4.0811, -19.4831, 0)
	S037 = Part.Arc(P056, P057, P058)
	P059 = App.Vector(-11.9362, -33.0886, 0)
	S038 = Part.LineSegment(P058, P059)
	P060 = App.Vector(-13.9186, -33.6198, 0)
	P061 = App.Vector(-14.4498, -31.6374, 0)
	S039 = Part.Arc(P059, P060, P061)
	P062 = App.Vector(-7.0615, -18.8405, 0)
	S040 = Part.LineSegment(P061, P062)
	P063 = App.Vector(-7.2266, -18.2242, 0)
	P064 = App.Vector(-7.8430, -18.3893, 0)
	S041 = Part.Arc(P062, P063, P064)
	P065 = App.Vector(-15.3874, -31.4565, 0)
	S042 = Part.LineSegment(P064, P065)
	P066 = App.Vector(-17.3698, -31.9877, 0)
	P067 = App.Vector(-17.9009, -30.0053, 0)
	S043 = Part.Arc(P065, P066, P067)
	P068 = App.Vector(-9.4017, -15.2842, 0)
	S044 = Part.LineSegment(P067, P068)
	P069 = App.Vector(-9.2919, -14.5659, 0)
	P070 = App.Vector(-9.6973, -13.9629, 0)
	S045 = Part.Arc(P068, P069, P070)
	P071 = App.Vector(-13.0228, -10.9274, 0)
	P072 = App.Vector(-15.4347, -7.1253, 0)
	S046 = Part.Arc(P070, P071, P072)
	P073 = App.Vector(-15.9581, -6.6213, 0)
	P074 = App.Vector(-16.6846, -6.6048, 0)
	S047 = Part.Arc(P072, P073, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr32():
	P000 = App.Vector(-8.5357, -15.7842, 0)
	P001 = App.Vector(-17.0349, -30.5053, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-16.8698, -31.1217, 0)
	P003 = App.Vector(-16.2534, -30.9565, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-8.7090, -17.8893, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-6.7266, -17.3581, 0)
	P006 = App.Vector(-6.1955, -19.3405, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-13.5838, -32.1374, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-13.4186, -32.7537, 0)
	P009 = App.Vector(-12.8022, -32.5886, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-4.9471, -18.9831, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-2.9647, -18.4519, 0)
	P012 = App.Vector(-2.4335, -20.4343, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(-9.9189, -33.3993, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(-9.7537, -34.0156, 0)
	P015 = App.Vector(-9.1374, -33.8505, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(-1.4652, -20.5619, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(0.5172, -20.0307, 0)
	P018 = App.Vector(1.0484, -22.0131, 0)
	S011 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(-6.0258, -34.2659, 0)
	S012 = Part.LineSegment(P018, P019)
	P020 = App.Vector(-5.8606, -34.8823, 0)
	P021 = App.Vector(-5.2443, -34.7171, 0)
	S013 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(-1.2146, -27.7375, 0)
	S014 = Part.LineSegment(P021, P022)
	P023 = App.Vector(0.7678, -27.2063, 0)
	P024 = App.Vector(1.2989, -29.1887, 0)
	S015 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(-1.8781, -34.6915, 0)
	S016 = Part.LineSegment(P024, P025)
	P026 = App.Vector(-1.7129, -35.3079, 0)
	P027 = App.Vector(-1.0966, -35.1427, 0)
	S017 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(-0.9640, -34.9131, 0)
	S018 = Part.LineSegment(P027, P028)
	P029 = App.Vector(0.6438, -34.2306, 0)
	P030 = App.Vector(1.7431, -35.5881, 0)
	S019 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(1.7899, -36.9296, 0)
	S020 = Part.LineSegment(P030, P031)
	P032 = App.Vector(2.1223, -37.6397, 0)
	P033 = App.Vector(2.8647, -37.8919, 0)
	S021 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(14.2351, -35.2330, 0)
	P035 = App.Vector(24.2612, -29.2471, 0)
	S022 = Part.Arc(P033, P034, P035)
	P036 = App.Vector(24.6201, -28.5500, 0)
	P037 = App.Vector(24.3659, -27.8083, 0)
	S023 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(23.4677, -26.8108, 0)
	S024 = Part.LineSegment(P037, P038)
	P039 = App.Vector(22.9346, -26.7071, 0)
	P040 = App.Vector(22.6880, -27.1910, 0)
	S025 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(22.7341, -27.4521, 0)
	S026 = Part.LineSegment(P040, P041)
	P042 = App.Vector(21.5569, -29.1333, 0)
	P043 = App.Vector(19.8758, -27.9561, 0)
	S027 = Part.Arc(P041, P042, P043)
	P044 = App.Vector(18.7724, -21.6986, 0)
	S028 = Part.LineSegment(P043, P044)
	P045 = App.Vector(18.2497, -21.3326, 0)
	P046 = App.Vector(17.8837, -21.8553, 0)
	S029 = Part.Arc(P044, P045, P046)
	P047 = App.Vector(19.2832, -29.7922, 0)
	S030 = Part.LineSegment(P046, P047)
	P048 = App.Vector(18.1060, -31.4733, 0)
	P049 = App.Vector(16.4249, -30.2962, 0)
	S031 = Part.Arc(P047, P048, P049)
	P050 = App.Vector(13.9680, -16.3628, 0)
	S032 = Part.LineSegment(P049, P050)
	P051 = App.Vector(13.4453, -15.9968, 0)
	P052 = App.Vector(13.0793, -16.5195, 0)
	S033 = Part.Arc(P050, P051, P052)
	P053 = App.Vector(15.7439, -31.6307, 0)
	S034 = Part.LineSegment(P052, P053)
	P054 = App.Vector(14.5667, -33.3119, 0)
	P055 = App.Vector(12.8855, -32.1347, 0)
	S035 = Part.Arc(P053, P054, P055)
	P056 = App.Vector(10.2859, -17.3915, 0)
	S036 = Part.LineSegment(P055, P056)
	P057 = App.Vector(9.7632, -17.0255, 0)
	P058 = App.Vector(9.3972, -17.5482, 0)
	S037 = Part.Arc(P056, P057, P058)
	P059 = App.Vector(12.1253, -33.0198, 0)
	S038 = Part.LineSegment(P058, P059)
	P060 = App.Vector(10.9481, -34.7009, 0)
	P061 = App.Vector(9.2669, -33.5238, 0)
	S039 = Part.Arc(P059, P060, P061)
	P062 = App.Vector(6.7010, -18.9717, 0)
	S040 = Part.LineSegment(P061, P062)
	P063 = App.Vector(6.1783, -18.6057, 0)
	P064 = App.Vector(5.8123, -19.1284, 0)
	S041 = Part.Arc(P062, P063, P064)
	P065 = App.Vector(8.4325, -33.9879, 0)
	S042 = Part.LineSegment(P064, P065)
	P066 = App.Vector(7.2553, -35.6691, 0)
	P067 = App.Vector(5.5741, -34.4919, 0)
	S043 = Part.Arc(P065, P066, P067)
	P068 = App.Vector(2.6224, -17.7517, 0)
	S044 = Part.LineSegment(P067, P068)
	P069 = App.Vector(2.2448, -17.1308, 0)
	P070 = App.Vector(1.5466, -16.9295, 0)
	S045 = Part.Arc(P068, P069, P070)
	P071 = App.Vector(-2.9520, -16.7417, 0)
	P072 = App.Vector(-7.2436, -15.3796, 0)
	S046 = Part.Arc(P070, P071, P072)
	P073 = App.Vector(-7.9685, -15.3299, 0)
	P074 = App.Vector(-8.5357, -15.7842, 0)
	S047 = Part.Arc(P072, P073, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr33():
	P000 = App.Vector(3.6072, -17.5781, 0)
	P001 = App.Vector(6.5590, -34.3183, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(7.0817, -34.6843, 0)
	P003 = App.Vector(7.4477, -34.1616, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(4.8275, -19.3021, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(6.0047, -17.6209, 0)
	P006 = App.Vector(7.6858, -18.7981, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(10.2518, -33.3501, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(10.7745, -33.7161, 0)
	P009 = App.Vector(11.1405, -33.1934, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(8.4124, -17.7218, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(9.5896, -16.0407, 0)
	P012 = App.Vector(11.2707, -17.2178, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(13.8703, -31.9611, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(14.3930, -32.3271, 0)
	P015 = App.Vector(14.7590, -31.8044, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(12.0945, -16.6931, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(13.2717, -15.0120, 0)
	P018 = App.Vector(14.9528, -16.1891, 0)
	S011 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(17.4097, -30.1225, 0)
	S012 = Part.LineSegment(P018, P019)
	P020 = App.Vector(17.9324, -30.4885, 0)
	P021 = App.Vector(18.2984, -29.9658, 0)
	S013 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(16.8989, -22.0289, 0)
	S014 = Part.LineSegment(P021, P022)
	P023 = App.Vector(18.0760, -20.3477, 0)
	P024 = App.Vector(19.7572, -21.5249, 0)
	S015 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(20.8606, -27.7825, 0)
	S016 = Part.LineSegment(P024, P025)
	P026 = App.Vector(21.3833, -28.1485, 0)
	P027 = App.Vector(21.7493, -27.6258, 0)
	S017 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(21.7032, -27.3647, 0)
	S018 = Part.LineSegment(P027, P028)
	P029 = App.Vector(22.4962, -25.8083, 0)
	P030 = App.Vector(24.2109, -26.1416, 0)
	S019 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(25.1091, -27.1392, 0)
	S020 = Part.LineSegment(P030, P031)
	P032 = App.Vector(25.8201, -27.4695, 0)
	P033 = App.Vector(26.5509, -27.1855, 0)
	S021 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(33.5520, -17.8399, 0)
	P035 = App.Vector(37.3848, -6.8098, 0)
	S022 = Part.Arc(P033, P034, P035)
	P036 = App.Vector(37.2117, -6.0451, 0)
	P037 = App.Vector(36.5402, -5.6403, 0)
	S023 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(35.2109, -5.4535, 0)
	S024 = Part.LineSegment(P037, P038)
	P039 = App.Vector(34.7359, -5.7168, 0)
	P040 = App.Vector(34.8581, -6.2459, 0)
	S025 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(35.0612, -6.4164, 0)
	S026 = Part.LineSegment(P040, P041)
	P042 = App.Vector(35.2401, -8.4609, 0)
	P043 = App.Vector(33.1956, -8.6397, 0)
	S027 = Part.Arc(P041, P042, P043)
	P044 = App.Vector(28.3280, -4.5554, 0)
	S028 = Part.LineSegment(P043, P044)
	P045 = App.Vector(27.6924, -4.6110, 0)
	P046 = App.Vector(27.7480, -5.2467, 0)
	S029 = Part.Arc(P044, P045, P046)
	P047 = App.Vector(33.9218, -10.4271, 0)
	S030 = Part.LineSegment(P046, P047)
	P048 = App.Vector(34.1007, -12.4716, 0)
	P049 = App.Vector(32.0562, -12.6505, 0)
	S031 = Part.Arc(P047, P048, P049)
	P050 = App.Vector(21.2179, -3.5561, 0)
	S032 = Part.LineSegment(P049, P050)
	P051 = App.Vector(20.5822, -3.6117, 0)
	P052 = App.Vector(20.6379, -4.2474, 0)
	S033 = Part.Arc(P050, P051, P052)
	P053 = App.Vector(32.3923, -14.1106, 0)
	S034 = Part.LineSegment(P052, P053)
	P054 = App.Vector(32.5712, -16.1551, 0)
	P055 = App.Vector(30.5267, -16.3340, 0)
	S035 = Part.Arc(P053, P054, P055)
	P056 = App.Vector(19.0585, -6.7110, 0)
	S036 = Part.LineSegment(P055, P056)
	P057 = App.Vector(18.4228, -6.7666, 0)
	P058 = App.Vector(18.4784, -7.4023, 0)
	S037 = Part.Arc(P056, P057, P058)
	P059 = App.Vector(30.5132, -17.5007, 0)
	S038 = Part.LineSegment(P058, P059)
	P060 = App.Vector(30.6921, -19.5452, 0)
	P061 = App.Vector(28.6476, -19.7240, 0)
	S039 = Part.Arc(P059, P060, P061)
	P062 = App.Vector(17.3281, -10.2258, 0)
	S040 = Part.LineSegment(P061, P062)
	P063 = App.Vector(16.6924, -10.2815, 0)
	P064 = App.Vector(16.7480, -10.9171, 0)
	S041 = Part.Arc(P062, P063, P064)
	P065 = App.Vector(28.3067, -20.6160, 0)
	S042 = Part.LineSegment(P064, P065)
	P066 = App.Vector(28.4855, -22.6605, 0)
	P067 = App.Vector(26.4410, -22.8394, 0)
	S043 = Part.Arc(P065, P066, P067)
	P068 = App.Vector(13.4194, -11.9130, 0)
	S044 = Part.LineSegment(P067, P068)
	P069 = App.Vector(12.7311, -11.6800, 0)
	P070 = App.Vector(12.0668, -11.9746, 0)
	S045 = Part.Arc(P068, P069, P070)
	P071 = App.Vector(8.5000, -14.7224, 0)
	P072 = App.Vector(4.3369, -16.4375, 0)
	S046 = Part.Arc(P070, P071, P072)
	P073 = App.Vector(3.7496, -16.8655, 0)
	P074 = App.Vector(3.6072, -17.5781, 0)
	S047 = Part.Arc(P072, P073, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueB_faceProfile_Fa0_Ctr34():
	P000 = App.Vector(14.0622, -11.1469, 0)
	P001 = App.Vector(27.0838, -22.0733, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(27.7195, -22.0177, 0)
	P003 = App.Vector(27.6639, -21.3820, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(16.1052, -11.6832, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(15.9263, -9.6387, 0)
	P006 = App.Vector(17.9709, -9.4598, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(29.2904, -18.9580, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(29.9260, -18.9024, 0)
	P009 = App.Vector(29.8704, -18.2667, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(17.8356, -8.1683, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(17.6568, -6.1238, 0)
	P012 = App.Vector(19.7013, -5.9449, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(31.1695, -15.5679, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(31.8052, -15.5123, 0)
	P015 = App.Vector(31.7495, -14.8766, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(19.9951, -5.0135, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(19.8162, -2.9690, 0)
	P018 = App.Vector(21.8607, -2.7901, 0)
	S011 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(32.6990, -11.8845, 0)
	S012 = Part.LineSegment(P018, P019)
	P020 = App.Vector(33.3346, -11.8289, 0)
	P021 = App.Vector(33.2790, -11.1932, 0)
	S013 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(27.1052, -6.0127, 0)
	S014 = Part.LineSegment(P021, P022)
	P023 = App.Vector(26.9263, -3.9682, 0)
	P024 = App.Vector(28.9708, -3.7894, 0)
	S015 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(33.8384, -7.8737, 0)
	S016 = Part.LineSegment(P024, P025)
	P026 = App.Vector(34.4740, -7.8181, 0)
	P027 = App.Vector(34.4184, -7.1824, 0)
	S017 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(34.2153, -7.0120, 0)
	S018 = Part.LineSegment(P027, P028)
	P029 = App.Vector(33.8224, -5.3100, 0)
	P030 = App.Vector(35.3501, -4.4632, 0)
	S019 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(36.6794, -4.6500, 0)
	S020 = Part.LineSegment(P030, P031)
	P032 = App.Vector(37.4364, -4.4460, 0)
	P033 = App.Vector(37.8137, -3.7587, 0)
	S021 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(37.1696, 7.9006, 0)
	P035 = App.Vector(33.0157, 18.8139, 0)
	S022 = Part.Arc(P033, P034, P035)
	P036 = App.Vector(32.3915, 19.2884, 0)
	P037 = App.Vector(31.6169, 19.1669, 0)
	S023 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(30.4786, 18.4555, 0)
	S024 = Part.LineSegment(P037, P038)
	P039 = App.Vector(30.2840, 17.9485, 0)
	P040 = App.Vector(30.7177, 17.6217, 0)
	S025 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(30.9828, 17.6217, 0)
	S026 = Part.LineSegment(P040, P041)
	P042 = App.Vector(32.4340, 16.1705, 0)
	P043 = App.Vector(30.9828, 14.7193, 0)
	S027 = Part.Arc(P041, P042, P043)
	P044 = App.Vector(24.6287, 14.7193, 0)
	S028 = Part.LineSegment(P043, P044)
	P045 = App.Vector(24.1775, 14.2681, 0)
	P046 = App.Vector(24.6287, 13.8169, 0)
	S029 = Part.Arc(P044, P045, P046)
	P047 = App.Vector(32.6880, 13.8169, 0)
	S030 = Part.LineSegment(P046, P047)
	P048 = App.Vector(34.1393, 12.3657, 0)
	P049 = App.Vector(32.6880, 10.9145, 0)
	S031 = Part.Arc(P047, P048, P049)
	P050 = App.Vector(18.5397, 10.9145, 0)
	S032 = Part.LineSegment(P049, P050)
	P051 = App.Vector(18.0885, 10.4633, 0)
	P052 = App.Vector(18.5397, 10.0121, 0)
	S033 = Part.Arc(P050, P051, P052)
	P053 = App.Vector(33.8841, 10.0121, 0)
	S034 = Part.LineSegment(P052, P053)
	P054 = App.Vector(35.3353, 8.5608, 0)
	P055 = App.Vector(33.8841, 7.1096, 0)
	S035 = Part.Arc(P053, P054, P055)
	P056 = App.Vector(18.9134, 7.1096, 0)
	S036 = Part.LineSegment(P055, P056)
	P057 = App.Vector(18.4622, 6.6584, 0)
	P058 = App.Vector(18.9134, 6.2072, 0)
	S037 = Part.Arc(P056, P057, P058)
	P059 = App.Vector(34.6237, 6.2072, 0)
	S038 = Part.LineSegment(P058, P059)
	P060 = App.Vector(36.0749, 4.7560, 0)
	P061 = App.Vector(34.6237, 3.3048, 0)
	S039 = Part.Arc(P059, P060, P061)
	P062 = App.Vector(19.8471, 3.3048, 0)
	S040 = Part.LineSegment(P061, P062)
	P063 = App.Vector(19.3959, 2.8536, 0)
	P064 = App.Vector(19.8471, 2.4024, 0)
	S041 = Part.Arc(P062, P063, P064)
	P065 = App.Vector(34.9358, 2.4024, 0)
	S042 = Part.LineSegment(P064, P065)
	P066 = App.Vector(36.3871, 0.9512, 0)
	P067 = App.Vector(34.9358, -0.5000, 0)
	S043 = Part.Arc(P065, P066, P067)
	P068 = App.Vector(17.9374, -0.5000, 0)
	S044 = Part.LineSegment(P067, P068)
	P069 = App.Vector(17.2604, -0.7640, 0)
	P070 = App.Vector(16.9409, -1.4167, 0)
	S045 = Part.Arc(P068, P069, P070)
	P071 = App.Vector(15.9748, -5.8143, 0)
	P072 = App.Vector(13.8881, -9.8042, 0)
	S046 = Part.Arc(P070, P071, P072)
	P073 = App.Vector(13.7133, -10.5095, 0)
	P074 = App.Vector(14.0622, -11.1469, 0)
	S047 = Part.Arc(P072, P073, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_springTorqueB_faceProfile_Fa0():
	FC000 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr0()
	FC001 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr1()
	FC002 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr2()
	FC003 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr3()
	FC004 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr4()
	FC005 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr5()
	FC006 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr6()
	FC007 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr7()
	FC008 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr8()
	FC009 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr9()
	FC010 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr10()
	FC011 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr11()
	FC012 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr12()
	FC013 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr13()
	FC014 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr14()
	FC015 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr15()
	FC016 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr16()
	FC017 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr17()
	FC018 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr18()
	FC019 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr19()
	FC020 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr20()
	FC021 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr21()
	FC022 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr22()
	FC023 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr23()
	FC024 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr24()
	FC025 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr25()
	FC026 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr26()
	FC027 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr27()
	FC028 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr28()
	FC029 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr29()
	FC030 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr30()
	FC031 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr31()
	FC032 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr32()
	FC033 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr33()
	FC034 = ctr_face_springTorqueB_faceProfile_Fa0_Ctr34()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008, FC009, FC010, FC011, FC012, FC013, FC014, FC015, FC016, FC017, FC018, FC019, FC020, FC021, FC022, FC023, FC024, FC025, FC026, FC027, FC028, FC029, FC030, FC031, FC032, FC033, FC034])
	rOneFace.check()
	return rOneFace

def springTorqueB_faceProfile():
	FA000 = face_springTorqueB_faceProfile_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_springTorqueB_profile():
	FIG = springTorqueB_faceProfile()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_springTorqueB_profile = fex_subpax_springTorqueB_profile()

pax_springTorqueB = subpax_springTorqueB_profile

pax_springTorqueB.check()
#pax_springTorqueB.exportBrep(f"{outFileName}.brep")
#pax_springTorqueB.exportIges(f"{outFileName}.igs")
#pax_springTorqueB.exportStep(f"{outFileName}.stp")
pax_springTorqueB.exportStl(f"{outFileName}.stl")

