# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "door1arc"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_door1arc_faceDoor_Fa0_Ctr0():
	P000 = App.Vector(1500.0000, 1000.0000, 0)
	P001 = App.Vector(1900.0000, 1000.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1884.3155, 1189.2838, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1489.7710, 1123.4459, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1500.0000, 1000.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa0():
	FC000 = ctr_face_door1arc_faceDoor_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa1_Ctr0():
	P000 = App.Vector(1489.7710, 1123.4459, 0)
	P001 = App.Vector(1884.3155, 1189.2838, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1837.6898, 1373.4044, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1459.3629, 1243.5246, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1489.7710, 1123.4459, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa1():
	FC000 = ctr_face_door1arc_faceDoor_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa2_Ctr0():
	P000 = App.Vector(1459.3629, 1243.5246, 0)
	P001 = App.Vector(1837.6898, 1373.4044, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1761.3948, 1547.3395, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1409.6053, 1356.9605, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1459.3629, 1243.5246, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa2():
	FC000 = ctr_face_door1arc_faceDoor_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa3_Ctr0():
	P000 = App.Vector(1409.6053, 1356.9605, 0)
	P001 = App.Vector(1761.3948, 1547.3395, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1657.5116, 1706.3446, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1341.8554, 1460.6595, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1409.6053, 1356.9605, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa3():
	FC000 = ctr_face_door1arc_faceDoor_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa4_Ctr0():
	P000 = App.Vector(1341.8554, 1460.6595, 0)
	P001 = App.Vector(1657.5116, 1706.3446, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1528.8738, 1846.0825, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1257.9612, 1551.7929, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1341.8554, 1460.6595, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa4():
	FC000 = ctr_face_door1arc_faceDoor_Fa4_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa5_Ctr0():
	P000 = App.Vector(1257.9612, 1551.7929, 0)
	P001 = App.Vector(1528.8738, 1846.0825, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1378.9904, 1962.7415, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1160.2111, 1627.8749, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1257.9612, 1551.7929, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa5():
	FC000 = ctr_face_door1arc_faceDoor_Fa5_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa6_Ctr0():
	P000 = App.Vector(1160.2111, 1627.8749, 0)
	P001 = App.Vector(1378.9904, 1962.7415, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1211.9497, 2053.1393, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1051.2716, 1686.8300, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1160.2111, 1627.8749, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa6():
	FC000 = ctr_face_door1arc_faceDoor_Fa6_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa7_Ctr0():
	P000 = App.Vector(1051.2716, 1686.8300, 0)
	P001 = App.Vector(1211.9497, 2053.1393, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1032.3083, 2114.8103, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(934.1141, 1727.0502, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1051.2716, 1686.8300, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa7():
	FC000 = ctr_face_door1arc_faceDoor_Fa7_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa8_Ctr0():
	P000 = App.Vector(934.1141, 1727.0502, 0)
	P001 = App.Vector(1032.3083, 2114.8103, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(844.9662, 2146.0722, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(811.9345, 1747.4384, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(934.1141, 1727.0502, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa8():
	FC000 = ctr_face_door1arc_faceDoor_Fa8_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa9_Ctr0():
	P000 = App.Vector(811.9345, 1747.4384, 0)
	P001 = App.Vector(844.9662, 2146.0722, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(655.0338, 2146.0722, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(688.0655, 1747.4384, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(811.9345, 1747.4384, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa9():
	FC000 = ctr_face_door1arc_faceDoor_Fa9_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa10_Ctr0():
	P000 = App.Vector(688.0655, 1747.4384, 0)
	P001 = App.Vector(655.0338, 2146.0722, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(467.6917, 2114.8103, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(565.8859, 1727.0502, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(688.0655, 1747.4384, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa10():
	FC000 = ctr_face_door1arc_faceDoor_Fa10_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa11_Ctr0():
	P000 = App.Vector(565.8859, 1727.0502, 0)
	P001 = App.Vector(467.6917, 2114.8103, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(288.0503, 2053.1393, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(448.7284, 1686.8300, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(565.8859, 1727.0502, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa11():
	FC000 = ctr_face_door1arc_faceDoor_Fa11_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa12_Ctr0():
	P000 = App.Vector(448.7284, 1686.8300, 0)
	P001 = App.Vector(288.0503, 2053.1393, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(121.0096, 1962.7415, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(339.7889, 1627.8749, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(448.7284, 1686.8300, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa12():
	FC000 = ctr_face_door1arc_faceDoor_Fa12_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa13_Ctr0():
	P000 = App.Vector(339.7889, 1627.8749, 0)
	P001 = App.Vector(121.0096, 1962.7415, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-28.8738, 1846.0825, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(242.0388, 1551.7929, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(339.7889, 1627.8749, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa13():
	FC000 = ctr_face_door1arc_faceDoor_Fa13_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa14_Ctr0():
	P000 = App.Vector(242.0388, 1551.7929, 0)
	P001 = App.Vector(-28.8738, 1846.0825, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-157.5116, 1706.3446, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(158.1446, 1460.6595, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(242.0388, 1551.7929, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa14():
	FC000 = ctr_face_door1arc_faceDoor_Fa14_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa15_Ctr0():
	P000 = App.Vector(158.1446, 1460.6595, 0)
	P001 = App.Vector(-157.5116, 1706.3446, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-261.3948, 1547.3395, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(90.3947, 1356.9605, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(158.1446, 1460.6595, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa15():
	FC000 = ctr_face_door1arc_faceDoor_Fa15_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa16_Ctr0():
	P000 = App.Vector(90.3947, 1356.9605, 0)
	P001 = App.Vector(-261.3948, 1547.3395, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-337.6898, 1373.4044, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(40.6371, 1243.5246, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(90.3947, 1356.9605, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa16():
	FC000 = ctr_face_door1arc_faceDoor_Fa16_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa17_Ctr0():
	P000 = App.Vector(40.6371, 1243.5246, 0)
	P001 = App.Vector(-337.6898, 1373.4044, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-384.3155, 1189.2838, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(10.2290, 1123.4459, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(40.6371, 1243.5246, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa17():
	FC000 = ctr_face_door1arc_faceDoor_Fa17_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa18_Ctr0():
	P000 = App.Vector(10.2290, 1123.4459, 0)
	P001 = App.Vector(-384.3155, 1189.2838, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-400.0000, 1000.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 1000.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(10.2290, 1123.4459, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa18():
	FC000 = ctr_face_door1arc_faceDoor_Fa18_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa19_Ctr0():
	P000 = App.Vector(-399.8000, 0.2000, 0)
	P001 = App.Vector(-0.2000, 0.2000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-0.2000, 199.8000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-399.8000, 199.8000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-399.8000, 0.2000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa19():
	FC000 = ctr_face_door1arc_faceDoor_Fa19_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa20_Ctr0():
	P000 = App.Vector(1500.2000, 0.2000, 0)
	P001 = App.Vector(1899.8000, 0.2000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1899.8000, 199.8000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1500.2000, 199.8000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1500.2000, 0.2000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa20():
	FC000 = ctr_face_door1arc_faceDoor_Fa20_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa21_Ctr0():
	P000 = App.Vector(-199.8000, 200.2000, 0)
	P001 = App.Vector(-0.2000, 200.2000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-0.2000, 399.8000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-199.8000, 399.8000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-199.8000, 200.2000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa21():
	FC000 = ctr_face_door1arc_faceDoor_Fa21_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa22_Ctr0():
	P000 = App.Vector(1500.2000, 200.2000, 0)
	P001 = App.Vector(1699.8000, 200.2000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1699.8000, 399.8000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1500.2000, 399.8000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1500.2000, 200.2000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa22():
	FC000 = ctr_face_door1arc_faceDoor_Fa22_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa23_Ctr0():
	P000 = App.Vector(-399.8000, 400.2000, 0)
	P001 = App.Vector(-0.2000, 400.2000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-0.2000, 599.8000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-399.8000, 599.8000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-399.8000, 400.2000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa23():
	FC000 = ctr_face_door1arc_faceDoor_Fa23_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa24_Ctr0():
	P000 = App.Vector(1500.2000, 400.2000, 0)
	P001 = App.Vector(1899.8000, 400.2000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1899.8000, 599.8000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1500.2000, 599.8000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1500.2000, 400.2000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa24():
	FC000 = ctr_face_door1arc_faceDoor_Fa24_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa25_Ctr0():
	P000 = App.Vector(-199.8000, 600.2000, 0)
	P001 = App.Vector(-0.2000, 600.2000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-0.2000, 799.8000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-199.8000, 799.8000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-199.8000, 600.2000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa25():
	FC000 = ctr_face_door1arc_faceDoor_Fa25_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa26_Ctr0():
	P000 = App.Vector(1500.2000, 600.2000, 0)
	P001 = App.Vector(1699.8000, 600.2000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1699.8000, 799.8000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1500.2000, 799.8000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1500.2000, 600.2000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa26():
	FC000 = ctr_face_door1arc_faceDoor_Fa26_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa27_Ctr0():
	P000 = App.Vector(-399.8000, 800.2000, 0)
	P001 = App.Vector(-0.2000, 800.2000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-0.2000, 999.8000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-399.8000, 999.8000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-399.8000, 800.2000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa27():
	FC000 = ctr_face_door1arc_faceDoor_Fa27_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa28_Ctr0():
	P000 = App.Vector(1500.2000, 800.2000, 0)
	P001 = App.Vector(1899.8000, 800.2000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1899.8000, 999.8000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1500.2000, 999.8000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1500.2000, 800.2000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa28():
	FC000 = ctr_face_door1arc_faceDoor_Fa28_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa29_Ctr0():
	P000 = App.Vector(-199.8000, -199.8000, 0)
	P001 = App.Vector(149.8000, -199.8000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(149.8000, -0.2000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-199.8000, -0.2000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-199.8000, -199.8000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa29():
	FC000 = ctr_face_door1arc_faceDoor_Fa29_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa30_Ctr0():
	P000 = App.Vector(150.2000, -199.8000, 0)
	P001 = App.Vector(549.8000, -199.8000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(549.8000, -0.2000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(150.2000, -0.2000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(150.2000, -199.8000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa30():
	FC000 = ctr_face_door1arc_faceDoor_Fa30_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa31_Ctr0():
	P000 = App.Vector(550.2000, -199.8000, 0)
	P001 = App.Vector(949.8000, -199.8000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(949.8000, -0.2000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(550.2000, -0.2000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(550.2000, -199.8000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa31():
	FC000 = ctr_face_door1arc_faceDoor_Fa31_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa32_Ctr0():
	P000 = App.Vector(950.2000, -199.8000, 0)
	P001 = App.Vector(1349.8000, -199.8000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1349.8000, -0.2000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(950.2000, -0.2000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(950.2000, -199.8000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa32():
	FC000 = ctr_face_door1arc_faceDoor_Fa32_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door1arc_faceDoor_Fa33_Ctr0():
	P000 = App.Vector(1350.2000, -199.8000, 0)
	P001 = App.Vector(1699.8000, -199.8000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1699.8000, -0.2000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1350.2000, -0.2000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1350.2000, -199.8000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door1arc_faceDoor_Fa33():
	FC000 = ctr_face_door1arc_faceDoor_Fa33_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def door1arc_faceDoor():
	FA000 = face_door1arc_faceDoor_Fa0()
	FA001 = face_door1arc_faceDoor_Fa1()
	FA002 = face_door1arc_faceDoor_Fa2()
	FA003 = face_door1arc_faceDoor_Fa3()
	FA004 = face_door1arc_faceDoor_Fa4()
	FA005 = face_door1arc_faceDoor_Fa5()
	FA006 = face_door1arc_faceDoor_Fa6()
	FA007 = face_door1arc_faceDoor_Fa7()
	FA008 = face_door1arc_faceDoor_Fa8()
	FA009 = face_door1arc_faceDoor_Fa9()
	FA010 = face_door1arc_faceDoor_Fa10()
	FA011 = face_door1arc_faceDoor_Fa11()
	FA012 = face_door1arc_faceDoor_Fa12()
	FA013 = face_door1arc_faceDoor_Fa13()
	FA014 = face_door1arc_faceDoor_Fa14()
	FA015 = face_door1arc_faceDoor_Fa15()
	FA016 = face_door1arc_faceDoor_Fa16()
	FA017 = face_door1arc_faceDoor_Fa17()
	FA018 = face_door1arc_faceDoor_Fa18()
	FA019 = face_door1arc_faceDoor_Fa19()
	FA020 = face_door1arc_faceDoor_Fa20()
	FA021 = face_door1arc_faceDoor_Fa21()
	FA022 = face_door1arc_faceDoor_Fa22()
	FA023 = face_door1arc_faceDoor_Fa23()
	FA024 = face_door1arc_faceDoor_Fa24()
	FA025 = face_door1arc_faceDoor_Fa25()
	FA026 = face_door1arc_faceDoor_Fa26()
	FA027 = face_door1arc_faceDoor_Fa27()
	FA028 = face_door1arc_faceDoor_Fa28()
	FA029 = face_door1arc_faceDoor_Fa29()
	FA030 = face_door1arc_faceDoor_Fa30()
	FA031 = face_door1arc_faceDoor_Fa31()
	FA032 = face_door1arc_faceDoor_Fa32()
	FA033 = face_door1arc_faceDoor_Fa33()
	rOneFig = FA000.fuse([FA001, FA002, FA003, FA004, FA005, FA006, FA007, FA008, FA009, FA010, FA011, FA012, FA013, FA014, FA015, FA016, FA017, FA018, FA019, FA020, FA021, FA022, FA023, FA024, FA025, FA026, FA027, FA028, FA029, FA030, FA031, FA032, FA033])
	rOneFig.check()
	return rOneFig

def fex_subpax_door1arc_top():
	FIG = door1arc_faceDoor()
	VEX = FIG.extrude(App.Vector(0, 0, 200))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_door1arc_top = fex_subpax_door1arc_top()

pax_door1arc = subpax_door1arc_top

pax_door1arc.check()
#pax_door1arc.exportBrep(f"{outFileName}.brep")
#pax_door1arc.exportIges(f"{outFileName}.igs")
#pax_door1arc.exportStep(f"{outFileName}.stp")
pax_door1arc.exportStl(f"{outFileName}.stl")

