# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "springTorqueC"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(42.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr1():
	P000 = App.Vector(8.8273, -0.0000, 0)
	P001 = App.Vector(10.9717, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(11.7472, 0.3686, 0)
	P003 = App.Vector(11.9509, 1.2028, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(11.4457, 3.6424, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(10.9274, 4.3270, 0)
	P006 = App.Vector(10.0693, 4.3574, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(8.1013, 3.5057, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(7.4251, 3.4632, 0)
	P009 = App.Vector(6.8770, 3.8614, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(6.1219, 4.9726, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(5.9534, 5.6288, 0)
	P012 = App.Vector(6.2418, 6.2418, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(7.7582, 7.7582, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(8.0458, 8.5672, 0)
	P015 = App.Vector(7.6001, 9.3011, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(5.5177, 10.6689, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(4.6672, 10.7866, 0)
	P018 = App.Vector(4.0389, 10.2012, 0)
	S011 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(3.2495, 8.2074, 0)
	S012 = Part.LineSegment(P018, P019)
	P020 = App.Vector(2.8015, 7.6992, 0)
	P021 = App.Vector(2.1324, 7.5932, 0)
	S013 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(0.8126, 7.8450, 0)
	S014 = Part.LineSegment(P021, P022)
	P023 = App.Vector(0.2295, 8.1898, 0)
	P024 = App.Vector(0.0000, 8.8273, 0)
	S015 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(0.0000, 10.9717, 0)
	S016 = Part.LineSegment(P024, P025)
	P026 = App.Vector(-0.3686, 11.7472, 0)
	P027 = App.Vector(-1.2028, 11.9509, 0)
	S017 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(-3.6424, 11.4457, 0)
	S018 = Part.LineSegment(P027, P028)
	P029 = App.Vector(-4.3270, 10.9274, 0)
	P030 = App.Vector(-4.3574, 10.0693, 0)
	S019 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(-3.5057, 8.1013, 0)
	S020 = Part.LineSegment(P030, P031)
	P032 = App.Vector(-3.4632, 7.4251, 0)
	P033 = App.Vector(-3.8614, 6.8770, 0)
	S021 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(-4.9726, 6.1219, 0)
	S022 = Part.LineSegment(P033, P034)
	P035 = App.Vector(-5.6288, 5.9534, 0)
	P036 = App.Vector(-6.2418, 6.2418, 0)
	S023 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-7.7582, 7.7582, 0)
	S024 = Part.LineSegment(P036, P037)
	P038 = App.Vector(-8.5672, 8.0458, 0)
	P039 = App.Vector(-9.3011, 7.6001, 0)
	S025 = Part.Arc(P037, P038, P039)
	P040 = App.Vector(-10.6689, 5.5177, 0)
	S026 = Part.LineSegment(P039, P040)
	P041 = App.Vector(-10.7866, 4.6672, 0)
	P042 = App.Vector(-10.2012, 4.0389, 0)
	S027 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(-8.2074, 3.2495, 0)
	S028 = Part.LineSegment(P042, P043)
	P044 = App.Vector(-7.6992, 2.8015, 0)
	P045 = App.Vector(-7.5932, 2.1324, 0)
	S029 = Part.Arc(P043, P044, P045)
	P046 = App.Vector(-7.8450, 0.8126, 0)
	S030 = Part.LineSegment(P045, P046)
	P047 = App.Vector(-8.1898, 0.2295, 0)
	P048 = App.Vector(-8.8273, 0.0000, 0)
	S031 = Part.Arc(P046, P047, P048)
	P049 = App.Vector(-10.9717, 0.0000, 0)
	S032 = Part.LineSegment(P048, P049)
	P050 = App.Vector(-11.7472, -0.3686, 0)
	P051 = App.Vector(-11.9509, -1.2028, 0)
	S033 = Part.Arc(P049, P050, P051)
	P052 = App.Vector(-11.4457, -3.6424, 0)
	S034 = Part.LineSegment(P051, P052)
	P053 = App.Vector(-10.9274, -4.3270, 0)
	P054 = App.Vector(-10.0693, -4.3574, 0)
	S035 = Part.Arc(P052, P053, P054)
	P055 = App.Vector(-8.1013, -3.5057, 0)
	S036 = Part.LineSegment(P054, P055)
	P056 = App.Vector(-7.4251, -3.4632, 0)
	P057 = App.Vector(-6.8770, -3.8614, 0)
	S037 = Part.Arc(P055, P056, P057)
	P058 = App.Vector(-6.1219, -4.9726, 0)
	S038 = Part.LineSegment(P057, P058)
	P059 = App.Vector(-5.9534, -5.6288, 0)
	P060 = App.Vector(-6.2418, -6.2418, 0)
	S039 = Part.Arc(P058, P059, P060)
	P061 = App.Vector(-7.7582, -7.7582, 0)
	S040 = Part.LineSegment(P060, P061)
	P062 = App.Vector(-8.0458, -8.5672, 0)
	P063 = App.Vector(-7.6001, -9.3011, 0)
	S041 = Part.Arc(P061, P062, P063)
	P064 = App.Vector(-5.5177, -10.6689, 0)
	S042 = Part.LineSegment(P063, P064)
	P065 = App.Vector(-4.6672, -10.7866, 0)
	P066 = App.Vector(-4.0389, -10.2012, 0)
	S043 = Part.Arc(P064, P065, P066)
	P067 = App.Vector(-3.2495, -8.2074, 0)
	S044 = Part.LineSegment(P066, P067)
	P068 = App.Vector(-2.8015, -7.6992, 0)
	P069 = App.Vector(-2.1324, -7.5932, 0)
	S045 = Part.Arc(P067, P068, P069)
	P070 = App.Vector(-0.8126, -7.8450, 0)
	S046 = Part.LineSegment(P069, P070)
	P071 = App.Vector(-0.2295, -8.1898, 0)
	P072 = App.Vector(-0.0000, -8.8273, 0)
	S047 = Part.Arc(P070, P071, P072)
	P073 = App.Vector(-0.0000, -10.9717, 0)
	S048 = Part.LineSegment(P072, P073)
	P074 = App.Vector(0.3686, -11.7472, 0)
	P075 = App.Vector(1.2028, -11.9509, 0)
	S049 = Part.Arc(P073, P074, P075)
	P076 = App.Vector(3.6424, -11.4457, 0)
	S050 = Part.LineSegment(P075, P076)
	P077 = App.Vector(4.3270, -10.9274, 0)
	P078 = App.Vector(4.3574, -10.0693, 0)
	S051 = Part.Arc(P076, P077, P078)
	P079 = App.Vector(3.5057, -8.1013, 0)
	S052 = Part.LineSegment(P078, P079)
	P080 = App.Vector(3.4632, -7.4251, 0)
	P081 = App.Vector(3.8614, -6.8770, 0)
	S053 = Part.Arc(P079, P080, P081)
	P082 = App.Vector(4.9726, -6.1219, 0)
	S054 = Part.LineSegment(P081, P082)
	P083 = App.Vector(5.6288, -5.9534, 0)
	P084 = App.Vector(6.2418, -6.2418, 0)
	S055 = Part.Arc(P082, P083, P084)
	P085 = App.Vector(7.7582, -7.7582, 0)
	S056 = Part.LineSegment(P084, P085)
	P086 = App.Vector(8.5672, -8.0458, 0)
	P087 = App.Vector(9.3011, -7.6001, 0)
	S057 = Part.Arc(P085, P086, P087)
	P088 = App.Vector(10.6689, -5.5177, 0)
	S058 = Part.LineSegment(P087, P088)
	P089 = App.Vector(10.7866, -4.6672, 0)
	P090 = App.Vector(10.2012, -4.0389, 0)
	S059 = Part.Arc(P088, P089, P090)
	P091 = App.Vector(8.2074, -3.2495, 0)
	S060 = Part.LineSegment(P090, P091)
	P092 = App.Vector(7.6992, -2.8015, 0)
	P093 = App.Vector(7.5932, -2.1324, 0)
	S061 = Part.Arc(P091, P092, P093)
	P094 = App.Vector(7.8450, -0.8126, 0)
	S062 = Part.LineSegment(P093, P094)
	P095 = App.Vector(8.1898, -0.2295, 0)
	P096 = App.Vector(8.8273, -0.0000, 0)
	S063 = Part.Arc(P094, P095, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047, S048, S049, S050, S051, S052, S053, S054, S055, S056, S057, S058, S059, S060, S061, S062, S063])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(15.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(10.6066, 10.6066, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(0.0000, 15.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-10.6066, 10.6066, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-15.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-10.6066, -10.6066, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-0.0000, -15.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr9():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(10.6066, -10.6066, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr10():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(40.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr11():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(36.9552, 15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr12():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(28.2843, 28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr13():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(15.3073, 36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr14():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(0.0000, 40.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr15():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-15.3073, 36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr16():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-28.2843, 28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr17():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-36.9552, 15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr18():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-40.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr19():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-36.9552, -15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr20():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-28.2843, -28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr21():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-15.3073, -36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr22():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-0.0000, -40.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr23():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(15.3073, -36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr24():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(28.2843, -28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr25():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(36.9552, -15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr26():
	P000 = App.Vector(17.0895, 0.5000, 0)
	P001 = App.Vector(18.8936, 0.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(20.6351, 1.2976, 0)
	P003 = App.Vector(21.1688, 3.1372, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(19.4012, 9.0306, 0)
	P005 = App.Vector(16.0299, 14.1775, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(16.3155, 18.8357, 0)
	P007 = App.Vector(20.9737, 18.5500, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(25.6978, 11.1186, 0)
	P009 = App.Vector(27.8802, 2.5875, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(30.3829, 0.5098, 0)
	P011 = App.Vector(32.4605, 3.0125, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(29.6849, 13.4747, 0)
	P013 = App.Vector(23.6367, 22.4514, 0)
	S006 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(22.7297, 24.6801, 0)
	P015 = App.Vector(23.5770, 26.9322, 0)
	S007 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(24.3659, 27.8083, 0)
	S008 = Part.LineSegment(P015, P016)
	P017 = App.Vector(24.6201, 28.5500, 0)
	P018 = App.Vector(24.2612, 29.2471, 0)
	S009 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(22.3358, 30.7426, 0)
	P020 = App.Vector(20.3185, 32.1116, 0)
	S010 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(19.5446, 32.2376, 0)
	P022 = App.Vector(18.9178, 31.7666, 0)
	S011 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(18.3283, 30.7456, 0)
	S012 = Part.LineSegment(P022, P023)
	P024 = App.Vector(16.4483, 29.2438, 0)
	P025 = App.Vector(14.0484, 29.4177, 0)
	S013 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(3.6421, 32.3959, 0)
	P027 = App.Vector(-7.1658, 31.8027, 0)
	S014 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(-8.9039, 29.0534, 0)
	P029 = App.Vector(-6.1546, 27.3152, 0)
	S015 = Part.Arc(P027, P028, P029)
	P030 = App.Vector(2.6334, 27.8759, 0)
	P031 = App.Vector(11.1609, 25.6794, 0)
	S016 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(12.8720, 21.3375, 0)
	P033 = App.Vector(8.5301, 19.6264, 0)
	S017 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(2.5933, 21.2423, 0)
	P035 = App.Vector(-3.5579, 21.1022, 0)
	S018 = Part.Arc(P033, P034, P035)
	P036 = App.Vector(-5.1425, 20.0261, 0)
	P037 = App.Vector(-5.3629, 18.1234, 0)
	S019 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(-4.8054, 16.4076, 0)
	S020 = Part.LineSegment(P037, P038)
	P039 = App.Vector(-4.7573, 16.3502, 0)
	P040 = App.Vector(-4.6828, 16.3423, 0)
	S021 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(9.9923, 13.7533, 0)
	P042 = App.Vector(16.9895, 0.5965, 0)
	S022 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(17.0200, 0.5281, 0)
	P044 = App.Vector(17.0895, 0.5000, 0)
	S023 = Part.Arc(P042, P043, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr27():
	P000 = App.Vector(-5.7565, 16.0985, 0)
	P001 = App.Vector(-6.3140, 17.8144, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-5.9978, 20.5444, 0)
	P003 = App.Vector(-3.7241, 22.0882, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(2.7145, 22.2349, 0)
	P005 = App.Vector(8.9287, 20.5436, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(11.9549, 21.7362, 0)
	P007 = App.Vector(10.7623, 24.7623, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(2.5393, 26.8803, 0)
	P009 = App.Vector(-5.9348, 26.3397, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-9.8795, 28.8336, 0)
	P011 = App.Vector(-7.3856, 32.7782, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(3.7538, 33.3897, 0)
	P013 = App.Vector(14.4793, 30.3201, 0)
	S006 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(16.1520, 30.1989, 0)
	P015 = App.Vector(17.4623, 31.2456, 0)
	S007 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(18.0518, 32.2666, 0)
	S008 = Part.LineSegment(P015, P016)
	P017 = App.Vector(18.1462, 33.0449, 0)
	P018 = App.Vector(17.6502, 33.6522, 0)
	S009 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(-15.4560, 34.7147, 0)
	P020 = App.Vector(-36.8188, 9.4010, 0)
	S010 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(-36.6994, 8.6261, 0)
	P022 = App.Vector(-36.0578, 8.1755, 0)
	S011 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-34.9046, 7.9304, 0)
	S012 = Part.LineSegment(P022, P023)
	P024 = App.Vector(-33.2499, 8.2037, 0)
	P025 = App.Vector(-32.2208, 9.5279, 0)
	S013 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(-27.3251, 19.5524, 0)
	P027 = App.Vector(-19.4171, 27.4215, 0)
	S014 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(-14.8169, 26.6353, 0)
	P029 = App.Vector(-15.6030, 22.0351, 0)
	S015 = Part.Arc(P027, P028, P029)
	P030 = App.Vector(-21.6751, 16.0994, 0)
	P031 = App.Vector(-25.6034, 8.5713, 0)
	S016 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(-24.1525, 5.6601, 0)
	P033 = App.Vector(-21.2413, 7.1110, 0)
	S017 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(-18.3401, 12.8608, 0)
	P035 = App.Vector(-13.9228, 17.5475, 0)
	S018 = Part.Arc(P033, P034, P035)
	P036 = App.Vector(-11.2542, 18.2041, 0)
	P037 = App.Vector(-9.0138, 16.6124, 0)
	S019 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(-8.1117, 15.0499, 0)
	S020 = Part.LineSegment(P037, P038)
	P039 = App.Vector(-8.0527, 15.0038, 0)
	P040 = App.Vector(-7.9782, 15.0116, 0)
	S021 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(-6.9145, 15.5303, 0)
	P042 = App.Vector(-5.8174, 15.9737, 0)
	S022 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(-5.7617, 16.0238, 0)
	P044 = App.Vector(-5.7565, 16.0985, 0)
	S023 = Part.Arc(P042, P043, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr28():
	P000 = App.Vector(-8.9777, 14.5499, 0)
	P001 = App.Vector(-9.8798, 16.1124, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-11.4413, 17.2218, 0)
	P003 = App.Vector(-13.3013, 16.7641, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-17.5214, 12.2867, 0)
	P005 = App.Vector(-20.2931, 6.7935, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(-24.4700, 4.7118, 0)
	P007 = App.Vector(-26.5517, 8.8887, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(-22.4779, 16.6956, 0)
	P009 = App.Vector(-16.1809, 22.8512, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-15.6330, 26.0574, 0)
	P011 = App.Vector(-18.8392, 26.6054, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(-26.5119, 18.9705, 0)
	P013 = App.Vector(-31.2618, 9.2443, 0)
	S006 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(-32.7384, 7.3445, 0)
	P015 = App.Vector(-35.1125, 6.9522, 0)
	S007 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(-36.2657, 7.1973, 0)
	S008 = Part.LineSegment(P015, P016)
	P017 = App.Vector(-37.0351, 7.0466, 0)
	P018 = App.Vector(-37.4593, 6.3873, 0)
	S009 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(-37.7918, 3.9721, 0)
	P020 = App.Vector(-37.9688, 1.5405, 0)
	S010 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(-37.6909, 0.8074, 0)
	P022 = App.Vector(-36.9696, 0.5000, 0)
	S011 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-35.7906, 0.5000, 0)
	S012 = Part.LineSegment(P022, P023)
	P024 = App.Vector(-33.5500, -0.3773, 0)
	P025 = App.Vector(-32.5007, -2.5426, 0)
	S013 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(-29.8767, -13.0438, 0)
	P027 = App.Vector(-23.9591, -22.1071, 0)
	S014 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(-20.7090, -22.2377, 0)
	P029 = App.Vector(-20.5783, -18.9877, 0)
	S015 = Part.Arc(P027, P028, P029)
	P030 = App.Vector(-25.4579, -11.6574, 0)
	P031 = App.Vector(-27.8195, -3.1741, 0)
	S016 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(-24.9149, 0.4787, 0)
	P033 = App.Vector(-21.2621, -2.4259, 0)
	S017 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(-19.6930, -8.3753, 0)
	P035 = App.Vector(-16.4961, -13.6323, 0)
	S018 = Part.Arc(P033, P034, P035)
	P036 = App.Vector(-14.7719, -14.4666, 0)
	P037 = App.Vector(-13.0139, -13.7062, 0)
	S019 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(-11.8067, -12.3654, 0)
	S020 = Part.LineSegment(P037, P038)
	P039 = App.Vector(-11.7810, -12.2950, 0)
	P040 = App.Vector(-11.8115, -12.2266, 0)
	S021 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(-16.9069, 1.7770, 0)
	P042 = App.Vector(-9.0113, 14.4151, 0)
	S022 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(-8.9673, 14.4757, 0)
	P044 = App.Vector(-8.9777, 14.5499, 0)
	S023 = Part.Arc(P042, P043, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr29():
	P000 = App.Vector(-11.0635, -13.0345, 0)
	P001 = App.Vector(-12.2707, -14.3753, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-14.7931, -15.4664, 0)
	P003 = App.Vector(-17.2669, -14.2693, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-20.6132, -8.7666, 0)
	P005 = App.Vector(-22.2556, -2.5393, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(-24.8015, -0.5148, 0)
	P007 = App.Vector(-26.8260, -3.0607, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(-24.5487, -11.2410, 0)
	P009 = App.Vector(-19.8434, -18.3095, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-20.0309, -22.9727, 0)
	P011 = App.Vector(-24.6940, -22.7852, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(-30.7932, -13.4440, 0)
	P013 = App.Vector(-33.4976, -2.6206, 0)
	S006 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(-34.2290, -1.1114, 0)
	P015 = App.Vector(-35.7906, -0.5000, 0)
	S007 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(-36.9696, -0.5000, 0)
	S008 = Part.LineSegment(P015, P016)
	P017 = App.Vector(-37.6909, -0.8074, 0)
	P018 = App.Vector(-37.9688, -1.5405, 0)
	S009 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(-22.3358, -30.7426, 0)
	P020 = App.Vector(10.2679, -36.5865, 0)
	S010 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(10.8793, -36.0956, 0)
	P022 = App.Vector(10.9487, -35.3147, 0)
	S011 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(10.5844, -34.1934, 0)
	S012 = Part.LineSegment(P022, P023)
	P024 = App.Vector(9.5203, -32.8972, 0)
	P025 = App.Vector(7.8590, -32.6680, 0)
	S013 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(-3.2703, -33.4405, 0)
	P027 = App.Vector(-14.0391, -30.5264, 0)
	S014 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(-15.6584, -26.1494, 0)
	P029 = App.Vector(-11.2815, -24.5302, 0)
	S015 = Part.Arc(P027, P028, P029)
	P030 = App.Vector(-3.1049, -26.8209, 0)
	P031 = App.Vector(5.3788, -26.4588, 0)
	S016 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(7.1745, -23.7467, 0)
	P033 = App.Vector(4.4624, -21.9510, 0)
	S017 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(-1.9677, -22.3134, 0)
	P035 = App.Vector(-8.2352, -20.8313, 0)
	S018 = Part.Arc(P033, P034, P035)
	P036 = App.Vector(-10.1381, -18.8484, 0)
	P037 = App.Vector(-9.8798, -16.1124, 0)
	S019 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(-8.9777, -14.5499, 0)
	S020 = Part.LineSegment(P037, P038)
	P039 = App.Vector(-8.9673, -14.4757, 0)
	P040 = App.Vector(-9.0113, -14.4151, 0)
	S021 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(-9.9923, -13.7533, 0)
	P042 = App.Vector(-10.9249, -13.0248, 0)
	S022 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(-10.9962, -13.0017, 0)
	P044 = App.Vector(-11.0635, -13.0345, 0)
	S023 = Part.Arc(P042, P043, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr30():
	P000 = App.Vector(-8.1117, -15.0499, 0)
	P001 = App.Vector(-9.0138, -16.6124, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-9.1938, -18.5193, 0)
	P003 = App.Vector(-7.8675, -19.9013, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-1.8799, -21.3173, 0)
	P005 = App.Vector(4.2632, -20.9711, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(8.1544, -23.5475, 0)
	P007 = App.Vector(5.5780, -27.4388, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(-3.2199, -27.8142, 0)
	P009 = App.Vector(-11.6993, -25.4387, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-14.7499, -26.5673, 0)
	P011 = App.Vector(-13.6213, -29.6179, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(-3.1730, -32.4452, 0)
	P013 = App.Vector(7.6251, -31.6957, 0)
	S006 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(10.0087, -32.0246, 0)
	P015 = App.Vector(11.5354, -33.8844, 0)
	S007 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(11.8998, -35.0057, 0)
	S008 = Part.LineSegment(P015, P016)
	P017 = App.Vector(12.4150, -35.5967, 0)
	P018 = App.Vector(13.1981, -35.6344, 0)
	S009 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(15.4560, -34.7147, 0)
	P020 = App.Vector(17.6502, -33.6522, 0)
	S010 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(18.1462, -33.0449, 0)
	P022 = App.Vector(18.0518, -32.2666, 0)
	S011 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(17.4623, -31.2456, 0)
	S012 = Part.LineSegment(P022, P023)
	P024 = App.Vector(17.1017, -28.8666, 0)
	P025 = App.Vector(18.4523, -26.8751, 0)
	S013 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(26.2347, -19.3521, 0)
	P027 = App.Vector(31.1248, -9.6956, 0)
	S014 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(29.6129, -6.8157, 0)
	P029 = App.Vector(26.7330, -8.3275, 0)
	S015 = Part.Arc(P027, P028, P029)
	P030 = App.Vector(22.8245, -16.2185, 0)
	P031 = App.Vector(16.6586, -22.5054, 0)
	S016 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(12.0428, -21.8163, 0)
	P033 = App.Vector(12.7319, -17.2005, 0)
	S017 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(17.0997, -12.8670, 0)
	P035 = App.Vector(20.0540, -7.4699, 0)
	S018 = Part.Arc(P033, P034, P035)
	P036 = App.Vector(19.9144, -5.5595, 0)
	P037 = App.Vector(18.3768, -4.4173, 0)
	S019 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(16.6121, -4.0422, 0)
	S020 = Part.LineSegment(P037, P038)
	P039 = App.Vector(16.5383, -4.0552, 0)
	P040 = App.Vector(16.4943, -4.1158, 0)
	S021 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(6.9145, -15.5303, 0)
	P042 = App.Vector(-7.9782, -15.0116, 0)
	S022 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(-8.0527, -15.0038, 0)
	P044 = App.Vector(-8.1117, -15.0499, 0)
	S023 = Part.Arc(P042, P043, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr31():
	P000 = App.Vector(16.8200, -3.0640, 0)
	P001 = App.Vector(18.5847, -3.4391, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(20.7909, -5.0780, 0)
	P003 = App.Vector(20.9911, -7.8189, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(17.8988, -13.4683, 0)
	P005 = App.Vector(13.3269, -18.0043, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(12.8466, -21.2213, 0)
	P007 = App.Vector(16.0636, -21.7016, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(22.0094, -15.6393, 0)
	P009 = App.Vector(25.7782, -8.0301, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(29.9104, -5.8609, 0)
	P011 = App.Vector(32.0796, -9.9930, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(27.0394, -19.9457, 0)
	P013 = App.Vector(19.0183, -27.6995, 0)
	S006 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(18.0770, -29.0875, 0)
	P015 = App.Vector(18.3283, -30.7456, 0)
	S007 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(18.9178, -31.7666, 0)
	S008 = Part.LineSegment(P015, P016)
	P017 = App.Vector(19.5446, -32.2376, 0)
	P018 = App.Vector(20.3185, -32.1116, 0)
	S009 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(37.7918, -3.9721, 0)
	P020 = App.Vector(26.5509, 27.1855, 0)
	S010 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(25.8201, 27.4695, 0)
	P022 = App.Vector(25.1091, 27.1392, 0)
	S011 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(24.3202, 26.2631, 0)
	S012 = Part.LineSegment(P022, P023)
	P024 = App.Vector(23.7296, 24.6934, 0)
	P025 = App.Vector(24.3618, 23.1401, 0)
	S013 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(30.5955, 13.8880, 0)
	P027 = App.Vector(33.4562, 3.1050, 0)
	S014 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(30.4753, -0.4859, 0)
	P029 = App.Vector(26.8845, 2.4950, 0)
	S015 = Part.Arc(P027, P028, P029)
	P030 = App.Vector(24.7800, 10.7215, 0)
	P031 = App.Vector(20.2246, 17.8875, 0)
	S016 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(16.9780, 18.0866, 0)
	P033 = App.Vector(16.7790, 14.8400, 0)
	S017 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(20.3078, 9.4526, 0)
	P035 = App.Vector(22.1580, 3.2838, 0)
	S018 = Part.Arc(P033, P034, P035)
	P036 = App.Vector(21.3923, 0.6444, 0)
	P037 = App.Vector(18.8936, -0.5000, 0)
	S019 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(17.0895, -0.5000, 0)
	S020 = Part.LineSegment(P037, P038)
	P039 = App.Vector(17.0200, -0.5281, 0)
	P040 = App.Vector(16.9895, -0.5965, 0)
	S021 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(16.9069, -1.7770, 0)
	P042 = App.Vector(16.7423, -2.9489, 0)
	S022 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(16.7579, -3.0221, 0)
	P044 = App.Vector(16.8200, -3.0640, 0)
	S023 = Part.Arc(P042, P043, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_springTorqueC_faceProfile_Fa0():
	FC000 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr0()
	FC001 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr1()
	FC002 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr2()
	FC003 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr3()
	FC004 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr4()
	FC005 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr5()
	FC006 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr6()
	FC007 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr7()
	FC008 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr8()
	FC009 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr9()
	FC010 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr10()
	FC011 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr11()
	FC012 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr12()
	FC013 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr13()
	FC014 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr14()
	FC015 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr15()
	FC016 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr16()
	FC017 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr17()
	FC018 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr18()
	FC019 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr19()
	FC020 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr20()
	FC021 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr21()
	FC022 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr22()
	FC023 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr23()
	FC024 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr24()
	FC025 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr25()
	FC026 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr26()
	FC027 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr27()
	FC028 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr28()
	FC029 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr29()
	FC030 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr30()
	FC031 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr31()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008, FC009, FC010, FC011, FC012, FC013, FC014, FC015, FC016, FC017, FC018, FC019, FC020, FC021, FC022, FC023, FC024, FC025, FC026, FC027, FC028, FC029, FC030, FC031])
	rOneFace.check()
	return rOneFace

def springTorqueC_faceProfile():
	FA000 = face_springTorqueC_faceProfile_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_springTorqueC_profile():
	FIG = springTorqueC_faceProfile()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_springTorqueC_profile = fex_subpax_springTorqueC_profile()

pax_springTorqueC = subpax_springTorqueC_profile

pax_springTorqueC.check()
#pax_springTorqueC.exportBrep(f"{outFileName}.brep")
#pax_springTorqueC.exportIges(f"{outFileName}.igs")
#pax_springTorqueC.exportStep(f"{outFileName}.stp")
pax_springTorqueC.exportStl(f"{outFileName}.stl")

