# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "springTorqueC"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(42.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr1():
	P000 = App.Vector(8.8273, -0.0000, 0)
	P001 = App.Vector(10.9717, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(11.7472, 0.3686, 0)
	P003 = App.Vector(11.9509, 1.2028, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(11.4457, 3.6424, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(10.9274, 4.3270, 0)
	P006 = App.Vector(10.0693, 4.3574, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(8.1013, 3.5057, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(7.4251, 3.4632, 0)
	P009 = App.Vector(6.8770, 3.8614, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(6.1219, 4.9726, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(5.9534, 5.6288, 0)
	P012 = App.Vector(6.2418, 6.2418, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(7.7582, 7.7582, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(8.0458, 8.5672, 0)
	P015 = App.Vector(7.6001, 9.3011, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(5.5177, 10.6689, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(4.6672, 10.7866, 0)
	P018 = App.Vector(4.0389, 10.2012, 0)
	S011 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(3.2495, 8.2074, 0)
	S012 = Part.LineSegment(P018, P019)
	P020 = App.Vector(2.8015, 7.6992, 0)
	P021 = App.Vector(2.1324, 7.5932, 0)
	S013 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(0.8126, 7.8450, 0)
	S014 = Part.LineSegment(P021, P022)
	P023 = App.Vector(0.2295, 8.1898, 0)
	P024 = App.Vector(0.0000, 8.8273, 0)
	S015 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(0.0000, 10.9717, 0)
	S016 = Part.LineSegment(P024, P025)
	P026 = App.Vector(-0.3686, 11.7472, 0)
	P027 = App.Vector(-1.2028, 11.9509, 0)
	S017 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(-3.6424, 11.4457, 0)
	S018 = Part.LineSegment(P027, P028)
	P029 = App.Vector(-4.3270, 10.9274, 0)
	P030 = App.Vector(-4.3574, 10.0693, 0)
	S019 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(-3.5057, 8.1013, 0)
	S020 = Part.LineSegment(P030, P031)
	P032 = App.Vector(-3.4632, 7.4251, 0)
	P033 = App.Vector(-3.8614, 6.8770, 0)
	S021 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(-4.9726, 6.1219, 0)
	S022 = Part.LineSegment(P033, P034)
	P035 = App.Vector(-5.6288, 5.9534, 0)
	P036 = App.Vector(-6.2418, 6.2418, 0)
	S023 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-7.7582, 7.7582, 0)
	S024 = Part.LineSegment(P036, P037)
	P038 = App.Vector(-8.5672, 8.0458, 0)
	P039 = App.Vector(-9.3011, 7.6001, 0)
	S025 = Part.Arc(P037, P038, P039)
	P040 = App.Vector(-10.6689, 5.5177, 0)
	S026 = Part.LineSegment(P039, P040)
	P041 = App.Vector(-10.7866, 4.6672, 0)
	P042 = App.Vector(-10.2012, 4.0389, 0)
	S027 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(-8.2074, 3.2495, 0)
	S028 = Part.LineSegment(P042, P043)
	P044 = App.Vector(-7.6992, 2.8015, 0)
	P045 = App.Vector(-7.5932, 2.1324, 0)
	S029 = Part.Arc(P043, P044, P045)
	P046 = App.Vector(-7.8450, 0.8126, 0)
	S030 = Part.LineSegment(P045, P046)
	P047 = App.Vector(-8.1898, 0.2295, 0)
	P048 = App.Vector(-8.8273, 0.0000, 0)
	S031 = Part.Arc(P046, P047, P048)
	P049 = App.Vector(-10.9717, 0.0000, 0)
	S032 = Part.LineSegment(P048, P049)
	P050 = App.Vector(-11.7472, -0.3686, 0)
	P051 = App.Vector(-11.9509, -1.2028, 0)
	S033 = Part.Arc(P049, P050, P051)
	P052 = App.Vector(-11.4457, -3.6424, 0)
	S034 = Part.LineSegment(P051, P052)
	P053 = App.Vector(-10.9274, -4.3270, 0)
	P054 = App.Vector(-10.0693, -4.3574, 0)
	S035 = Part.Arc(P052, P053, P054)
	P055 = App.Vector(-8.1013, -3.5057, 0)
	S036 = Part.LineSegment(P054, P055)
	P056 = App.Vector(-7.4251, -3.4632, 0)
	P057 = App.Vector(-6.8770, -3.8614, 0)
	S037 = Part.Arc(P055, P056, P057)
	P058 = App.Vector(-6.1219, -4.9726, 0)
	S038 = Part.LineSegment(P057, P058)
	P059 = App.Vector(-5.9534, -5.6288, 0)
	P060 = App.Vector(-6.2418, -6.2418, 0)
	S039 = Part.Arc(P058, P059, P060)
	P061 = App.Vector(-7.7582, -7.7582, 0)
	S040 = Part.LineSegment(P060, P061)
	P062 = App.Vector(-8.0458, -8.5672, 0)
	P063 = App.Vector(-7.6001, -9.3011, 0)
	S041 = Part.Arc(P061, P062, P063)
	P064 = App.Vector(-5.5177, -10.6689, 0)
	S042 = Part.LineSegment(P063, P064)
	P065 = App.Vector(-4.6672, -10.7866, 0)
	P066 = App.Vector(-4.0389, -10.2012, 0)
	S043 = Part.Arc(P064, P065, P066)
	P067 = App.Vector(-3.2495, -8.2074, 0)
	S044 = Part.LineSegment(P066, P067)
	P068 = App.Vector(-2.8015, -7.6992, 0)
	P069 = App.Vector(-2.1324, -7.5932, 0)
	S045 = Part.Arc(P067, P068, P069)
	P070 = App.Vector(-0.8126, -7.8450, 0)
	S046 = Part.LineSegment(P069, P070)
	P071 = App.Vector(-0.2295, -8.1898, 0)
	P072 = App.Vector(-0.0000, -8.8273, 0)
	S047 = Part.Arc(P070, P071, P072)
	P073 = App.Vector(-0.0000, -10.9717, 0)
	S048 = Part.LineSegment(P072, P073)
	P074 = App.Vector(0.3686, -11.7472, 0)
	P075 = App.Vector(1.2028, -11.9509, 0)
	S049 = Part.Arc(P073, P074, P075)
	P076 = App.Vector(3.6424, -11.4457, 0)
	S050 = Part.LineSegment(P075, P076)
	P077 = App.Vector(4.3270, -10.9274, 0)
	P078 = App.Vector(4.3574, -10.0693, 0)
	S051 = Part.Arc(P076, P077, P078)
	P079 = App.Vector(3.5057, -8.1013, 0)
	S052 = Part.LineSegment(P078, P079)
	P080 = App.Vector(3.4632, -7.4251, 0)
	P081 = App.Vector(3.8614, -6.8770, 0)
	S053 = Part.Arc(P079, P080, P081)
	P082 = App.Vector(4.9726, -6.1219, 0)
	S054 = Part.LineSegment(P081, P082)
	P083 = App.Vector(5.6288, -5.9534, 0)
	P084 = App.Vector(6.2418, -6.2418, 0)
	S055 = Part.Arc(P082, P083, P084)
	P085 = App.Vector(7.7582, -7.7582, 0)
	S056 = Part.LineSegment(P084, P085)
	P086 = App.Vector(8.5672, -8.0458, 0)
	P087 = App.Vector(9.3011, -7.6001, 0)
	S057 = Part.Arc(P085, P086, P087)
	P088 = App.Vector(10.6689, -5.5177, 0)
	S058 = Part.LineSegment(P087, P088)
	P089 = App.Vector(10.7866, -4.6672, 0)
	P090 = App.Vector(10.2012, -4.0389, 0)
	S059 = Part.Arc(P088, P089, P090)
	P091 = App.Vector(8.2074, -3.2495, 0)
	S060 = Part.LineSegment(P090, P091)
	P092 = App.Vector(7.6992, -2.8015, 0)
	P093 = App.Vector(7.5932, -2.1324, 0)
	S061 = Part.Arc(P091, P092, P093)
	P094 = App.Vector(7.8450, -0.8126, 0)
	S062 = Part.LineSegment(P093, P094)
	P095 = App.Vector(8.1898, -0.2295, 0)
	P096 = App.Vector(8.8273, -0.0000, 0)
	S063 = Part.Arc(P094, P095, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047, S048, S049, S050, S051, S052, S053, S054, S055, S056, S057, S058, S059, S060, S061, S062, S063])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(15.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(10.6066, 10.6066, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(0.0000, 15.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-10.6066, 10.6066, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-15.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-10.6066, -10.6066, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-0.0000, -15.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr9():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(10.6066, -10.6066, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr10():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(40.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr11():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(36.9552, 15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr12():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(28.2843, 28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr13():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(15.3073, 36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr14():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(0.0000, 40.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr15():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-15.3073, 36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr16():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-28.2843, 28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr17():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-36.9552, 15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr18():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-40.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr19():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-36.9552, -15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr20():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-28.2843, -28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr21():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-15.3073, -36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr22():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-0.0000, -40.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr23():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(15.3073, -36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr24():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(28.2843, -28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr25():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(36.9552, -15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr26():
	P000 = App.Vector(17.3767, 0.5000, 0)
	P001 = App.Vector(18.8936, 0.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(19.6971, 0.6449, 0)
	P003 = App.Vector(20.3993, 1.0613, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(22.5362, 2.9118, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(24.8492, 3.7137, 0)
	P006 = App.Vector(27.0782, 2.7013, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(28.5103, 1.2080, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(30.5958, 0.5397, 0)
	P009 = App.Vector(32.2956, 1.9205, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(32.8015, 3.1430, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(33.8419, 4.4993, 0)
	P012 = App.Vector(35.4213, 5.1531, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(36.0702, 5.2382, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(37.0893, 5.8448, 0)
	P015 = App.Vector(37.3493, 7.0019, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(37.3440, 7.0303, 0)
	P017 = App.Vector(37.3387, 7.0586, 0)
	S010 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(36.6757, 8.0419, 0)
	P019 = App.Vector(35.5058, 8.2364, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(34.8703, 8.0798, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(33.1613, 8.1145, 0)
	P022 = App.Vector(31.6989, 8.9996, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(30.7831, 9.9545, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(28.6976, 10.6227, 0)
	P025 = App.Vector(26.9979, 9.2418, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(26.2069, 7.3299, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(24.4986, 5.5764, 0)
	P028 = App.Vector(22.0523, 5.4822, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(19.3888, 6.4291, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(18.5832, 6.5616, 0)
	P031 = App.Vector(17.7821, 6.4045, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(16.3690, 5.8529, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(16.1524, 5.6503, 0)
	P034 = App.Vector(16.1348, 5.3543, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(16.7065, 3.1451, 0)
	P036 = App.Vector(16.9772, 0.8793, 0)
	S022 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(17.1013, 0.6099, 0)
	P038 = App.Vector(17.3767, 0.5000, 0)
	S023 = Part.Arc(P036, P037, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr27():
	P000 = App.Vector(16.0054, 6.7844, 0)
	P001 = App.Vector(17.4185, 7.3360, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(18.5679, 7.5615, 0)
	P003 = App.Vector(19.7238, 7.3713, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(22.3872, 6.4245, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(24.0922, 6.4901, 0)
	P006 = App.Vector(25.2828, 7.7123, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(26.0739, 9.6241, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(28.5126, 11.6054, 0)
	P009 = App.Vector(31.5048, 10.6467, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(32.4206, 9.6918, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(33.4398, 9.0749, 0)
	P012 = App.Vector(34.6310, 9.0507, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(35.2665, 9.2074, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(36.2120, 9.9232, 0)
	P015 = App.Vector(36.3421, 11.1020, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(34.5764, 15.7630, 0)
	P017 = App.Vector(32.2159, 20.1528, 0)
	S010 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(31.2408, 20.8277, 0)
	P019 = App.Vector(30.0803, 20.5834, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(29.5452, 20.2064, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(28.7823, 19.2914, 0)
	P022 = App.Vector(28.5795, 18.1174, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(28.6997, 16.7998, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(27.4609, 13.9122, 0)
	P025 = App.Vector(24.3658, 13.3708, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(22.4038, 14.0275, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(20.7003, 13.9303, 0)
	P028 = App.Vector(19.5325, 12.6862, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(18.5004, 10.0547, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(17.8860, 9.0574, 0)
	P031 = App.Vector(16.9619, 8.3376, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(15.6187, 7.6326, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(15.4259, 7.4073, 0)
	P034 = App.Vector(15.4412, 7.1111, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(15.4684, 7.0519, 0)
	P036 = App.Vector(15.4953, 6.9925, 0)
	S022 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(15.7088, 6.7867, 0)
	P038 = App.Vector(16.0054, 6.7844, 0)
	S023 = Part.Arc(P036, P037, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr28():
	P000 = App.Vector(15.1539, 8.5181, 0)
	P001 = App.Vector(16.4971, 9.2230, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(17.1412, 9.7247, 0)
	P003 = App.Vector(17.5695, 10.4198, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(18.6016, 13.0514, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(20.2771, 14.8363, 0)
	P006 = App.Vector(22.7212, 14.9758, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(24.6832, 14.3191, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(26.8404, 14.6964, 0)
	P009 = App.Vector(27.7038, 16.7090, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(27.5836, 18.0266, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(27.8746, 19.7110, 0)
	P012 = App.Vector(28.9692, 21.0239, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(29.5043, 21.4009, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(30.1247, 22.4116, 0)
	P015 = App.Vector(29.8173, 23.5570, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(29.7994, 23.5796, 0)
	P017 = App.Vector(29.7814, 23.6023, 0)
	S010 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(28.7374, 24.1648, 0)
	P019 = App.Vector(27.6112, 23.7934, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(27.1212, 23.3593, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(25.5919, 22.5959, 0)
	P022 = App.Vector(23.8857, 22.7000, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(22.6310, 23.1199, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(20.4739, 22.7424, 0)
	P025 = App.Vector(19.6106, 20.7298, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(19.7986, 18.6693, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(19.1009, 16.3227, 0)
	P028 = App.Vector(16.9786, 15.1025, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(14.1802, 14.7031, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(13.4053, 14.4461, 0)
	P031 = App.Vector(12.7690, 13.9346, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(11.7741, 12.7895, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(11.6764, 12.5095, 0)
	P034 = App.Vector(11.7984, 12.2392, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(13.3313, 10.5488, 0)
	P036 = App.Vector(14.6240, 8.6683, 0)
	S022 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(14.8590, 8.4874, 0)
	P038 = App.Vector(15.1539, 8.5181, 0)
	S023 = Part.Arc(P036, P037, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr29():
	P000 = App.Vector(11.0192, 13.4454, 0)
	P001 = App.Vector(12.0141, 14.5905, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(12.9271, 15.3243, 0)
	P003 = App.Vector(14.0389, 15.6930, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(16.8373, 16.0925, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(18.3165, 16.9429, 0)
	P006 = App.Vector(18.8028, 18.5784, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(18.6148, 20.6389, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(19.8533, 23.5265, 0)
	P009 = App.Vector(22.9484, 24.0682, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(24.2030, 23.6483, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(25.3922, 23.5757, 0)
	P012 = App.Vector(26.4581, 24.1078, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(26.9480, 24.5419, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(27.4525, 25.6151, 0)
	P015 = App.Vector(27.0199, 26.7193, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(23.2905, 30.0259, 0)
	P017 = App.Vector(19.1603, 32.8159, 0)
	S010 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(17.9832, 32.9603, 0)
	P019 = App.Vector(17.0691, 32.2047, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(16.7706, 31.6223, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(16.5203, 30.4575, 0)
	P022 = App.Vector(16.8863, 29.3237, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(17.6050, 28.2129, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(17.8501, 25.0804, 0)
	P025 = App.Vector(15.3612, 23.1626, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(13.3187, 22.8323, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(11.8555, 21.9546, 0)
	P028 = App.Vector(11.3996, 20.3103, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(11.7087, 17.5006, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(11.6281, 16.3320, 0)
	P031 = App.Vector(11.1443, 15.2651, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(10.2826, 14.0167, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(10.2166, 13.7276, 0)
	P034 = App.Vector(10.3678, 13.4725, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(10.4194, 13.4326, 0)
	P036 = App.Vector(10.4709, 13.3926, 0)
	S022 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(10.7556, 13.3095, 0)
	P038 = App.Vector(11.0192, 13.4454, 0)
	S023 = Part.Arc(P036, P037, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr30():
	P000 = App.Vector(9.4596, 14.5848, 0)
	P001 = App.Vector(10.3213, 15.8332, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(10.6585, 16.5767, 0)
	P003 = App.Vector(10.7147, 17.3912, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(10.4056, 20.2010, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(11.0597, 22.5601, 0)
	P006 = App.Vector(13.1590, 23.8195, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(15.2015, 24.1498, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(16.9362, 25.4864, 0)
	P009 = App.Vector(16.7654, 27.6697, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(16.0467, 28.7805, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(15.5215, 30.4072, 0)
	P012 = App.Vector(15.8807, 32.0784, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(16.1792, 32.6609, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(16.2589, 33.8441, 0)
	P015 = App.Vector(15.4544, 34.7154, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(15.4280, 34.7272, 0)
	P017 = App.Vector(15.4016, 34.7389, 0)
	S010 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(14.2158, 34.7518, 0)
	P019 = App.Vector(13.3911, 33.8995, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(13.1590, 33.2875, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(12.1596, 31.9008, 0)
	P022 = App.Vector(10.6005, 31.2001, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(9.2944, 30.9888, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(7.5598, 29.6520, 0)
	P025 = App.Vector(7.7307, 27.4688, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(8.8548, 25.7317, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(9.3275, 23.3297, 0)
	P028 = App.Vector(8.0153, 21.2629, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(5.7231, 19.6088, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(5.1564, 19.0211, 0)
	P031 = App.Vector(4.8306, 18.2725, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(4.4818, 16.7962, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(4.5255, 16.5029, 0)
	P034 = App.Vector(4.7591, 16.3202, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(6.9020, 15.5358, 0)
	P036 = App.Vector(8.9205, 14.4715, 0)
	S022 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(9.2127, 14.4206, 0)
	P038 = App.Vector(9.4596, 14.5848, 0)
	S023 = Part.Arc(P036, P037, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr31():
	P000 = App.Vector(3.5086, 17.0261, 0)
	P001 = App.Vector(3.8574, 18.5024, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(4.3248, 19.5765, 0)
	P003 = App.Vector(5.1379, 20.4197, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(7.4301, 22.0738, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(8.3447, 23.5143, 0)
	P006 = App.Vector(8.0152, 25.1884, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(6.8912, 26.9255, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(6.6459, 30.0580, 0)
	P009 = App.Vector(9.1347, 31.9760, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(10.4408, 32.1872, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(11.5275, 32.6756, 0)
	P012 = App.Vector(12.2240, 33.6421, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(12.4561, 34.2541, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(12.4041, 35.4389, 0)
	P015 = App.Vector(11.5079, 36.2156, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(6.6690, 37.4102, 0)
	P017 = App.Vector(1.7153, 37.9613, 0)
	S010 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(0.6059, 37.5421, 0)
	P019 = App.Vector(0.1477, 36.4483, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(0.1540, 35.7938, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(0.4737, 34.6461, 0)
	P022 = App.Vector(1.3247, 33.8123, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(2.4773, 33.1627, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(4.1500, 30.5029, 0)
	P025 = App.Vector(2.8374, 27.6482, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(1.1824, 26.4065, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(0.2947, 24.9493, 0)
	P028 = App.Vector(0.6552, 23.2816, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(2.2346, 20.9373, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(2.7063, 19.8651, 0)
	P031 = App.Vector(2.7737, 18.6956, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(2.5909, 17.1897, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(2.6668, 16.9031, 0)
	P034 = App.Vector(2.9193, 16.7475, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(2.9835, 16.7362, 0)
	P036 = App.Vector(3.0476, 16.7246, 0)
	S022 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(3.3383, 16.7834, 0)
	P038 = App.Vector(3.5086, 17.0261, 0)
	S023 = Part.Arc(P036, P037, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr32():
	P000 = App.Vector(1.5982, 17.3103, 0)
	P001 = App.Vector(1.7810, 18.8162, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1.7340, 19.6312, 0)
	P003 = App.Vector(1.4053, 20.3785, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-0.1742, 22.7228, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-0.6914, 25.1157, 0)
	P006 = App.Vector(0.5823, 27.2064, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(2.2373, 28.4481, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(3.1522, 30.4378, 0)
	P009 = App.Vector(1.9863, 32.2916, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(0.8337, 32.9412, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-0.3873, 34.1375, 0)
	P012 = App.Vector(-0.8459, 35.7841, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(-0.8523, 36.4386, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(-1.3316, 37.5234, 0)
	P015 = App.Vector(-2.4489, 37.9210, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(-2.4777, 37.9191, 0)
	P017 = App.Vector(-2.5065, 37.9172, 0)
	S010 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(-3.5625, 37.3776, 0)
	P019 = App.Vector(-3.8966, 36.2397, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(-3.8177, 35.5900, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-4.0582, 33.8976, 0)
	P022 = App.Vector(-5.1131, 32.5526, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-6.1714, 31.7585, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(-7.0861, 29.7688, 0)
	P025 = App.Vector(-5.9202, 27.9151, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(-4.1176, 26.8993, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(-2.5827, 24.9921, 0)
	P028 = App.Vector(-2.7842, 22.5523, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-4.0451, 20.0224, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(-4.2738, 19.2387, 0)
	P031 = App.Vector(-4.2144, 18.4244, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(-3.8371, 16.9551, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(-3.6621, 16.7157, 0)
	P034 = App.Vector(-3.3704, 16.6625, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(-1.1084, 16.9638, 0)
	P036 = App.Vector(1.1735, 16.9594, 0)
	S022 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(1.4558, 17.0501, 0)
	P038 = App.Vector(1.5982, 17.3103, 0)
	S023 = Part.Arc(P036, P037, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr33():
	P000 = App.Vector(-4.8057, 16.7064, 0)
	P001 = App.Vector(-5.1830, 18.1757, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-5.2683, 19.3440, 0)
	P003 = App.Vector(-4.9401, 20.4685, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-3.6792, 22.9984, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-3.5388, 24.6988, 0)
	P006 = App.Vector(-4.6085, 26.0281, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-6.4111, 27.0439, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-8.0840, 29.7036, 0)
	P009 = App.Vector(-6.7716, 32.5584, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-5.7133, 33.3525, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-4.9780, 34.2899, 0)
	P012 = App.Vector(-4.8104, 35.4694, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(-4.8893, 36.1192, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(-5.4860, 37.1441, 0)
	P015 = App.Vector(-6.6405, 37.4153, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(-11.4803, 36.2243, 0)
	P017 = App.Vector(-16.1226, 34.4102, 0)
	S010 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(-16.9102, 33.5235, 0)
	P019 = App.Vector(-16.8076, 32.3420, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(-16.4978, 31.7654, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-15.6814, 30.8977, 0)
	P022 = App.Vector(-14.5404, 30.5549, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-13.2180, 30.5154, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(-10.5008, 28.9376, 0)
	P025 = App.Vector(-10.3363, 25.7999, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(-11.2248, 23.9313, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(-11.3336, 22.2285, 0)
	P028 = App.Vector(-10.2394, 20.9193, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-7.7514, 19.5775, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(-6.8354, 18.8473, 0)
	P031 = App.Vector(-6.2323, 17.8432, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(-5.6944, 16.4248, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(-5.4939, 16.2063, 0)
	P034 = App.Vector(-5.1980, 16.1858, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(-5.1359, 16.2056, 0)
	P036 = App.Vector(-5.0738, 16.2252, 0)
	S022 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-4.8437, 16.4123, 0)
	P038 = App.Vector(-4.8057, 16.7064, 0)
	S023 = Part.Arc(P036, P037, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr34():
	P000 = App.Vector(-6.6294, 16.0702, 0)
	P001 = App.Vector(-7.1673, 17.4886, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-7.5877, 18.1884, 0)
	P003 = App.Vector(-8.2261, 18.6973, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-10.7140, 20.0391, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-12.2840, 21.9175, 0)
	P006 = App.Vector(-12.1279, 24.3607, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-11.2394, 26.2293, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-11.3540, 28.4162, 0)
	P009 = App.Vector(-13.2479, 29.5158, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-14.5703, 29.5554, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-16.2074, 30.0472, 0)
	P012 = App.Vector(-17.3788, 31.2922, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(-17.6885, 31.8687, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(-18.6170, 32.6065, 0)
	P015 = App.Vector(-19.7911, 32.4393, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(-19.8158, 32.4243, 0)
	P017 = App.Vector(-19.8404, 32.4092, 0)
	S010 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(-20.5247, 31.4406, 0)
	P019 = App.Vector(-20.2917, 30.2778, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(-19.9199, 29.7392, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-19.3464, 28.1289, 0)
	P022 = App.Vector(-19.6554, 26.4477, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-20.2234, 25.2528, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(-20.1087, 23.0659, 0)
	P025 = App.Vector(-18.2148, 21.9663, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(-16.1467, 21.9046, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(-13.9013, 20.9292, 0)
	P028 = App.Vector(-12.9458, 18.6752, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-12.8866, 15.8491, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(-12.7249, 15.0488, 0)
	P031 = App.Vector(-12.2939, 14.3555, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(-11.2770, 13.2298, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(-11.0108, 13.0991, 0)
	P034 = App.Vector(-10.7278, 13.1877, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(-8.8650, 14.5056, 0)
	P036 = App.Vector(-6.8424, 15.5622, 0)
	S022 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-6.6345, 15.7737, 0)
	P038 = App.Vector(-6.6294, 16.0702, 0)
	S023 = Part.Arc(P036, P037, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr35():
	P000 = App.Vector(-12.0191, 12.5595, 0)
	P001 = App.Vector(-13.0360, 13.6852, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-13.6544, 14.6800, 0)
	P003 = App.Vector(-13.8864, 15.8281, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-13.9456, 18.6543, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-14.6116, 20.2252, 0)
	P006 = App.Vector(-16.1765, 20.9051, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-18.2446, 20.9668, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-20.9620, 22.5444, 0)
	P009 = App.Vector(-21.1266, 25.6821, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-20.5585, 26.8770, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-20.3431, 28.0488, 0)
	P012 = App.Vector(-20.7429, 29.1711, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(-21.1147, 29.7097, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(-22.1193, 30.3399, 0)
	P015 = App.Vector(-23.2676, 30.0436, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(-26.9996, 26.7399, 0)
	P017 = App.Vector(-30.2671, 22.9761, 0)
	S010 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(-30.5523, 21.8250, 0)
	P019 = App.Vector(-29.9125, 20.8265, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(-29.3702, 20.4599, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-28.2441, 20.0711, 0)
	P022 = App.Vector(-27.0745, 20.2978, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-25.8852, 20.8773, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(-22.7459, 20.7431, 0)
	P025 = App.Vector(-21.1421, 18.0411, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(-21.0605, 15.9737, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(-20.3655, 14.4154, 0)
	P028 = App.Vector(-18.7882, 13.7646, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-15.9616, 13.7328, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(-14.8113, 13.5119, 0)
	P031 = App.Vector(-13.8105, 12.9031, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(-12.6751, 11.8971, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(-12.3960, 11.7968, 0)
	P034 = App.Vector(-12.1246, 11.9162, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(-12.0788, 11.9626, 0)
	P036 = App.Vector(-12.0328, 12.0088, 0)
	S022 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-11.9161, 12.2814, 0)
	P038 = App.Vector(-12.0191, 12.5595, 0)
	S023 = Part.Arc(P036, P037, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr36():
	P000 = App.Vector(-13.3382, 11.1486, 0)
	P001 = App.Vector(-14.4737, 12.1546, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-15.1711, 12.5789, 0)
	P003 = App.Vector(-15.9729, 12.7328, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-18.7995, 12.7647, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-21.0625, 13.6984, 0)
	P006 = App.Vector(-22.0597, 15.9342, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-22.1414, 18.0016, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-23.2592, 19.8848, 0)
	P009 = App.Vector(-25.4471, 19.9784, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-26.6365, 19.3988, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-28.3146, 19.0736, 0)
	P012 = App.Vector(-29.9303, 19.6315, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(-30.4725, 19.9981, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(-31.6376, 20.2198, 0)
	P015 = App.Vector(-32.5995, 19.5262, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(-32.6143, 19.5014, 0)
	P017 = App.Vector(-32.6291, 19.4766, 0)
	S010 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(-32.7849, 18.3010, 0)
	P019 = App.Vector(-32.0382, 17.3796, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(-31.4587, 17.0755, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-30.2025, 15.9162, 0)
	P022 = App.Vector(-29.6948, 14.2840, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-29.6425, 12.9619, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(-28.5246, 11.0788, 0)
	P025 = App.Vector(-26.3367, 10.9854, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(-24.4768, 11.8918, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(-22.0353, 12.0716, 0)
	P028 = App.Vector(-20.1418, 10.5198, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-18.7760, 8.0449, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(-18.2609, 7.4115, 0)
	P031 = App.Vector(-17.5570, 6.9979, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(-16.1335, 6.4737, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(-15.8371, 6.4817, 0)
	P034 = App.Vector(-15.6276, 6.6916, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(-14.5906, 8.7243, 0)
	P036 = App.Vector(-13.2907, 10.5998, 0)
	S022 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-13.2050, 10.8837, 0)
	P038 = App.Vector(-13.3382, 11.1486, 0)
	S023 = Part.Arc(P036, P037, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr37():
	P000 = App.Vector(-16.4791, 5.5353, 0)
	P001 = App.Vector(-17.9026, 6.0595, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-18.9125, 6.6529, 0)
	P003 = App.Vector(-19.6515, 7.5618, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-21.0173, 10.0367, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-22.3370, 11.1182, 0)
	P006 = App.Vector(-24.0387, 10.9929, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-25.8986, 10.0864, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-29.0378, 10.2205, 0)
	P009 = App.Vector(-30.6417, 12.9224, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-30.6941, 14.2444, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-31.0479, 15.3820, 0)
	P012 = App.Vector(-31.9234, 16.1900, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(-32.5030, 16.4942, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(-33.6854, 16.5853, 0)
	P015 = App.Vector(-34.5644, 15.7893, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(-36.3336, 11.1296, 0)
	P017 = App.Vector(-37.4777, 6.2785, 0)
	S010 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(-37.1953, 5.1267, 0)
	P019 = App.Vector(-36.1647, 4.5400, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(-35.5143, 4.4674, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-34.3364, 4.6464, 0)
	P022 = App.Vector(-33.4061, 5.3906, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-32.6224, 6.4565, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(-29.7803, 7.7965, 0)
	P025 = App.Vector(-27.1046, 6.1494, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(-26.0714, 4.3567, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(-24.7319, 3.2999, 0)
	P028 = App.Vector(-23.0329, 3.4567, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-20.5153, 4.7420, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(-19.3940, 5.0810, 0)
	P031 = App.Vector(-18.2250, 5.0070, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(-16.7521, 4.6440, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(-16.4584, 4.6848, 0)
	P034 = App.Vector(-16.2735, 4.9167, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(-16.2545, 4.9790, 0)
	P036 = App.Vector(-16.2353, 5.0413, 0)
	S022 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-16.2586, 5.3370, 0)
	P038 = App.Vector(-16.4791, 5.5353, 0)
	S023 = Part.Arc(P036, P037, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr38():
	P000 = App.Vector(-16.9914, 3.6730, 0)
	P001 = App.Vector(-18.4643, 4.0361, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-19.2791, 4.0877, 0)
	P003 = App.Vector(-20.0605, 3.8514, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-22.5782, 2.5660, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-25.0159, 2.3410, 0)
	P006 = App.Vector(-26.9379, 3.8574, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-27.9710, 5.6500, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-29.8359, 6.7980, 0)
	P009 = App.Vector(-31.8167, 5.8641, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-32.6005, 4.7982, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-33.9352, 3.7304, 0)
	P012 = App.Vector(-35.6252, 3.4735, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(-36.2757, 3.5461, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(-37.4103, 3.2011, 0)
	P015 = App.Vector(-37.9397, 2.1399, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(-37.9413, 2.1110, 0)
	P017 = App.Vector(-37.9429, 2.0822, 0)
	S010 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(-37.5345, 0.9688, 0)
	P019 = App.Vector(-36.4452, 0.5000, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(-35.7906, 0.5000, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-34.1396, 0.0573, 0)
	P022 = App.Vector(-32.9316, -1.1521, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-32.2709, -2.2983, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(-30.4059, -3.4462, 0)
	P025 = App.Vector(-28.4251, -2.5122, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(-27.1995, -0.8452, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(-25.1212, 0.4486, 0)
	P028 = App.Vector(-22.7235, -0.0455, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-20.3640, -1.6022, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(-19.6135, -1.9237, 0)
	P031 = App.Vector(-18.7981, -1.9628, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(-17.2940, -1.7654, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(-17.0352, -1.6206, 0)
	P034 = App.Vector(-16.9473, -1.3374, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(-16.9737, 0.9444, 0)
	P036 = App.Vector(-16.6943, 3.2092, 0)
	S022 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-16.7503, 3.5004, 0)
	P038 = App.Vector(-16.9914, 3.6730, 0)
	S023 = Part.Arc(P036, P037, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr39():
	P000 = App.Vector(-17.1639, -2.7569, 0)
	P001 = App.Vector(-18.6679, -2.9543, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-19.8380, -2.8982, 0)
	P003 = App.Vector(-20.9147, -2.4369, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-23.2742, -0.8802, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-24.9453, -0.5359, 0)
	P006 = App.Vector(-26.3938, -1.4376, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-27.6194, -3.1046, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-30.4614, -4.4447, 0)
	P009 = App.Vector(-33.1373, -2.7977, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-33.7980, -1.6514, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-34.6399, -0.8086, 0)
	P012 = App.Vector(-35.7906, -0.5000, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(-36.4452, -0.5000, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(-37.5345, -0.9688, 0)
	P015 = App.Vector(-37.9429, -2.0822, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(-37.3440, -7.0303, 0)
	P017 = App.Vector(-36.1027, -11.8574, 0)
	S010 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(-35.3174, -12.7460, 0)
	P019 = App.Vector(-34.1321, -12.7867, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(-33.5224, -12.5487, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-32.5627, -11.8428, 0)
	P022 = App.Vector(-32.0848, -10.7514, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-31.8862, -9.4434, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(-29.9924, -6.9361, 0)
	P025 = App.Vector(-26.8577, -7.1511, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(-25.1098, -8.2583, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(-23.4325, -8.5716, 0)
	P028 = App.Vector(-22.0010, -7.6432, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-20.3691, -5.3351, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(-19.5338, -4.5138, 0)
	P031 = App.Vector(-18.4643, -4.0361, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(-16.9914, -3.6730, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(-16.7503, -3.5004, 0)
	P034 = App.Vector(-16.6943, -3.2092, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(-16.7065, -3.1451, 0)
	P036 = App.Vector(-16.7185, -3.0810, 0)
	S022 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-16.8765, -2.8301, 0)
	P038 = App.Vector(-17.1639, -2.7569, 0)
	S023 = Part.Arc(P036, P037, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr40():
	P000 = App.Vector(-16.7521, -4.6440, 0)
	P001 = App.Vector(-18.2250, -5.0070, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-18.9704, -5.3400, 0)
	P003 = App.Vector(-19.5526, -5.9124, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-21.1845, -8.2205, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-23.2384, -9.5526, 0)
	P006 = App.Vector(-25.6449, -9.1031, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-27.3928, -7.9959, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-29.5776, -7.8461, 0)
	P009 = App.Vector(-30.8975, -9.5935, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-31.0962, -10.9016, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-31.7817, -12.4674, 0)
	P012 = App.Vector(-33.1588, -13.4802, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(-33.7685, -13.7182, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(-34.6128, -14.5510, 0)
	P015 = App.Vector(-34.5884, -15.7367, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(-34.5764, -15.7630, 0)
	P017 = App.Vector(-34.5644, -15.7893, 0)
	S010 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(-33.6854, -16.5853, 0)
	P019 = App.Vector(-32.5030, -16.4942, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(-31.9234, -16.1900, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-30.2557, -15.8147, 0)
	P022 = App.Vector(-28.6241, -16.3242, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-27.5063, -17.0321, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(-25.3215, -17.1818, 0)
	P025 = App.Vector(-24.0017, -15.4343, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(-23.6912, -13.3887, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(-22.4522, -11.2772, 0)
	P028 = App.Vector(-20.0995, -10.6004, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-17.2868, -10.8823, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(-16.4729, -10.8182, 0)
	P031 = App.Vector(-15.7327, -10.4739, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(-14.4927, -9.6001, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(-14.3308, -9.3516, 0)
	P034 = App.Vector(-14.3846, -9.0600, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(-15.4684, -7.0519, 0)
	P036 = App.Vector(-16.2735, -4.9167, 0)
	S022 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-16.4584, -4.6848, 0)
	P038 = App.Vector(-16.7521, -4.6440, 0)
	S023 = Part.Arc(P036, P037, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr41():
	P000 = App.Vector(-13.9167, -10.4176, 0)
	P001 = App.Vector(-15.1567, -11.2913, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-16.2188, -11.7854, 0)
	P003 = App.Vector(-17.3866, -11.8773, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-20.1992, -11.5954, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-21.8390, -12.0671, 0)
	P006 = App.Vector(-22.7025, -13.5387, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-23.0130, -15.5843, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-24.9067, -18.0917, 0)
	P009 = App.Vector(-28.0414, -17.8769, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-29.1591, -17.1690, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-30.2964, -16.8139, 0)
	P012 = App.Vector(-31.4587, -17.0755, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(-32.0382, -17.3796, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(-32.7849, -18.3010, 0)
	P015 = App.Vector(-32.6291, -19.4766, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(-29.7994, -23.5796, 0)
	P017 = App.Vector(-26.4569, -27.2769, 0)
	S010 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(-25.3486, -27.6989, 0)
	P019 = App.Vector(-24.2802, -27.1840, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(-23.8510, -26.6899, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-23.3292, -25.6189, 0)
	P022 = App.Vector(-23.4132, -24.4305, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-23.8452, -23.1799, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(-23.3335, -20.0798, 0)
	P025 = App.Vector(-20.4580, -18.8134, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(-18.3958, -18.9815, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(-16.7651, -18.4794, 0)
	P028 = App.Vector(-15.9289, -16.9921, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-15.5566, -14.1899, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(-15.1987, -13.0746, 0)
	P031 = App.Vector(-14.4737, -12.1546, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(-13.3382, -11.1486, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(-13.2050, -10.8837, 0)
	P034 = App.Vector(-13.2907, -10.5998, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(-13.3313, -10.5488, 0)
	P036 = App.Vector(-13.3716, -10.4976, 0)
	S022 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-13.6282, -10.3488, 0)
	P038 = App.Vector(-13.9167, -10.4176, 0)
	S023 = Part.Arc(P036, P037, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr42():
	P000 = App.Vector(-12.6751, -11.8971, 0)
	P001 = App.Vector(-13.8105, -12.9031, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-14.3158, -13.5443, 0)
	P003 = App.Vector(-14.5653, -14.3217, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-14.9377, -17.1238, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-16.1373, -19.2578, 0)
	P006 = App.Vector(-18.4770, -19.9782, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-20.5392, -19.8101, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-22.5434, -20.6927, 0)
	P009 = App.Vector(-22.9000, -22.8534, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-22.4681, -24.1040, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-22.3474, -25.8091, 0)
	P012 = App.Vector(-23.0961, -27.3458, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(-23.5253, -27.8399, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(-23.8859, -28.9697, 0)
	P015 = App.Vector(-23.3133, -30.0082, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(-23.2905, -30.0259, 0)
	P017 = App.Vector(-23.2676, -30.0436, 0)
	S010 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(-22.1193, -30.3399, 0)
	P019 = App.Vector(-21.1147, -29.7097, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(-20.7429, -29.1711, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-19.4407, -28.0638, 0)
	P022 = App.Vector(-17.7591, -27.7566, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-16.4404, -27.8640, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(-14.4363, -26.9812, 0)
	P025 = App.Vector(-14.0798, -24.8205, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(-14.7555, -22.8649, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(-14.6396, -20.4195, 0)
	P028 = App.Vector(-12.8710, -18.7269, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-10.2495, -17.6694, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(-9.5586, -17.2344, 0)
	P031 = App.Vector(-9.0631, -16.5855, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(-8.3712, -15.2356, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(-8.3434, -14.9403, 0)
	P034 = App.Vector(-8.5265, -14.7071, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(-10.4194, -13.4326, 0)
	P036 = App.Vector(-12.1246, -11.9162, 0)
	S022 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-12.3960, -11.7968, 0)
	P038 = App.Vector(-12.6751, -11.8971, 0)
	S023 = Part.Arc(P036, P037, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr43():
	P000 = App.Vector(-7.4813, -15.6917, 0)
	P001 = App.Vector(-8.1732, -17.0417, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-8.8841, -17.9727, 0)
	P003 = App.Vector(-9.8754, -18.5968, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-12.4968, -19.6543, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-13.7296, -20.8340, 0)
	P006 = App.Vector(-13.8103, -22.5383, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-13.1346, -24.4939, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-13.6461, -27.5941, 0)
	P009 = App.Vector(-16.5216, -28.8607, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-17.8403, -28.7533, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-19.0123, -28.9674, 0)
	P012 = App.Vector(-19.9199, -29.7392, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(-20.2917, -30.2778, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(-20.5247, -31.4406, 0)
	P015 = App.Vector(-19.8404, -32.4092, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(-15.4280, -34.7272, 0)
	P017 = App.Vector(-10.7502, -36.4477, 0)
	S010 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(-9.5728, -36.3062, 0)
	P019 = App.Vector(-8.8660, -35.3538, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(-8.7156, -34.7168, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-8.7513, -33.5260, 0)
	P022 = App.Vector(-9.3780, -32.5128, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-10.3417, -31.6062, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(-11.3293, -28.6234, 0)
	P025 = App.Vector(-9.3716, -26.1657, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(-7.4675, -25.3562, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(-6.2569, -24.1538, 0)
	P028 = App.Vector(-6.2078, -22.4483, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-7.1803, -19.7941, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(-7.3817, -18.6402, 0)
	P031 = App.Vector(-7.1673, -17.4886, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(-6.6294, -16.0702, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(-6.6345, -15.7737, 0)
	P034 = App.Vector(-6.8424, -15.5622, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(-6.9020, -15.5358, 0)
	P036 = App.Vector(-6.9615, -15.5093, 0)
	S022 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-7.2578, -15.4968, 0)
	P038 = App.Vector(-7.4813, -15.6917, 0)
	S023 = Part.Arc(P036, P037, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr44():
	P000 = App.Vector(-5.6944, -16.4248, 0)
	P001 = App.Vector(-6.2323, -17.8432, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-6.3817, -18.6458, 0)
	P003 = App.Vector(-6.2413, -19.4501, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-5.2688, -22.1042, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-5.3393, -24.5513, 0)
	P006 = App.Vector(-7.0763, -26.2765, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-8.9804, -27.0860, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-10.3448, -28.7989, 0)
	P009 = App.Vector(-9.6565, -30.8779, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-8.6928, -31.7844, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-7.7936, -33.2382, 0)
	P012 = App.Vector(-7.7423, -34.9468, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(-7.8928, -35.5837, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(-7.6870, -36.7517, 0)
	P015 = App.Vector(-6.6974, -37.4051, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(-6.6690, -37.4102, 0)
	P017 = App.Vector(-6.6405, -37.4153, 0)
	S010 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(-5.4860, -37.1441, 0)
	P019 = App.Vector(-4.8893, -36.1192, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(-4.8104, -35.4694, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-4.1719, -33.8838, 0)
	P022 = App.Vector(-2.8258, -32.8303, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-1.6082, -32.3126, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(-0.2439, -30.5996, 0)
	P025 = App.Vector(-0.9324, -28.5207, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(-2.4395, -27.1031, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(-3.4733, -24.8840, 0)
	P028 = App.Vector(-2.6939, -22.5633, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-0.8641, -20.4086, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(-0.4545, -19.7024, 0)
	P031 = App.Vector(-0.3173, -18.8976, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(-0.3320, -17.3807, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(-0.4446, -17.1064, 0)
	P034 = App.Vector(-0.7152, -16.9850, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(-2.9835, -16.7362, 0)
	P036 = App.Vector(-5.1980, -16.1858, 0)
	S022 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-5.4939, -16.2063, 0)
	P038 = App.Vector(-5.6944, -16.4248, 0)
	S023 = Part.Arc(P036, P037, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr45():
	P000 = App.Vector(0.6679, -17.3711, 0)
	P001 = App.Vector(0.6826, -18.8879, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(0.4859, -20.0427, 0)
	P003 = App.Vector(-0.1019, -21.0559, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-1.9316, -23.2106, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-2.4749, -24.8280, 0)
	P006 = App.Vector(-1.7543, -26.3747, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(-0.2472, -27.7923, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(0.7406, -30.7751, 0)
	P009 = App.Vector(-1.2169, -33.2329, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-2.4345, -33.7506, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-3.3727, -34.4848, 0)
	P012 = App.Vector(-3.8177, -35.5900, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(-3.8966, -36.2397, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(-3.5625, -37.3776, 0)
	P015 = App.Vector(-2.5065, -37.9172, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(2.4777, -37.9191, 0)
	P017 = App.Vector(7.4192, -37.2687, 0)
	S010 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(8.3961, -36.5962, 0)
	P019 = App.Vector(8.5793, -35.4245, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(8.4165, -34.7906, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(7.8314, -33.7527, 0)
	P022 = App.Vector(6.8057, -33.1468, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(5.5311, -32.7919, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(3.2704, -30.6098, 0)
	P025 = App.Vector(3.8617, -27.5238, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(5.1715, -25.9221, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(5.6846, -24.2949, 0)
	P028 = App.Vector(4.9355, -22.7619, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(2.8409, -20.8636, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(2.1264, -19.9355, 0)
	P031 = App.Vector(1.7810, -18.8162, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(1.5982, -17.3103, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(1.4558, -17.0501, 0)
	P034 = App.Vector(1.1735, -16.9594, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(1.1084, -16.9638, 0)
	P036 = App.Vector(1.0434, -16.9680, 0)
	S022 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(0.7752, -17.0946, 0)
	P038 = App.Vector(0.6679, -17.3711, 0)
	S023 = Part.Arc(P036, P037, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr46():
	P000 = App.Vector(2.5909, -17.1897, 0)
	P001 = App.Vector(2.7737, -18.6956, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(3.0144, -19.4758, 0)
	P003 = App.Vector(3.5125, -20.1227, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(5.6070, -22.0209, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(6.6819, -24.2204, 0)
	P006 = App.Vector(5.9456, -26.5552, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(4.6358, -28.1569, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(4.2237, -30.3077, 0)
	P009 = App.Vector(5.7993, -31.8286, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(7.0739, -32.1835, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(8.5457, -33.0528, 0)
	P012 = App.Vector(9.3851, -34.5419, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(9.5478, -35.1758, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(10.2728, -36.1143, 0)
	P015 = App.Vector(11.4528, -36.2330, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(11.4803, -36.2243, 0)
	P017 = App.Vector(11.5079, -36.2156, 0)
	S010 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(12.4041, -35.4389, 0)
	P019 = App.Vector(12.4561, -34.2541, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(12.2240, -33.6421, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(12.0525, -31.9414, 0)
	P022 = App.Vector(12.7549, -30.3830, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(13.5924, -29.3588, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(14.0044, -27.2079, 0)
	P025 = App.Vector(12.4286, -25.6871, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(10.4354, -25.1323, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(8.4887, -23.6478, 0)
	P028 = App.Vector(8.1004, -21.2307, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(8.7192, -18.4725, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(8.7538, -17.6568, 0)
	P031 = App.Vector(8.5012, -16.8805, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(7.7832, -15.5442, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(7.5561, -15.3536, 0)
	P034 = App.Vector(7.2601, -15.3718, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(5.1359, -16.2056, 0)
	P036 = App.Vector(2.9193, -16.7475, 0)
	S022 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(2.6668, -16.9031, 0)
	P038 = App.Vector(2.5909, -17.1897, 0)
	S023 = Part.Arc(P036, P037, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr47():
	P000 = App.Vector(8.6642, -15.0709, 0)
	P001 = App.Vector(9.3821, -16.4072, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(9.7445, -17.5211, 0)
	P003 = App.Vector(9.6950, -18.6914, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(9.0761, -21.4496, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(9.3468, -23.1343, 0)
	P006 = App.Vector(10.7035, -24.1689, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(12.6968, -24.7237, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(14.9576, -26.9058, 0)
	P009 = App.Vector(14.3665, -29.9918, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(13.5290, -31.0160, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(13.0395, -32.1022, 0)
	P012 = App.Vector(13.1590, -33.2875, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(13.3911, -33.8995, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(14.2158, -34.7518, 0)
	P015 = App.Vector(15.4016, -34.7389, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(19.8158, -32.4243, 0)
	P017 = App.Vector(23.8890, -29.5519, 0)
	S010 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(24.4415, -28.5025, 0)
	P019 = App.Vector(24.0591, -27.3799, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(23.6204, -26.8942, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(22.6201, -26.2471, 0)
	P022 = App.Vector(21.4302, -26.1873, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(20.1367, -26.4654, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(17.1208, -25.5838, 0)
	P025 = App.Vector(16.2103, -22.5765, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(16.6257, -20.5496, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(16.3239, -18.8703, 0)
	P028 = App.Vector(14.9481, -17.8610, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(12.2113, -17.1536, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(11.1473, -16.6638, 0)
	P031 = App.Vector(10.3213, -15.8332, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(9.4596, -14.5848, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(9.2127, -14.4206, 0)
	P034 = App.Vector(8.9205, -14.4715, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(8.8650, -14.5056, 0)
	P036 = App.Vector(8.8093, -14.5395, 0)
	S022 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(8.6307, -14.7762, 0)
	P038 = App.Vector(8.6642, -15.0709, 0)
	S023 = Part.Arc(P036, P037, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr48():
	P000 = App.Vector(10.2826, -14.0167, 0)
	P001 = App.Vector(11.1443, -15.2651, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(11.7200, -15.8441, 0)
	P003 = App.Vector(12.4616, -16.1854, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(15.1984, -16.8928, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(17.1723, -18.3409, 0)
	P006 = App.Vector(17.6054, -20.7504, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(17.1899, -22.7773, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(17.8246, -24.8733, 0)
	P009 = App.Vector(19.9265, -25.4877, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(21.2200, -25.2097, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(22.9272, -25.2954, 0)
	P012 = App.Vector(24.3625, -26.2238, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(24.8012, -26.7095, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(25.8793, -27.2036, 0)
	P015 = App.Vector(26.9793, -26.7604, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(26.9996, -26.7399, 0)
	P017 = App.Vector(27.0199, -26.7193, 0)
	S010 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(27.4525, -25.6151, 0)
	P019 = App.Vector(26.9480, -24.5419, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(26.4581, -24.1078, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(25.5159, -22.6816, 0)
	P022 = App.Vector(25.4136, -20.9753, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(25.6792, -19.6792, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(25.0444, -17.5833, 0)
	P025 = App.Vector(22.9424, -16.9689, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(20.9196, -17.4040, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(18.5060, -16.9942, 0)
	P028 = App.Vector(17.0389, -15.0344, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(16.3051, -12.3046, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(15.9566, -11.5663, 0)
	P031 = App.Vector(15.3721, -10.9962, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(14.1155, -10.1466, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(13.8257, -10.0834, 0)
	P034 = App.Vector(13.5721, -10.2371, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(12.0788, -11.9626, 0)
	P036 = App.Vector(10.3678, -13.4725, 0)
	S022 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(10.2166, -13.7276, 0)
	P038 = App.Vector(10.2826, -14.0167, 0)
	S023 = Part.Arc(P036, P037, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr49():
	P000 = App.Vector(14.6755, -9.3182, 0)
	P001 = App.Vector(15.9322, -10.1678, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(16.7708, -10.9857, 0)
	P003 = App.Vector(17.2708, -12.0450, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(18.0046, -14.7748, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(19.0272, -16.1407, 0)
	P006 = App.Vector(20.7094, -16.4263, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(22.7322, -15.9913, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(25.7481, -16.8727, 0)
	P009 = App.Vector(26.6588, -19.8799, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(26.3932, -21.1761, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(26.4645, -22.3653, 0)
	P012 = App.Vector(27.1212, -23.3593, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(27.6112, -23.7934, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(28.7374, -24.1648, 0)
	P015 = App.Vector(29.7814, -23.6023, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(32.6143, -19.5014, 0)
	P017 = App.Vector(34.8861, -15.0651, 0)
	S010 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(34.8876, -13.8792, 0)
	P019 = App.Vector(34.0274, -13.0628, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(33.4132, -12.8367, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(32.2267, -12.7286, 0)
	P022 = App.Vector(31.1454, -13.2286, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(30.1293, -14.0760, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(27.0491, -14.6968, 0)
	P025 = App.Vector(24.8453, -12.4572, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(24.2712, -10.4694, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(23.2235, -9.1227, 0)
	P028 = App.Vector(21.5363, -8.8684, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(18.7843, -9.5138, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(17.6145, -9.5747, 0)
	P031 = App.Vector(16.4971, -9.2230, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(15.1539, -8.5181, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(14.8590, -8.4874, 0)
	P034 = App.Vector(14.6240, -8.6683, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(14.5906, -8.7243, 0)
	P036 = App.Vector(14.5571, -8.7802, 0)
	S022 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(14.5089, -9.0728, 0)
	P038 = App.Vector(14.6755, -9.3182, 0)
	S023 = Part.Arc(P036, P037, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr50():
	P000 = App.Vector(15.6187, -7.6326, 0)
	P001 = App.Vector(16.9619, -8.3376, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(17.7406, -8.5827, 0)
	P003 = App.Vector(18.5559, -8.5403, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(21.3080, -7.8948, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(23.7287, -8.2597, 0)
	P006 = App.Vector(25.2320, -10.1920, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(25.8061, -12.1798, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(27.3420, -13.7407, 0)
	P009 = App.Vector(29.4888, -13.3080, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(30.5049, -12.4606, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(32.0564, -11.7432, 0)
	P012 = App.Vector(33.7587, -11.8983, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(34.3729, -12.1244, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(35.5572, -12.0609, 0)
	P015 = App.Vector(36.3251, -11.1573, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(36.3336, -11.1296, 0)
	P017 = App.Vector(36.3421, -11.1020, 0)
	S010 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(36.2120, -9.9232, 0)
	P019 = App.Vector(35.2665, -9.2074, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(34.6310, -9.0507, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(33.1339, -8.2258, 0)
	P022 = App.Vector(32.2503, -6.7625, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(31.8832, -5.4914, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(30.3471, -3.9305, 0)
	P025 = App.Vector(28.2003, -4.3634, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(26.6114, -5.6886, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(24.2839, -6.4474, 0)
	P028 = App.Vector(22.0740, -5.3939, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(20.1557, -3.3178, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(19.5040, -2.8260, 0)
	P031 = App.Vector(18.7216, -2.5929, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(17.2140, -2.4246, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(16.9281, -2.5033, 0)
	P034 = App.Vector(16.7749, -2.7573, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(16.2545, -4.9790, 0)
	P036 = App.Vector(15.4412, -7.1111, 0)
	S022 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(15.4259, -7.4073, 0)
	P038 = App.Vector(15.6187, -7.6326, 0)
	S023 = Part.Arc(P036, P037, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr51():
	P000 = App.Vector(17.3249, -1.4308, 0)
	P001 = App.Vector(18.8325, -1.5991, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(19.9551, -1.9336, 0)
	P003 = App.Vector(20.8901, -2.6391, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(22.8085, -4.7153, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(24.3487, -5.4495, 0)
	P006 = App.Vector(25.9709, -4.9207, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(27.5598, -3.5954, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(30.6399, -2.9744, 0)
	P009 = App.Vector(32.8439, -5.2138, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(33.2111, -6.4849, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(33.8268, -7.5048, 0)
	P012 = App.Vector(34.8703, -8.0798, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(35.5058, -8.2364, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(36.6757, -8.0419, 0)
	P015 = App.Vector(37.3387, -7.0586, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(37.9413, -2.1110, 0)
	P017 = App.Vector(37.8912, 2.8729, 0)
	S010 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(37.3414, 3.9237, 0)
	P019 = App.Vector(36.2003, 4.2467, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(35.5514, 4.1616, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(34.4506, 3.7059, 0)
	P022 = App.Vector(33.7255, 2.7606, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(33.2196, 1.5381, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(30.7808, -0.4431, 0)
	P025 = App.Vector(27.7886, 0.5159, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(26.3565, 2.0092, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(24.8029, 2.7148, 0)
	P028 = App.Vector(23.1908, 2.1559, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(21.0540, 0.3054, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(20.0464, -0.2921, 0)
	P031 = App.Vector(18.8936, -0.5000, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(17.3767, -0.5000, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(17.1013, -0.6099, 0)
	P034 = App.Vector(16.9772, -0.8793, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(16.9737, -0.9444, 0)
	P036 = App.Vector(16.9700, -1.0095, 0)
	S022 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(17.0634, -1.2910, 0)
	P038 = App.Vector(17.3249, -1.4308, 0)
	S023 = Part.Arc(P036, P037, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_springTorqueC_faceProfile_Fa0():
	FC000 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr0()
	FC001 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr1()
	FC002 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr2()
	FC003 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr3()
	FC004 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr4()
	FC005 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr5()
	FC006 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr6()
	FC007 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr7()
	FC008 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr8()
	FC009 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr9()
	FC010 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr10()
	FC011 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr11()
	FC012 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr12()
	FC013 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr13()
	FC014 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr14()
	FC015 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr15()
	FC016 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr16()
	FC017 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr17()
	FC018 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr18()
	FC019 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr19()
	FC020 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr20()
	FC021 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr21()
	FC022 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr22()
	FC023 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr23()
	FC024 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr24()
	FC025 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr25()
	FC026 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr26()
	FC027 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr27()
	FC028 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr28()
	FC029 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr29()
	FC030 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr30()
	FC031 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr31()
	FC032 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr32()
	FC033 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr33()
	FC034 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr34()
	FC035 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr35()
	FC036 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr36()
	FC037 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr37()
	FC038 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr38()
	FC039 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr39()
	FC040 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr40()
	FC041 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr41()
	FC042 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr42()
	FC043 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr43()
	FC044 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr44()
	FC045 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr45()
	FC046 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr46()
	FC047 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr47()
	FC048 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr48()
	FC049 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr49()
	FC050 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr50()
	FC051 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr51()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008, FC009, FC010, FC011, FC012, FC013, FC014, FC015, FC016, FC017, FC018, FC019, FC020, FC021, FC022, FC023, FC024, FC025, FC026, FC027, FC028, FC029, FC030, FC031, FC032, FC033, FC034, FC035, FC036, FC037, FC038, FC039, FC040, FC041, FC042, FC043, FC044, FC045, FC046, FC047, FC048, FC049, FC050, FC051])
	rOneFace.check()
	return rOneFace

def springTorqueC_faceProfile():
	FA000 = face_springTorqueC_faceProfile_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_springTorqueC_profile():
	FIG = springTorqueC_faceProfile()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_springTorqueC_profile = fex_subpax_springTorqueC_profile()

pax_springTorqueC = subpax_springTorqueC_profile

pax_springTorqueC.check()
#pax_springTorqueC.exportBrep(f"{outFileName}.brep")
#pax_springTorqueC.exportIges(f"{outFileName}.igs")
#pax_springTorqueC.exportStep(f"{outFileName}.stp")
pax_springTorqueC.exportStl(f"{outFileName}.stl")

