# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "springTorqueC"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(42.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr1():
	P000 = App.Vector(8.8273, -0.0000, 0)
	P001 = App.Vector(10.9717, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(11.7472, 0.3686, 0)
	P003 = App.Vector(11.9509, 1.2028, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(11.4457, 3.6424, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(10.9274, 4.3270, 0)
	P006 = App.Vector(10.0693, 4.3574, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(8.1013, 3.5057, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(7.4251, 3.4632, 0)
	P009 = App.Vector(6.8770, 3.8614, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(6.1219, 4.9726, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(5.9534, 5.6288, 0)
	P012 = App.Vector(6.2418, 6.2418, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(7.7582, 7.7582, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(8.0458, 8.5672, 0)
	P015 = App.Vector(7.6001, 9.3011, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(5.5177, 10.6689, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(4.6672, 10.7866, 0)
	P018 = App.Vector(4.0389, 10.2012, 0)
	S011 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(3.2495, 8.2074, 0)
	S012 = Part.LineSegment(P018, P019)
	P020 = App.Vector(2.8015, 7.6992, 0)
	P021 = App.Vector(2.1324, 7.5932, 0)
	S013 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(0.8126, 7.8450, 0)
	S014 = Part.LineSegment(P021, P022)
	P023 = App.Vector(0.2295, 8.1898, 0)
	P024 = App.Vector(0.0000, 8.8273, 0)
	S015 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(0.0000, 10.9717, 0)
	S016 = Part.LineSegment(P024, P025)
	P026 = App.Vector(-0.3686, 11.7472, 0)
	P027 = App.Vector(-1.2028, 11.9509, 0)
	S017 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(-3.6424, 11.4457, 0)
	S018 = Part.LineSegment(P027, P028)
	P029 = App.Vector(-4.3270, 10.9274, 0)
	P030 = App.Vector(-4.3574, 10.0693, 0)
	S019 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(-3.5057, 8.1013, 0)
	S020 = Part.LineSegment(P030, P031)
	P032 = App.Vector(-3.4632, 7.4251, 0)
	P033 = App.Vector(-3.8614, 6.8770, 0)
	S021 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(-4.9726, 6.1219, 0)
	S022 = Part.LineSegment(P033, P034)
	P035 = App.Vector(-5.6288, 5.9534, 0)
	P036 = App.Vector(-6.2418, 6.2418, 0)
	S023 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-7.7582, 7.7582, 0)
	S024 = Part.LineSegment(P036, P037)
	P038 = App.Vector(-8.5672, 8.0458, 0)
	P039 = App.Vector(-9.3011, 7.6001, 0)
	S025 = Part.Arc(P037, P038, P039)
	P040 = App.Vector(-10.6689, 5.5177, 0)
	S026 = Part.LineSegment(P039, P040)
	P041 = App.Vector(-10.7866, 4.6672, 0)
	P042 = App.Vector(-10.2012, 4.0389, 0)
	S027 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(-8.2074, 3.2495, 0)
	S028 = Part.LineSegment(P042, P043)
	P044 = App.Vector(-7.6992, 2.8015, 0)
	P045 = App.Vector(-7.5932, 2.1324, 0)
	S029 = Part.Arc(P043, P044, P045)
	P046 = App.Vector(-7.8450, 0.8126, 0)
	S030 = Part.LineSegment(P045, P046)
	P047 = App.Vector(-8.1898, 0.2295, 0)
	P048 = App.Vector(-8.8273, 0.0000, 0)
	S031 = Part.Arc(P046, P047, P048)
	P049 = App.Vector(-10.9717, 0.0000, 0)
	S032 = Part.LineSegment(P048, P049)
	P050 = App.Vector(-11.7472, -0.3686, 0)
	P051 = App.Vector(-11.9509, -1.2028, 0)
	S033 = Part.Arc(P049, P050, P051)
	P052 = App.Vector(-11.4457, -3.6424, 0)
	S034 = Part.LineSegment(P051, P052)
	P053 = App.Vector(-10.9274, -4.3270, 0)
	P054 = App.Vector(-10.0693, -4.3574, 0)
	S035 = Part.Arc(P052, P053, P054)
	P055 = App.Vector(-8.1013, -3.5057, 0)
	S036 = Part.LineSegment(P054, P055)
	P056 = App.Vector(-7.4251, -3.4632, 0)
	P057 = App.Vector(-6.8770, -3.8614, 0)
	S037 = Part.Arc(P055, P056, P057)
	P058 = App.Vector(-6.1219, -4.9726, 0)
	S038 = Part.LineSegment(P057, P058)
	P059 = App.Vector(-5.9534, -5.6288, 0)
	P060 = App.Vector(-6.2418, -6.2418, 0)
	S039 = Part.Arc(P058, P059, P060)
	P061 = App.Vector(-7.7582, -7.7582, 0)
	S040 = Part.LineSegment(P060, P061)
	P062 = App.Vector(-8.0458, -8.5672, 0)
	P063 = App.Vector(-7.6001, -9.3011, 0)
	S041 = Part.Arc(P061, P062, P063)
	P064 = App.Vector(-5.5177, -10.6689, 0)
	S042 = Part.LineSegment(P063, P064)
	P065 = App.Vector(-4.6672, -10.7866, 0)
	P066 = App.Vector(-4.0389, -10.2012, 0)
	S043 = Part.Arc(P064, P065, P066)
	P067 = App.Vector(-3.2495, -8.2074, 0)
	S044 = Part.LineSegment(P066, P067)
	P068 = App.Vector(-2.8015, -7.6992, 0)
	P069 = App.Vector(-2.1324, -7.5932, 0)
	S045 = Part.Arc(P067, P068, P069)
	P070 = App.Vector(-0.8126, -7.8450, 0)
	S046 = Part.LineSegment(P069, P070)
	P071 = App.Vector(-0.2295, -8.1898, 0)
	P072 = App.Vector(-0.0000, -8.8273, 0)
	S047 = Part.Arc(P070, P071, P072)
	P073 = App.Vector(-0.0000, -10.9717, 0)
	S048 = Part.LineSegment(P072, P073)
	P074 = App.Vector(0.3686, -11.7472, 0)
	P075 = App.Vector(1.2028, -11.9509, 0)
	S049 = Part.Arc(P073, P074, P075)
	P076 = App.Vector(3.6424, -11.4457, 0)
	S050 = Part.LineSegment(P075, P076)
	P077 = App.Vector(4.3270, -10.9274, 0)
	P078 = App.Vector(4.3574, -10.0693, 0)
	S051 = Part.Arc(P076, P077, P078)
	P079 = App.Vector(3.5057, -8.1013, 0)
	S052 = Part.LineSegment(P078, P079)
	P080 = App.Vector(3.4632, -7.4251, 0)
	P081 = App.Vector(3.8614, -6.8770, 0)
	S053 = Part.Arc(P079, P080, P081)
	P082 = App.Vector(4.9726, -6.1219, 0)
	S054 = Part.LineSegment(P081, P082)
	P083 = App.Vector(5.6288, -5.9534, 0)
	P084 = App.Vector(6.2418, -6.2418, 0)
	S055 = Part.Arc(P082, P083, P084)
	P085 = App.Vector(7.7582, -7.7582, 0)
	S056 = Part.LineSegment(P084, P085)
	P086 = App.Vector(8.5672, -8.0458, 0)
	P087 = App.Vector(9.3011, -7.6001, 0)
	S057 = Part.Arc(P085, P086, P087)
	P088 = App.Vector(10.6689, -5.5177, 0)
	S058 = Part.LineSegment(P087, P088)
	P089 = App.Vector(10.7866, -4.6672, 0)
	P090 = App.Vector(10.2012, -4.0389, 0)
	S059 = Part.Arc(P088, P089, P090)
	P091 = App.Vector(8.2074, -3.2495, 0)
	S060 = Part.LineSegment(P090, P091)
	P092 = App.Vector(7.6992, -2.8015, 0)
	P093 = App.Vector(7.5932, -2.1324, 0)
	S061 = Part.Arc(P091, P092, P093)
	P094 = App.Vector(7.8450, -0.8126, 0)
	S062 = Part.LineSegment(P093, P094)
	P095 = App.Vector(8.1898, -0.2295, 0)
	P096 = App.Vector(8.8273, -0.0000, 0)
	S063 = Part.Arc(P094, P095, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047, S048, S049, S050, S051, S052, S053, S054, S055, S056, S057, S058, S059, S060, S061, S062, S063])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(15.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(10.6066, 10.6066, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(0.0000, 15.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-10.6066, 10.6066, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-15.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-10.6066, -10.6066, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-0.0000, -15.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr9():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(10.6066, -10.6066, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr10():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(40.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr11():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(36.9552, 15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr12():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(28.2843, 28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr13():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(15.3073, 36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr14():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(0.0000, 40.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr15():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-15.3073, 36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr16():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-28.2843, 28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr17():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-36.9552, 15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr18():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-40.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr19():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-36.9552, -15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr20():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-28.2843, -28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr21():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-15.3073, -36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr22():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-0.0000, -40.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr23():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(15.3073, -36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr24():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(28.2843, -28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr25():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(36.9552, -15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueC_faceProfile_Fa0_Ctr26():
	P000 = App.Vector(17.0895, 0.5000, 0)
	P001 = App.Vector(19.0711, 0.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(19.4706, 0.6719, 0)
	P003 = App.Vector(19.6203, 1.0802, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-19.6419, 0.5637, 0)
	P005 = App.Vector(19.5260, -2.2036, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(21.2401, -0.8372, 0)
	P007 = App.Vector(22.6065, -2.5513, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(-22.7371, 0.7654, 0)
	P009 = App.Vector(22.7269, 1.0252, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(23.3011, 0.5006, 0)
	P011 = App.Vector(23.8258, 1.0748, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(-23.8396, 0.7047, 0)
	P013 = App.Vector(23.7207, -2.4803, 0)
	S006 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(25.4235, -1.0998, 0)
	P015 = App.Vector(26.8039, -2.8026, 0)
	S007 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(-26.9353, 0.8891, 0)
	P017 = App.Vector(26.9303, 1.0290, 0)
	S008 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(27.5009, 0.5004, 0)
	P019 = App.Vector(28.0295, 1.0710, 0)
	S009 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(-28.0373, 0.8431, 0)
	P021 = App.Vector(27.9146, -2.7532, 0)
	S010 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(29.6092, -1.3628, 0)
	P023 = App.Vector(30.9996, -3.0575, 0)
	S011 = Part.Arc(P021, P022, P023)
	P024 = App.Vector(-31.1335, 1.0150, 0)
	P025 = App.Vector(31.1329, 1.0318, 0)
	S012 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(31.7008, 0.5003, 0)
	P027 = App.Vector(32.2323, 1.0682, 0)
	S013 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(-32.2351, 0.9798, 0)
	P029 = App.Vector(32.1079, -3.0239, 0)
	S014 = Part.Arc(P027, P028, P029)
	P030 = App.Vector(33.7964, -1.6261, 0)
	P031 = App.Vector(35.1943, -3.3146, 0)
	S015 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(-35.3315, 1.1425, 0)
	P033 = App.Vector(35.3349, 1.0339, 0)
	S016 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(35.5015, 0.6554, 0)
	P035 = App.Vector(35.8846, 0.5000, 0)
	S017 = Part.Arc(P033, P034, P035)
	P036 = App.Vector(36.9696, 0.5000, 0)
	S018 = Part.LineSegment(P035, P036)
	P037 = App.Vector(37.6909, 0.8074, 0)
	P038 = App.Vector(37.9688, 1.5405, 0)
	S019 = Part.Arc(P036, P037, P038)
	P039 = App.Vector(-38.0000, 0.0000, 0)
	P040 = App.Vector(37.9688, -1.5405, 0)
	S020 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(37.6909, -0.8074, 0)
	P042 = App.Vector(36.9696, -0.5000, 0)
	S021 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(35.8846, -0.5000, 0)
	S022 = Part.LineSegment(P042, P043)
	P044 = App.Vector(34.8048, -0.0619, 0)
	P045 = App.Vector(34.3353, 1.0047, 0)
	S023 = Part.Arc(P043, P044, P045)
	P046 = App.Vector(-34.3321, 1.1102, 0)
	P047 = App.Vector(34.1987, -3.2208, 0)
	S024 = Part.Arc(P045, P046, P047)
	P048 = App.Vector(33.7027, -2.6216, 0)
	P049 = App.Vector(33.1035, -3.1177, 0)
	S025 = Part.Arc(P047, P048, P049)
	P050 = App.Vector(-33.2347, 1.0102, 0)
	P051 = App.Vector(33.2318, 1.1013, 0)
	S026 = Part.Arc(P049, P050, P051)
	P052 = App.Vector(31.7339, -0.4991, 0)
	P053 = App.Vector(30.1335, 0.9987, 0)
	S027 = Part.Arc(P051, P052, P053)
	P054 = App.Vector(-30.1340, 0.9825, 0)
	P055 = App.Vector(30.0044, -2.9593, 0)
	S028 = Part.Arc(P053, P054, P055)
	P056 = App.Vector(29.5111, -2.3580, 0)
	P057 = App.Vector(28.9097, -2.8514, 0)
	S029 = Part.Arc(P055, P056, P057)
	P058 = App.Vector(-29.0369, 0.8731, 0)
	P059 = App.Vector(29.0288, 1.1092, 0)
	S030 = Part.Arc(P057, P058, P059)
	P060 = App.Vector(27.5391, -0.4989, 0)
	P061 = App.Vector(25.9311, 0.9908, 0)
	S031 = Part.Arc(P059, P060, P061)
	P062 = App.Vector(-25.9359, 0.8561, 0)
	P063 = App.Vector(25.8093, -2.6986, 0)
	S032 = Part.Arc(P061, P062, P063)
	P064 = App.Vector(25.3195, -2.0944, 0)
	P065 = App.Vector(24.7153, -2.5842, 0)
	S033 = Part.Arc(P063, P064, P065)
	P066 = App.Vector(-24.8392, 0.7342, 0)
	P067 = App.Vector(24.8248, 1.1198, 0)
	S034 = Part.Arc(P065, P066, P067)
	P068 = App.Vector(23.3462, -0.4984, 0)
	P069 = App.Vector(21.7279, 0.9802, 0)
	S035 = Part.Arc(P067, P068, P069)
	P070 = App.Vector(-21.7377, 0.7318, 0)
	P071 = App.Vector(21.6128, -2.4391, 0)
	S036 = Part.Arc(P069, P070, P071)
	P072 = App.Vector(21.1279, -1.8309, 0)
	P073 = App.Vector(20.5197, -2.3158, 0)
	S037 = Part.Arc(P071, P072, P073)
	P074 = App.Vector(-20.6415, 0.5924, 0)
	P075 = App.Vector(20.6188, 1.1352, 0)
	S038 = Part.Arc(P073, P074, P075)
	P076 = App.Vector(20.1969, -0.0155, 0)
	P077 = App.Vector(19.0711, -0.5000, 0)
	S039 = Part.Arc(P075, P076, P077)
	P078 = App.Vector(17.0895, -0.5000, 0)
	S040 = Part.LineSegment(P077, P078)
	P079 = App.Vector(17.0200, -0.5281, 0)
	P080 = App.Vector(16.9895, -0.5965, 0)
	S041 = Part.Arc(P078, P079, P080)
	P081 = App.Vector(-17.0000, 0.0000, 0)
	P082 = App.Vector(16.9895, 0.5965, 0)
	S042 = Part.Arc(P080, P081, P082)
	P083 = App.Vector(17.0200, 0.5281, 0)
	P084 = App.Vector(17.0895, 0.5000, 0)
	S043 = Part.Arc(P082, P083, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_springTorqueC_faceProfile_Fa0():
	FC000 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr0()
	FC001 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr1()
	FC002 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr2()
	FC003 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr3()
	FC004 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr4()
	FC005 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr5()
	FC006 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr6()
	FC007 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr7()
	FC008 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr8()
	FC009 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr9()
	FC010 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr10()
	FC011 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr11()
	FC012 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr12()
	FC013 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr13()
	FC014 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr14()
	FC015 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr15()
	FC016 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr16()
	FC017 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr17()
	FC018 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr18()
	FC019 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr19()
	FC020 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr20()
	FC021 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr21()
	FC022 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr22()
	FC023 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr23()
	FC024 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr24()
	FC025 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr25()
	FC026 = ctr_face_springTorqueC_faceProfile_Fa0_Ctr26()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008, FC009, FC010, FC011, FC012, FC013, FC014, FC015, FC016, FC017, FC018, FC019, FC020, FC021, FC022, FC023, FC024, FC025, FC026])
	rOneFace.check()
	return rOneFace

def springTorqueC_faceProfile():
	FA000 = face_springTorqueC_faceProfile_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_springTorqueC_profile():
	FIG = springTorqueC_faceProfile()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_springTorqueC_profile = fex_subpax_springTorqueC_profile()

pax_springTorqueC = subpax_springTorqueC_profile

pax_springTorqueC.check()
#pax_springTorqueC.exportBrep(f"{outFileName}.brep")
#pax_springTorqueC.exportIges(f"{outFileName}.igs")
#pax_springTorqueC.exportStep(f"{outFileName}.stp")
pax_springTorqueC.exportStl(f"{outFileName}.stl")

