# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "heliostat"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_heliostat_faceBottomPole_Fa0_Ctr0():
	P000 = App.Vector(-500.0000, 0.0000, 0)
	P001 = App.Vector(-500.0000, 10.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-300.0000, 4000.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-190.4887, 4000.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-190.4887, 3990.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-290.4887, 3990.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(-489.9874, 10.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(-489.9874, 0.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-500.0000, 0.0000, 0)
	S007 = Part.LineSegment(P007, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_heliostat_faceBottomPole_Fa0():
	FC000 = ctr_face_heliostat_faceBottomPole_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def heliostat_faceBottomPole():
	FA000 = face_heliostat_faceBottomPole_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_heliostat_faceDoor_Fa0_Ctr0():
	P000 = App.Vector(300.0000, 600.0000, 0)
	P001 = App.Vector(300.0000, 1500.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(0.0000, 1800.0000, 0)
	P003 = App.Vector(-300.0000, 1500.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-300.0000, 600.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-0.0000, 300.0000, 0)
	P006 = App.Vector(300.0000, 600.0000, 0)
	S003 = Part.Arc(P004, P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_heliostat_faceDoor_Fa0():
	FC000 = ctr_face_heliostat_faceDoor_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def heliostat_faceDoor():
	FA000 = face_heliostat_faceDoor_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_heliostat_faceBottomDisc_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(500.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_heliostat_faceBottomDisc_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(389.9874, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_heliostat_faceBottomDisc_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(429.9874, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_heliostat_faceBottomDisc_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(415.3360, 111.2889, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_heliostat_faceBottomDisc_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(372.3801, 214.9937, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_heliostat_faceBottomDisc_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(304.0470, 304.0470, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_heliostat_faceBottomDisc_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(214.9937, 372.3801, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_heliostat_faceBottomDisc_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(111.2889, 415.3360, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_heliostat_faceBottomDisc_Fa0_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(0.0000, 429.9874, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_heliostat_faceBottomDisc_Fa0_Ctr9():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(-111.2889, 415.3360, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_heliostat_faceBottomDisc_Fa0_Ctr10():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(-214.9937, 372.3801, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_heliostat_faceBottomDisc_Fa0_Ctr11():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(-304.0470, 304.0470, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_heliostat_faceBottomDisc_Fa0_Ctr12():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(-372.3801, 214.9937, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_heliostat_faceBottomDisc_Fa0_Ctr13():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(-415.3360, 111.2889, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_heliostat_faceBottomDisc_Fa0_Ctr14():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(-429.9874, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_heliostat_faceBottomDisc_Fa0_Ctr15():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(-415.3360, -111.2889, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_heliostat_faceBottomDisc_Fa0_Ctr16():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(-372.3801, -214.9937, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_heliostat_faceBottomDisc_Fa0_Ctr17():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(-304.0470, -304.0470, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_heliostat_faceBottomDisc_Fa0_Ctr18():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(-214.9937, -372.3801, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_heliostat_faceBottomDisc_Fa0_Ctr19():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(-111.2889, -415.3360, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_heliostat_faceBottomDisc_Fa0_Ctr20():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(-0.0000, -429.9874, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_heliostat_faceBottomDisc_Fa0_Ctr21():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(111.2889, -415.3360, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_heliostat_faceBottomDisc_Fa0_Ctr22():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(214.9937, -372.3801, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_heliostat_faceBottomDisc_Fa0_Ctr23():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(304.0470, -304.0470, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_heliostat_faceBottomDisc_Fa0_Ctr24():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(372.3801, -214.9937, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_heliostat_faceBottomDisc_Fa0_Ctr25():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(415.3360, -111.2889, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_heliostat_faceBottomDisc_Fa0():
	FC000 = ctr_face_heliostat_faceBottomDisc_Fa0_Ctr0()
	FC001 = ctr_face_heliostat_faceBottomDisc_Fa0_Ctr1()
	FC002 = ctr_face_heliostat_faceBottomDisc_Fa0_Ctr2()
	FC003 = ctr_face_heliostat_faceBottomDisc_Fa0_Ctr3()
	FC004 = ctr_face_heliostat_faceBottomDisc_Fa0_Ctr4()
	FC005 = ctr_face_heliostat_faceBottomDisc_Fa0_Ctr5()
	FC006 = ctr_face_heliostat_faceBottomDisc_Fa0_Ctr6()
	FC007 = ctr_face_heliostat_faceBottomDisc_Fa0_Ctr7()
	FC008 = ctr_face_heliostat_faceBottomDisc_Fa0_Ctr8()
	FC009 = ctr_face_heliostat_faceBottomDisc_Fa0_Ctr9()
	FC010 = ctr_face_heliostat_faceBottomDisc_Fa0_Ctr10()
	FC011 = ctr_face_heliostat_faceBottomDisc_Fa0_Ctr11()
	FC012 = ctr_face_heliostat_faceBottomDisc_Fa0_Ctr12()
	FC013 = ctr_face_heliostat_faceBottomDisc_Fa0_Ctr13()
	FC014 = ctr_face_heliostat_faceBottomDisc_Fa0_Ctr14()
	FC015 = ctr_face_heliostat_faceBottomDisc_Fa0_Ctr15()
	FC016 = ctr_face_heliostat_faceBottomDisc_Fa0_Ctr16()
	FC017 = ctr_face_heliostat_faceBottomDisc_Fa0_Ctr17()
	FC018 = ctr_face_heliostat_faceBottomDisc_Fa0_Ctr18()
	FC019 = ctr_face_heliostat_faceBottomDisc_Fa0_Ctr19()
	FC020 = ctr_face_heliostat_faceBottomDisc_Fa0_Ctr20()
	FC021 = ctr_face_heliostat_faceBottomDisc_Fa0_Ctr21()
	FC022 = ctr_face_heliostat_faceBottomDisc_Fa0_Ctr22()
	FC023 = ctr_face_heliostat_faceBottomDisc_Fa0_Ctr23()
	FC024 = ctr_face_heliostat_faceBottomDisc_Fa0_Ctr24()
	FC025 = ctr_face_heliostat_faceBottomDisc_Fa0_Ctr25()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008, FC009, FC010, FC011, FC012, FC013, FC014, FC015, FC016, FC017, FC018, FC019, FC020, FC021, FC022, FC023, FC024, FC025])
	rOneFace.check()
	return rOneFace

def heliostat_faceBottomDisc():
	FA000 = face_heliostat_faceBottomDisc_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_heliostat_faceTopPole_Fa0_Ctr0():
	P000 = App.Vector(-600.2381, 2200.0000, 0)
	P001 = App.Vector(-590.2256, 2200.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-489.9749, 4200.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-190.4887, 4200.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-190.4887, 4210.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-489.4737, 4210.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(-459.3985, 4810.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(-100.0000, 4810.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-100.0000, 4820.0000, 0)
	S007 = Part.LineSegment(P007, P008)
	P009 = App.Vector(-468.9098, 4820.0000, 0)
	S008 = Part.LineSegment(P008, P009)
	P010 = App.Vector(-600.2381, 2200.0000, 0)
	S009 = Part.LineSegment(P009, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_heliostat_faceTopPole_Fa0():
	FC000 = ctr_face_heliostat_faceTopPole_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def heliostat_faceTopPole():
	FA000 = face_heliostat_faceTopPole_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_heliostat_faceHorizPole_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(200.0000, App.Vector(0.0000, 4510.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_heliostat_faceHorizPole_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(190.0000, App.Vector(0.0000, 4510.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_heliostat_faceHorizPole_Fa0():
	FC000 = ctr_face_heliostat_faceHorizPole_Fa0_Ctr0()
	FC001 = ctr_face_heliostat_faceHorizPole_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def heliostat_faceHorizPole():
	FA000 = face_heliostat_faceHorizPole_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_heliostat_faceHorizPoleInt_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(190.0000, App.Vector(0.0000, 4510.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_heliostat_faceHorizPoleInt_Fa0():
	FC000 = ctr_face_heliostat_faceHorizPoleInt_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def heliostat_faceHorizPoleInt():
	FA000 = face_heliostat_faceHorizPoleInt_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_heliostat_faceDiag3_Fa0_Ctr0():
	P000 = App.Vector(-4000.0000, 4310.0000, 0)
	P001 = App.Vector(4000.0000, 4310.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(4000.0000, 4710.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-4000.0000, 4710.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-4000.0000, 4310.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_heliostat_faceDiag3_Fa0_Ctr1():
	P000 = App.Vector(-4000.0000, 4320.0000, 0)
	P001 = App.Vector(4000.0000, 4320.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(4000.0000, 4700.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-4000.0000, 4700.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-4000.0000, 4320.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_heliostat_faceDiag3_Fa0():
	FC000 = ctr_face_heliostat_faceDiag3_Fa0_Ctr0()
	FC001 = ctr_face_heliostat_faceDiag3_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def heliostat_faceDiag3():
	FA000 = face_heliostat_faceDiag3_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_heliostat_faceDiagE_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(150.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_heliostat_faceDiagE_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(140.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_heliostat_faceDiagE_Fa0():
	FC000 = ctr_face_heliostat_faceDiagE_Fa0_Ctr0()
	FC001 = ctr_face_heliostat_faceDiagE_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def heliostat_faceDiagE():
	FA000 = face_heliostat_faceDiagE_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_heliostat_faceDiagI_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(140.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_heliostat_faceDiagI_Fa0():
	FC000 = ctr_face_heliostat_faceDiagI_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def heliostat_faceDiagI():
	FA000 = face_heliostat_faceDiagI_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_heliostat_faceCleanDiag_Fa0_Ctr0():
	P000 = App.Vector(-590.2256, 2200.0000, 0)
	P001 = App.Vector(-489.9749, 4200.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(0.0000, 4200.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 1400.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-590.2256, 1400.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-590.2256, 2200.0000, 0)
	S004 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_heliostat_faceCleanDiag_Fa0():
	FC000 = ctr_face_heliostat_faceCleanDiag_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def heliostat_faceCleanDiag():
	FA000 = face_heliostat_faceCleanDiag_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_heliostat_faceHand_Fa0_Ctr0():
	P000 = App.Vector(422.8617, 5356.0909, 0)
	P001 = App.Vector(234.9232, 5424.4950, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-0.0000, 5260.0000, 0)
	P003 = App.Vector(-234.9232, 5424.4950, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-422.8617, 5356.0909, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-200.0000, 4510.0000, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(0.0000, 4710.0000, 0)
	P007 = App.Vector(200.0000, 4510.0000, 0)
	S004 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(422.8617, 5356.0909, 0)
	S005 = Part.LineSegment(P007, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_heliostat_faceHand_Fa0():
	FC000 = ctr_face_heliostat_faceHand_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def heliostat_faceHand():
	FA000 = face_heliostat_faceHand_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_heliostat_bottomPole():
	FIG = heliostat_faceBottomPole()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_heliostat_bottomPole = fex_subpax_heliostat_bottomPole()

def fex_subpax_heliostat_door():
	FIG = heliostat_faceDoor()
	VEX = FIG.extrude(App.Vector(0, 0, 1000))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_heliostat_door = fex_subpax_heliostat_door()

def fex_subpax_heliostat_bottomDisc():
	FIG = heliostat_faceBottomDisc()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_heliostat_bottomDisc = fex_subpax_heliostat_bottomDisc()

def fex_subpax_heliostat_topPole():
	FIG = heliostat_faceTopPole()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_heliostat_topPole = fex_subpax_heliostat_topPole()

def fex_subpax_heliostat_horizPole():
	FIG = heliostat_faceHorizPole()
	VEX = FIG.extrude(App.Vector(0, 0, 8000))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 4000.0000, 0.0000))
	return VFP
subpax_heliostat_horizPole = fex_subpax_heliostat_horizPole()

def fex_subpax_heliostat_horizPoleInt():
	FIG = heliostat_faceHorizPoleInt()
	VEX = FIG.extrude(App.Vector(0, 0, 8000))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 4000.0000, 0.0000))
	return VFP
subpax_heliostat_horizPoleInt = fex_subpax_heliostat_horizPoleInt()

def fex_subpax_heliostat_diag1e():
	FIG = heliostat_faceDiagE()
	VEX = FIG.extrude(App.Vector(0, 0, 4686.953167005703))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 60.4714)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 429.4248, 2200.0000))
	return VFP
subpax_heliostat_diag1e = fex_subpax_heliostat_diag1e()

def fex_subpax_heliostat_diag1i():
	FIG = heliostat_faceDiagI()
	VEX = FIG.extrude(App.Vector(0, 0, 4686.953167005703))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 60.4714)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 429.4248, 2200.0000))
	return VFP
subpax_heliostat_diag1i = fex_subpax_heliostat_diag1i()

def fex_subpax_heliostat_diag2e():
	FIG = heliostat_faceDiagE()
	VEX = FIG.extrude(App.Vector(0, 0, 4686.953167005703))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -60.4714)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, -429.4248, 2200.0000))
	return VFP
subpax_heliostat_diag2e = fex_subpax_heliostat_diag2e()

def fex_subpax_heliostat_diag2i():
	FIG = heliostat_faceDiagI()
	VEX = FIG.extrude(App.Vector(0, 0, 4686.953167005703))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -60.4714)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, -429.4248, 2200.0000))
	return VFP
subpax_heliostat_diag2i = fex_subpax_heliostat_diag2i()

def fex_subpax_heliostat_cleanDiag():
	FIG = heliostat_faceCleanDiag()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_heliostat_cleanDiag = fex_subpax_heliostat_cleanDiag()

def fex_subpax_heliostat_hand1():
	FIG = heliostat_faceHand()
	VEX = FIG.extrude(App.Vector(0, 0, 300))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, -3700.0000, 0.0000))
	return VFP
subpax_heliostat_hand1 = fex_subpax_heliostat_hand1()

def fex_subpax_heliostat_hand2():
	FIG = heliostat_faceHand()
	VEX = FIG.extrude(App.Vector(0, 0, 300))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, -1000.0000, 0.0000))
	return VFP
subpax_heliostat_hand2 = fex_subpax_heliostat_hand2()

def fex_subpax_heliostat_hand3():
	FIG = heliostat_faceHand()
	VEX = FIG.extrude(App.Vector(0, 0, 300))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 1300.0000, 0.0000))
	return VFP
subpax_heliostat_hand3 = fex_subpax_heliostat_hand3()

def fex_subpax_heliostat_hand4():
	FIG = heliostat_faceHand()
	VEX = FIG.extrude(App.Vector(0, 0, 300))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 4000.0000, 0.0000))
	return VFP
subpax_heliostat_hand4 = fex_subpax_heliostat_hand4()

def fvol_ipax_heliostat_bottomPolePlus():
	V000 = subpax_heliostat_bottomDisc
	V001 = V000.fuse(subpax_heliostat_bottomPole)
	VFC = V001.removeSplitter()
	return VFC
ipax_heliostat_bottomPolePlus = fvol_ipax_heliostat_bottomPolePlus()

def fvol_ipax_heliostat_bottomPart():
	V000 = ipax_heliostat_bottomPolePlus
	V001 = V000.cut(subpax_heliostat_door)
	VFC = V001.removeSplitter()
	return VFC
ipax_heliostat_bottomPart = fvol_ipax_heliostat_bottomPart()

def fvol_ipax_heliostat_topPlus():
	V000 = subpax_heliostat_topPole
	V001 = V000.fuse(subpax_heliostat_horizPole)
	V002 = V001.fuse(subpax_heliostat_diag1e)
	V003 = V002.fuse(subpax_heliostat_diag2e)
	V004 = V003.fuse(subpax_heliostat_hand1)
	V005 = V004.fuse(subpax_heliostat_hand2)
	V006 = V005.fuse(subpax_heliostat_hand3)
	V007 = V006.fuse(subpax_heliostat_hand4)
	VFC = V007.removeSplitter()
	return VFC
ipax_heliostat_topPlus = fvol_ipax_heliostat_topPlus()

def fvol_ipax_heliostat_topMinus():
	V000 = subpax_heliostat_horizPoleInt
	V001 = V000.fuse(subpax_heliostat_diag1i)
	V002 = V001.fuse(subpax_heliostat_diag2i)
	V003 = V002.fuse(subpax_heliostat_cleanDiag)
	VFC = V003.removeSplitter()
	return VFC
ipax_heliostat_topMinus = fvol_ipax_heliostat_topMinus()

def fvol_ipax_heliostat_topPart():
	V000 = ipax_heliostat_topPlus
	V001 = V000.cut(ipax_heliostat_topMinus)
	VFC = V001.removeSplitter()
	return VFC
ipax_heliostat_topPart = fvol_ipax_heliostat_topPart()

pax_heliostat = ipax_heliostat_topPart

pax_heliostat.check()
#pax_heliostat.exportBrep(f"{outFileName}.brep")
#pax_heliostat.exportIges(f"{outFileName}.igs")
#pax_heliostat.exportStep(f"{outFileName}.stp")
pax_heliostat.exportStl(f"{outFileName}.stl")

