# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "springTorqueA"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(42.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(8.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(10.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(9.2388, 3.8268, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(7.0711, 7.0711, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(3.8268, 9.2388, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(0.0000, 10.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-3.8268, 9.2388, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-7.0711, 7.0711, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr9():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-9.2388, 3.8268, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr10():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-10.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr11():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-9.2388, -3.8268, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr12():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-7.0711, -7.0711, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr13():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-3.8268, -9.2388, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr14():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-0.0000, -10.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr15():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(3.8268, -9.2388, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr16():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(7.0711, -7.0711, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr17():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(9.2388, -3.8268, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr18():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(40.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr19():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(36.9552, 15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr20():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(28.2843, 28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr21():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(15.3073, 36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr22():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(0.0000, 40.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr23():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-15.3073, 36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr24():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-28.2843, 28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr25():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-36.9552, 15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr26():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-40.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr27():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-36.9552, -15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr28():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-28.2843, -28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr29():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-15.3073, -36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr30():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(-0.0000, -40.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr31():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(15.3073, -36.9552, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr32():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(28.2843, -28.2843, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr33():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.0000, App.Vector(36.9552, -15.3073, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr34():
	P000 = App.Vector(14.3091, 1.5000, 0)
	P001 = App.Vector(34.7095, 1.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(36.9631, 2.5197, 0)
	P003 = App.Vector(37.6846, 4.8857, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(30.7426, 22.3358, 0)
	P005 = App.Vector(16.2918, 34.3304, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(13.8186, 34.3753, 0)
	P007 = App.Vector(12.1524, 32.5472, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(5.8483, 13.1452, 0)
	S004 = Part.LineSegment(P007, P008)
	P009 = App.Vector(5.8528, 11.2776, 0)
	P010 = App.Vector(6.9612, 9.7745, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(9.7082, 7.0534, 0)
	P012 = App.Vector(11.4473, 3.6000, 0)
	S006 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(12.5343, 2.0813, 0)
	P014 = App.Vector(14.3091, 1.5000, 0)
	S007 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr35():
	P000 = App.Vector(2.9952, 14.0723, 0)
	P001 = App.Vector(9.2992, 33.4742, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(9.0258, 35.9326, 0)
	P003 = App.Vector(6.9986, 37.3500, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-11.7426, 36.1401, 0)
	P005 = App.Vector(-27.6157, 26.1031, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(-28.4227, 23.7649, 0)
	P007 = App.Vector(-27.1989, 21.6153, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(-10.6946, 9.6242, 0)
	S004 = Part.LineSegment(P007, P008)
	P009 = App.Vector(-8.9171, 9.0513, 0)
	P010 = App.Vector(-7.1450, 9.6410, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(-3.7082, 11.4127, 0)
	P012 = App.Vector(0.1136, 11.9995, 0)
	S006 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(1.8938, 12.5640, 0)
	P014 = App.Vector(2.9952, 14.0723, 0)
	S007 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr36():
	P000 = App.Vector(-12.4580, 7.1971, 0)
	P001 = App.Vector(-28.9623, 19.1882, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-31.3848, 19.6878, 0)
	P003 = App.Vector(-33.3592, 18.1978, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-38.0000, 0.0000, 0)
	P005 = App.Vector(-33.3592, -18.1978, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(-31.3848, -19.6878, 0)
	P007 = App.Vector(-28.9623, -19.1882, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(-12.4580, -7.1971, 0)
	S004 = Part.LineSegment(P007, P008)
	P009 = App.Vector(-11.3638, -5.6836, 0)
	P010 = App.Vector(-11.3771, -3.8161, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(-12.0000, -0.0000, 0)
	P012 = App.Vector(-11.3771, 3.8161, 0)
	S006 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(-11.3638, 5.6836, 0)
	P014 = App.Vector(-12.4580, 7.1971, 0)
	S007 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr37():
	P000 = App.Vector(-10.6946, -9.6242, 0)
	P001 = App.Vector(-27.1989, -21.6153, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-28.4227, -23.7649, 0)
	P003 = App.Vector(-27.6157, -26.1031, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-11.7426, -36.1401, 0)
	P005 = App.Vector(6.9986, -37.3500, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(9.0258, -35.9326, 0)
	P007 = App.Vector(9.2992, -33.4742, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(2.9952, -14.0723, 0)
	S004 = Part.LineSegment(P007, P008)
	P009 = App.Vector(1.8938, -12.5640, 0)
	P010 = App.Vector(0.1136, -11.9995, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(-3.7082, -11.4127, 0)
	P012 = App.Vector(-7.1450, -9.6410, 0)
	S006 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(-8.9171, -9.0513, 0)
	P014 = App.Vector(-10.6946, -9.6242, 0)
	S007 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_springTorqueA_faceProfile_Fa0_Ctr38():
	P000 = App.Vector(5.8483, -13.1452, 0)
	P001 = App.Vector(12.1524, -32.5472, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(13.8186, -34.3753, 0)
	P003 = App.Vector(16.2918, -34.3304, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(30.7426, -22.3358, 0)
	P005 = App.Vector(37.6846, -4.8857, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(36.9631, -2.5197, 0)
	P007 = App.Vector(34.7095, -1.5000, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(14.3091, -1.5000, 0)
	S004 = Part.LineSegment(P007, P008)
	P009 = App.Vector(12.5343, -2.0813, 0)
	P010 = App.Vector(11.4473, -3.6000, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(9.7082, -7.0534, 0)
	P012 = App.Vector(6.9612, -9.7745, 0)
	S006 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(5.8528, -11.2776, 0)
	P014 = App.Vector(5.8483, -13.1452, 0)
	S007 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_springTorqueA_faceProfile_Fa0():
	FC000 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr0()
	FC001 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr1()
	FC002 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr2()
	FC003 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr3()
	FC004 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr4()
	FC005 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr5()
	FC006 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr6()
	FC007 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr7()
	FC008 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr8()
	FC009 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr9()
	FC010 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr10()
	FC011 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr11()
	FC012 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr12()
	FC013 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr13()
	FC014 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr14()
	FC015 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr15()
	FC016 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr16()
	FC017 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr17()
	FC018 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr18()
	FC019 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr19()
	FC020 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr20()
	FC021 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr21()
	FC022 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr22()
	FC023 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr23()
	FC024 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr24()
	FC025 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr25()
	FC026 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr26()
	FC027 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr27()
	FC028 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr28()
	FC029 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr29()
	FC030 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr30()
	FC031 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr31()
	FC032 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr32()
	FC033 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr33()
	FC034 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr34()
	FC035 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr35()
	FC036 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr36()
	FC037 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr37()
	FC038 = ctr_face_springTorqueA_faceProfile_Fa0_Ctr38()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008, FC009, FC010, FC011, FC012, FC013, FC014, FC015, FC016, FC017, FC018, FC019, FC020, FC021, FC022, FC023, FC024, FC025, FC026, FC027, FC028, FC029, FC030, FC031, FC032, FC033, FC034, FC035, FC036, FC037, FC038])
	rOneFace.check()
	return rOneFace

def springTorqueA_faceProfile():
	FA000 = face_springTorqueA_faceProfile_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_springTorqueA_profile():
	FIG = springTorqueA_faceProfile()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_springTorqueA_profile = fex_subpax_springTorqueA_profile()

pax_springTorqueA = subpax_springTorqueA_profile

pax_springTorqueA.check()
#pax_springTorqueA.exportBrep(f"{outFileName}.brep")
#pax_springTorqueA.exportIges(f"{outFileName}.igs")
#pax_springTorqueA.exportStep(f"{outFileName}.stp")
pax_springTorqueA.exportStl(f"{outFileName}.stl")

