# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "plugTorque"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_plugTorque_faceIntern_Fa0_Ctr0():
	P000 = App.Vector(9.6207, -0.0000, 0)
	P001 = App.Vector(11.7815, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(12.5545, 0.3656, 0)
	P003 = App.Vector(12.7623, 1.1951, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(12.2482, 3.7798, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(11.7388, 4.4666, 0)
	P006 = App.Vector(10.8847, 4.5086, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(8.8883, 3.6817, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(8.2154, 3.6486, 0)
	P009 = App.Vector(7.6742, 4.0500, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(6.6785, 5.5402, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(6.5148, 6.1938, 0)
	P012 = App.Vector(6.8028, 6.8028, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(8.3308, 8.3308, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(8.6189, 9.1359, 0)
	P015 = App.Vector(8.1792, 9.8694, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(5.9880, 11.3335, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(5.1422, 11.4589, 0)
	P018 = App.Vector(4.5086, 10.8847, 0)
	S011 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(3.6817, 8.8883, 0)
	S012 = Part.LineSegment(P018, P019)
	P020 = App.Vector(3.2292, 8.3891, 0)
	P021 = App.Vector(2.5627, 8.2902, 0)
	S013 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(0.8049, 8.6399, 0)
	S014 = Part.LineSegment(P021, P022)
	P023 = App.Vector(0.2270, 8.9863, 0)
	P024 = App.Vector(0.0000, 9.6207, 0)
	S015 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(0.0000, 11.7815, 0)
	S016 = Part.LineSegment(P024, P025)
	P026 = App.Vector(-0.3656, 12.5545, 0)
	P027 = App.Vector(-1.1951, 12.7623, 0)
	S017 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(-3.7798, 12.2482, 0)
	S018 = Part.LineSegment(P027, P028)
	P029 = App.Vector(-4.4666, 11.7388, 0)
	P030 = App.Vector(-4.5086, 10.8847, 0)
	S019 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(-3.6817, 8.8883, 0)
	S020 = Part.LineSegment(P030, P031)
	P032 = App.Vector(-3.6486, 8.2154, 0)
	P033 = App.Vector(-4.0500, 7.6742, 0)
	S021 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(-5.5402, 6.6785, 0)
	S022 = Part.LineSegment(P033, P034)
	P035 = App.Vector(-6.1938, 6.5148, 0)
	P036 = App.Vector(-6.8028, 6.8028, 0)
	S023 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-8.3308, 8.3308, 0)
	S024 = Part.LineSegment(P036, P037)
	P038 = App.Vector(-9.1359, 8.6189, 0)
	P039 = App.Vector(-9.8694, 8.1792, 0)
	S025 = Part.Arc(P037, P038, P039)
	P040 = App.Vector(-11.3335, 5.9880, 0)
	S026 = Part.LineSegment(P039, P040)
	P041 = App.Vector(-11.4589, 5.1422, 0)
	P042 = App.Vector(-10.8847, 4.5086, 0)
	S027 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(-8.8883, 3.6817, 0)
	S028 = Part.LineSegment(P042, P043)
	P044 = App.Vector(-8.3891, 3.2292, 0)
	P045 = App.Vector(-8.2902, 2.5627, 0)
	S029 = Part.Arc(P043, P044, P045)
	P046 = App.Vector(-8.6399, 0.8049, 0)
	S030 = Part.LineSegment(P045, P046)
	P047 = App.Vector(-8.9863, 0.2270, 0)
	P048 = App.Vector(-9.6207, 0.0000, 0)
	S031 = Part.Arc(P046, P047, P048)
	P049 = App.Vector(-11.7815, 0.0000, 0)
	S032 = Part.LineSegment(P048, P049)
	P050 = App.Vector(-12.5545, -0.3656, 0)
	P051 = App.Vector(-12.7623, -1.1951, 0)
	S033 = Part.Arc(P049, P050, P051)
	P052 = App.Vector(-12.2482, -3.7798, 0)
	S034 = Part.LineSegment(P051, P052)
	P053 = App.Vector(-11.7388, -4.4666, 0)
	P054 = App.Vector(-10.8847, -4.5086, 0)
	S035 = Part.Arc(P052, P053, P054)
	P055 = App.Vector(-8.8883, -3.6817, 0)
	S036 = Part.LineSegment(P054, P055)
	P056 = App.Vector(-8.2154, -3.6486, 0)
	P057 = App.Vector(-7.6742, -4.0500, 0)
	S037 = Part.Arc(P055, P056, P057)
	P058 = App.Vector(-6.6785, -5.5402, 0)
	S038 = Part.LineSegment(P057, P058)
	P059 = App.Vector(-6.5148, -6.1938, 0)
	P060 = App.Vector(-6.8028, -6.8028, 0)
	S039 = Part.Arc(P058, P059, P060)
	P061 = App.Vector(-8.3308, -8.3308, 0)
	S040 = Part.LineSegment(P060, P061)
	P062 = App.Vector(-8.6189, -9.1359, 0)
	P063 = App.Vector(-8.1792, -9.8694, 0)
	S041 = Part.Arc(P061, P062, P063)
	P064 = App.Vector(-5.9880, -11.3335, 0)
	S042 = Part.LineSegment(P063, P064)
	P065 = App.Vector(-5.1422, -11.4589, 0)
	P066 = App.Vector(-4.5086, -10.8847, 0)
	S043 = Part.Arc(P064, P065, P066)
	P067 = App.Vector(-3.6817, -8.8883, 0)
	S044 = Part.LineSegment(P066, P067)
	P068 = App.Vector(-3.2292, -8.3891, 0)
	P069 = App.Vector(-2.5627, -8.2902, 0)
	S045 = Part.Arc(P067, P068, P069)
	P070 = App.Vector(-0.8049, -8.6399, 0)
	S046 = Part.LineSegment(P069, P070)
	P071 = App.Vector(-0.2270, -8.9863, 0)
	P072 = App.Vector(-0.0000, -9.6207, 0)
	S047 = Part.Arc(P070, P071, P072)
	P073 = App.Vector(-0.0000, -11.7815, 0)
	S048 = Part.LineSegment(P072, P073)
	P074 = App.Vector(0.3656, -12.5545, 0)
	P075 = App.Vector(1.1951, -12.7623, 0)
	S049 = Part.Arc(P073, P074, P075)
	P076 = App.Vector(3.7798, -12.2482, 0)
	S050 = Part.LineSegment(P075, P076)
	P077 = App.Vector(4.4666, -11.7388, 0)
	P078 = App.Vector(4.5086, -10.8847, 0)
	S051 = Part.Arc(P076, P077, P078)
	P079 = App.Vector(3.6817, -8.8883, 0)
	S052 = Part.LineSegment(P078, P079)
	P080 = App.Vector(3.6486, -8.2154, 0)
	P081 = App.Vector(4.0500, -7.6742, 0)
	S053 = Part.Arc(P079, P080, P081)
	P082 = App.Vector(5.5402, -6.6785, 0)
	S054 = Part.LineSegment(P081, P082)
	P083 = App.Vector(6.1938, -6.5148, 0)
	P084 = App.Vector(6.8028, -6.8028, 0)
	S055 = Part.Arc(P082, P083, P084)
	P085 = App.Vector(8.3308, -8.3308, 0)
	S056 = Part.LineSegment(P084, P085)
	P086 = App.Vector(9.1359, -8.6189, 0)
	P087 = App.Vector(9.8694, -8.1792, 0)
	S057 = Part.Arc(P085, P086, P087)
	P088 = App.Vector(11.3335, -5.9880, 0)
	S058 = Part.LineSegment(P087, P088)
	P089 = App.Vector(11.4589, -5.1422, 0)
	P090 = App.Vector(10.8847, -4.5086, 0)
	S059 = Part.Arc(P088, P089, P090)
	P091 = App.Vector(8.8883, -3.6817, 0)
	S060 = Part.LineSegment(P090, P091)
	P092 = App.Vector(8.3891, -3.2292, 0)
	P093 = App.Vector(8.2902, -2.5627, 0)
	S061 = Part.Arc(P091, P092, P093)
	P094 = App.Vector(8.6399, -0.8049, 0)
	S062 = Part.LineSegment(P093, P094)
	P095 = App.Vector(8.9863, -0.2270, 0)
	P096 = App.Vector(9.6207, -0.0000, 0)
	S063 = Part.Arc(P094, P095, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047, S048, S049, S050, S051, S052, S053, S054, S055, S056, S057, S058, S059, S060, S061, S062, S063])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_plugTorque_faceIntern_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(3.5000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_plugTorque_faceIntern_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(6.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_plugTorque_faceIntern_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(1.8541, 5.7063, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_plugTorque_faceIntern_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-4.8541, 3.5267, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_plugTorque_faceIntern_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-4.8541, -3.5267, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_plugTorque_faceIntern_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(1.8541, -5.7063, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_plugTorque_faceIntern_Fa0():
	FC000 = ctr_face_plugTorque_faceIntern_Fa0_Ctr0()
	FC001 = ctr_face_plugTorque_faceIntern_Fa0_Ctr1()
	FC002 = ctr_face_plugTorque_faceIntern_Fa0_Ctr2()
	FC003 = ctr_face_plugTorque_faceIntern_Fa0_Ctr3()
	FC004 = ctr_face_plugTorque_faceIntern_Fa0_Ctr4()
	FC005 = ctr_face_plugTorque_faceIntern_Fa0_Ctr5()
	FC006 = ctr_face_plugTorque_faceIntern_Fa0_Ctr6()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006])
	rOneFace.check()
	return rOneFace

def plugTorque_faceIntern():
	FA000 = face_plugTorque_faceIntern_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_plugTorque_faceExtern_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(18.5000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_plugTorque_faceExtern_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(16.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_plugTorque_faceExtern_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(11.3137, 11.3137, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_plugTorque_faceExtern_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(0.0000, 16.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_plugTorque_faceExtern_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-11.3137, 11.3137, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_plugTorque_faceExtern_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-16.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_plugTorque_faceExtern_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-11.3137, -11.3137, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_plugTorque_faceExtern_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(-0.0000, -16.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_plugTorque_faceExtern_Fa0_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(1.5000, App.Vector(11.3137, -11.3137, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_plugTorque_faceExtern_Fa0_Ctr9():
	P000 = App.Vector(9.8273, -0.0000, 0)
	P001 = App.Vector(11.9717, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(12.7472, 0.3686, 0)
	P003 = App.Vector(12.9509, 1.2028, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(12.3634, 4.0396, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(11.8452, 4.7242, 0)
	P006 = App.Vector(10.9871, 4.7545, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(9.0190, 3.9029, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(8.3429, 3.8603, 0)
	P009 = App.Vector(7.7948, 4.2586, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(6.8290, 5.6797, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(6.6605, 6.3359, 0)
	P012 = App.Vector(6.9489, 6.9489, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(8.4653, 8.4653, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(8.7529, 9.2743, 0)
	P015 = App.Vector(8.3072, 10.0082, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(5.8859, 11.5987, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(5.0353, 11.7163, 0)
	P018 = App.Vector(4.4071, 11.1310, 0)
	S011 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(3.6177, 9.1372, 0)
	S012 = Part.LineSegment(P018, P019)
	P020 = App.Vector(3.1696, 8.6290, 0)
	P021 = App.Vector(2.5005, 8.5230, 0)
	S013 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(0.8126, 8.8450, 0)
	S014 = Part.LineSegment(P021, P022)
	P023 = App.Vector(0.2295, 9.1898, 0)
	P024 = App.Vector(0.0000, 9.8273, 0)
	S015 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(0.0000, 11.9717, 0)
	S016 = Part.LineSegment(P024, P025)
	P026 = App.Vector(-0.3686, 12.7472, 0)
	P027 = App.Vector(-1.2028, 12.9509, 0)
	S017 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(-4.0396, 12.3634, 0)
	S018 = Part.LineSegment(P027, P028)
	P029 = App.Vector(-4.7242, 11.8452, 0)
	P030 = App.Vector(-4.7545, 10.9871, 0)
	S019 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(-3.9029, 9.0190, 0)
	S020 = Part.LineSegment(P030, P031)
	P032 = App.Vector(-3.8603, 8.3429, 0)
	P033 = App.Vector(-4.2586, 7.7948, 0)
	S021 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(-5.6797, 6.8290, 0)
	S022 = Part.LineSegment(P033, P034)
	P035 = App.Vector(-6.3359, 6.6605, 0)
	P036 = App.Vector(-6.9489, 6.9489, 0)
	S023 = Part.Arc(P034, P035, P036)
	P037 = App.Vector(-8.4653, 8.4653, 0)
	S024 = Part.LineSegment(P036, P037)
	P038 = App.Vector(-9.2743, 8.7529, 0)
	P039 = App.Vector(-10.0082, 8.3072, 0)
	S025 = Part.Arc(P037, P038, P039)
	P040 = App.Vector(-11.5987, 5.8859, 0)
	S026 = Part.LineSegment(P039, P040)
	P041 = App.Vector(-11.7163, 5.0353, 0)
	P042 = App.Vector(-11.1310, 4.4071, 0)
	S027 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(-9.1372, 3.6177, 0)
	S028 = Part.LineSegment(P042, P043)
	P044 = App.Vector(-8.6290, 3.1696, 0)
	P045 = App.Vector(-8.5230, 2.5005, 0)
	S029 = Part.Arc(P043, P044, P045)
	P046 = App.Vector(-8.8450, 0.8126, 0)
	S030 = Part.LineSegment(P045, P046)
	P047 = App.Vector(-9.1898, 0.2295, 0)
	P048 = App.Vector(-9.8273, 0.0000, 0)
	S031 = Part.Arc(P046, P047, P048)
	P049 = App.Vector(-11.9717, 0.0000, 0)
	S032 = Part.LineSegment(P048, P049)
	P050 = App.Vector(-12.7472, -0.3686, 0)
	P051 = App.Vector(-12.9509, -1.2028, 0)
	S033 = Part.Arc(P049, P050, P051)
	P052 = App.Vector(-12.3634, -4.0396, 0)
	S034 = Part.LineSegment(P051, P052)
	P053 = App.Vector(-11.8452, -4.7242, 0)
	P054 = App.Vector(-10.9871, -4.7545, 0)
	S035 = Part.Arc(P052, P053, P054)
	P055 = App.Vector(-9.0190, -3.9029, 0)
	S036 = Part.LineSegment(P054, P055)
	P056 = App.Vector(-8.3429, -3.8603, 0)
	P057 = App.Vector(-7.7948, -4.2586, 0)
	S037 = Part.Arc(P055, P056, P057)
	P058 = App.Vector(-6.8290, -5.6797, 0)
	S038 = Part.LineSegment(P057, P058)
	P059 = App.Vector(-6.6605, -6.3359, 0)
	P060 = App.Vector(-6.9489, -6.9489, 0)
	S039 = Part.Arc(P058, P059, P060)
	P061 = App.Vector(-8.4653, -8.4653, 0)
	S040 = Part.LineSegment(P060, P061)
	P062 = App.Vector(-8.7529, -9.2743, 0)
	P063 = App.Vector(-8.3072, -10.0082, 0)
	S041 = Part.Arc(P061, P062, P063)
	P064 = App.Vector(-5.8859, -11.5987, 0)
	S042 = Part.LineSegment(P063, P064)
	P065 = App.Vector(-5.0353, -11.7163, 0)
	P066 = App.Vector(-4.4071, -11.1310, 0)
	S043 = Part.Arc(P064, P065, P066)
	P067 = App.Vector(-3.6177, -9.1372, 0)
	S044 = Part.LineSegment(P066, P067)
	P068 = App.Vector(-3.1696, -8.6290, 0)
	P069 = App.Vector(-2.5005, -8.5230, 0)
	S045 = Part.Arc(P067, P068, P069)
	P070 = App.Vector(-0.8126, -8.8450, 0)
	S046 = Part.LineSegment(P069, P070)
	P071 = App.Vector(-0.2295, -9.1898, 0)
	P072 = App.Vector(-0.0000, -9.8273, 0)
	S047 = Part.Arc(P070, P071, P072)
	P073 = App.Vector(-0.0000, -11.9717, 0)
	S048 = Part.LineSegment(P072, P073)
	P074 = App.Vector(0.3686, -12.7472, 0)
	P075 = App.Vector(1.2028, -12.9509, 0)
	S049 = Part.Arc(P073, P074, P075)
	P076 = App.Vector(4.0396, -12.3634, 0)
	S050 = Part.LineSegment(P075, P076)
	P077 = App.Vector(4.7242, -11.8452, 0)
	P078 = App.Vector(4.7545, -10.9871, 0)
	S051 = Part.Arc(P076, P077, P078)
	P079 = App.Vector(3.9029, -9.0190, 0)
	S052 = Part.LineSegment(P078, P079)
	P080 = App.Vector(3.8603, -8.3429, 0)
	P081 = App.Vector(4.2586, -7.7948, 0)
	S053 = Part.Arc(P079, P080, P081)
	P082 = App.Vector(5.6797, -6.8290, 0)
	S054 = Part.LineSegment(P081, P082)
	P083 = App.Vector(6.3359, -6.6605, 0)
	P084 = App.Vector(6.9489, -6.9489, 0)
	S055 = Part.Arc(P082, P083, P084)
	P085 = App.Vector(8.4653, -8.4653, 0)
	S056 = Part.LineSegment(P084, P085)
	P086 = App.Vector(9.2743, -8.7529, 0)
	P087 = App.Vector(10.0082, -8.3072, 0)
	S057 = Part.Arc(P085, P086, P087)
	P088 = App.Vector(11.5987, -5.8859, 0)
	S058 = Part.LineSegment(P087, P088)
	P089 = App.Vector(11.7163, -5.0353, 0)
	P090 = App.Vector(11.1310, -4.4071, 0)
	S059 = Part.Arc(P088, P089, P090)
	P091 = App.Vector(9.1372, -3.6177, 0)
	S060 = Part.LineSegment(P090, P091)
	P092 = App.Vector(8.6290, -3.1696, 0)
	P093 = App.Vector(8.5230, -2.5005, 0)
	S061 = Part.Arc(P091, P092, P093)
	P094 = App.Vector(8.8450, -0.8126, 0)
	S062 = Part.LineSegment(P093, P094)
	P095 = App.Vector(9.1898, -0.2295, 0)
	P096 = App.Vector(9.8273, -0.0000, 0)
	S063 = Part.Arc(P094, P095, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047, S048, S049, S050, S051, S052, S053, S054, S055, S056, S057, S058, S059, S060, S061, S062, S063])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_plugTorque_faceExtern_Fa0():
	FC000 = ctr_face_plugTorque_faceExtern_Fa0_Ctr0()
	FC001 = ctr_face_plugTorque_faceExtern_Fa0_Ctr1()
	FC002 = ctr_face_plugTorque_faceExtern_Fa0_Ctr2()
	FC003 = ctr_face_plugTorque_faceExtern_Fa0_Ctr3()
	FC004 = ctr_face_plugTorque_faceExtern_Fa0_Ctr4()
	FC005 = ctr_face_plugTorque_faceExtern_Fa0_Ctr5()
	FC006 = ctr_face_plugTorque_faceExtern_Fa0_Ctr6()
	FC007 = ctr_face_plugTorque_faceExtern_Fa0_Ctr7()
	FC008 = ctr_face_plugTorque_faceExtern_Fa0_Ctr8()
	FC009 = ctr_face_plugTorque_faceExtern_Fa0_Ctr9()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008, FC009])
	rOneFace.check()
	return rOneFace

def plugTorque_faceExtern():
	FA000 = face_plugTorque_faceExtern_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_plugTorque_intern():
	FIG = plugTorque_faceIntern()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_plugTorque_intern = fex_subpax_plugTorque_intern()

def fex_subpax_plugTorque_extern():
	FIG = plugTorque_faceExtern()
	VEX = FIG.extrude(App.Vector(0, 0, 1))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -0.4500)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_plugTorque_extern = fex_subpax_plugTorque_extern()

def fvol_pax_plugTorque():
	V000 = subpax_plugTorque_intern
	V001 = V000.fuse(subpax_plugTorque_extern)
	VFC = V001.removeSplitter()
	return VFC
pax_plugTorque = fvol_pax_plugTorque()


pax_plugTorque.check()
#pax_plugTorque.exportBrep(f"{outFileName}.brep")
#pax_plugTorque.exportIges(f"{outFileName}.igs")
#pax_plugTorque.exportStep(f"{outFileName}.stp")
pax_plugTorque.exportStl(f"{outFileName}.stl")

